### ISSUE TITLE
Port to Linux

### ISSUE THREAD

**Issue by Rexadev** [files-community/Files#10043]
### What feature or improvement do you think would benefit Files?

I want to use this on Linux

### Requirements

- I will have nice explorer on Linux

### Files Version

2.0

### Windows Version

Windows 10 21H!

**Comment by Josh-65** [comment]
Files doesnt have the support, time to port to linux. It also heavily use Windows only tools

**Comment by yaichenbaum** [comment]
Thank you for your feedback, our mission is to build the best File Manager for Windows and we don't have plans to bring this to Linux right now.

**Comment by softyoda** [comment]
What are decent linux alternative then ? it's 2026, the entire world yearn for year of the linux desktop, and we still have only have dolphin -_-


(same for windows terminal too, i haven't found any decent alternative for it on linux despite this os relying on the terminal for 99% of its usage)

**Comment by Josh65-2201** [comment]
@softyoda We aren't Linux user's or a community based on it, you should go to the many on Reddit or other places.

**Comment by softyoda** [comment]
I have spend way more time on hundreds of reddit thread by nerdy who confuse terminal with UX affordance that a gui bring, or simply cannot comprehend what design even is in the first place and why nobody use linux. I wish FilePilot were FLOSS on linux, or that there were more choice, i have peregrinated opon so many threads of AlternativeTo, hackernews threads, yet nothing semed to rise, all speak of dolphin or nemo as something usable...
I answer because i saw something new not ever seen in my peregrination, someone @yair100 commented here but somehow got removed or invisiblised i don't know how. I still have the email so i'll post his message here : 

When i see this thing, i already react "FINALLY THE ARCENSTONE OF FILE EXPLORER" but having the comment removed from there and how easy is it for nowadays AI scrapper to get 5thousands stars on github, i wish to have advice from you, dear nerd, do you believe it's a giant scam or it's safe ?

**Comment by yair100** [comment]
@softyoda I removed my comment since this is not the proper forum for it. Please feel to reach out on our Discord server to continue this conversation.
