### ISSUE TITLE
When looking at downloads, it shows pins files that were downloaded over a year ago.

### ISSUE THREAD

**Issue by DanteAndHubble** [files-community/Files#10181]
### Description

Everytimg I open the app, I have to spend a minute scrolling to the very top because downloads always opens at items from this year.

please help

### Steps To Reproduce

Click on downloads

### Steps to fix

I dont know how to fix this

### Files Version

Version: 2.3.12.0 OS Version: 10.0.22000.978

### Windows Version

Edition	Windows 11 Pro Version	21H2 Installed on	‎11/‎7/‎2021 OS build	22000.978 Experience	Windows Feature Experience Pack 1000.22000.978.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/73189037/195247047-9e3b65a4-10c4-443f-a516-2065b666c26a.png)

**Comment by yaichenbaum** [comment]
What happens if you reset the app?

**Comment by sthivaios** [comment]
I mean, I can't make a file look like it is 1 years old, but I have files from last week and it always opens at the beginning where the first files are. So, I am not exactly sure about year-old files but for weeks-old files, it always opens at the beginning. So in my case, I would consider this bug as invalid. As @yair100 said, try resetting the app, and restarting your computer, as well as uninstalling and reinstalling the app. Also, I checked the bug on the PRE version. If your version is outdated, I suggest getting the latest updates first. If you are not to contribute in the community about this, do not download the PRE (preview) version as it can sometimes be unstable, (because that is the point - getting the latest updates for testing purposes).

**Comment by Josh-65** [comment]
Merging with #5825. 
I believe it depends on how many items there are not if there grouped or not, I've had the scrolling issue when there was no grouping and in different layout modes. might be Files is loading items from B to Z first then items with symbols, number and A at the start which would lead items being loaded above the first viewpoint.

**Comment by DanteAndHubble** [comment]
> What happens if you reset the app?

I just did, no luck
