### ISSUE TITLE
Bug: Trying to open properties from blank area of a folder doesn't open window

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#10289]
### Description

Read steps to reproduce for a clearer understanding. 
Side note when right clicking a folder and opening properties it will open two windows of the same folder just clicked on.

### Steps To Reproduce

1. Go to a folder
2. Right click empty space
3. Click properties
4. See window doesn't open

### Steps to fix

Fix issue preventing window from opening

### Files Version

2.3.51.0

### Windows Version

10.0.22621.675

### Relevant Assets/Logs

Haven't been generated.

**Comment by cinqmilleans** [comment]
@yair100 I identified the line of code to fix for this bug. However, it would be nice if the Show Properties command in the context menu corresponded to that in the action bar. It should be possible to open the properties from the quick actions when no element is selected. Is this the expected behavior?

**Comment by yaichenbaum** [comment]
Not currently but I don't see why it shouldn't be supported.
