### ISSUE TITLE
Feature: Add option to merge two tabs into split pane

### ISSUE THREAD

**Issue by verdaderoken** [files-community/Files#10336]
### What feature or improvement do you think would benefit Files?

Merging tabs would be a great feature for productivity specially for touch users

This feature helps users quickly use dual pane by dragging an existing tab over another tab. 
This also lets new users discover dual pane accidentally when dragging a tab 

from this:
![image](https://user-images.githubusercontent.com/88200096/198887146-59151f56-9703-4af3-93ca-37fdb286d455.png)

to this:
![image](https://user-images.githubusercontent.com/88200096/198887540-312d12d8-cfe7-43a2-a2ef-aa46d51227aa.png)

When ungrouping, there should be an option here like "**Ungroup tabs**"
![image](https://user-images.githubusercontent.com/88200096/198887276-dd92daf4-01a6-4f53-ab92-7b33c63cb164.png)

### Requirements

1. Implement a feature where dragging a tab over another tab would transform it into a grouped tab which also triggers a secondary pane
2. Have the option to ungroup the tabs in context menu of the tab

### Files Version

2.3.54.0

### Windows Version

22623.875

### Comments

I don't know if it's possible to do but I'll just issue this here. :)

**Comment by yaichenbaum** [comment]
> This also lets new users discover dual pane accidentally when dragging a tab

This can be a downside as well

Is this something you've seen in other apps? I'd like to get a better grasp on the user experience here.

**Comment by cinqmilleans** [comment]
In Files, there is no true Dual Panel mode. It is only possible to display 2 folders at the same time in the same tab. Other softwares uses reverse logic, each panel has its own tabs.

An expected use of the dual panel mode is to sort your hard drives, keeping the source folders on the left and the target folders on the right. There are necessarily several source or target folders since the goal is to sort. It is possible to simulate this by placing 2 windows side by side, but it is the purpose of a Double Panel to avoid this tedious manipulation.

Currently.
- It is not possible to use tabs when using panels. If I want to keep a folder on the left, and 2 others on the right, I have to create 2 tabs from scratch.
- To use it, it is mandatory to access the contextual menu of a folder to open a second panel. There isn't an easy access button or keyboard shortcut to open it (on the home page).
- From the second panel, there is an option to open a folder in the second panel, which is the same as just opening it. Why not change to "Open in main panel"?

The reverse logic (2 tab panels) requires reworking the entire interface. Also, users are used to having tabs at the top like in a browser.

Some suggestions that can be implemented easily without changing everything.
- Have a button to activate/deactivate the Dual Pane (as for the Preview Pane). Enabled, all tabs contain 2 folders. Disabled, all have only one.
- The second panel is the homepage by default. If it's the homepage, there's no need to display it in the tab name.
- In Dual Pane, opening a tab automatically copies the other folder, keeping the order of the folders. Ex: From A|B, I open C in a tab from B, it opens A|C in a tab.
- The contextual menu can offer specific options (copy/move to the second panel, ...). These actions can be accessed in the toolbar, only the active options (depending on the active panel).
- From the second panel, the contextual menu offers to open in the main panel instead of the second.
- We can add an entry in the context menu to exchange the position of the 2 tabs, it is convenient to be organized.

**Comment by cinqmilleans** [comment]
@yair100 What do you think ?

**Comment by yaichenbaum** [comment]
Luke is currently rebuilding the pane feature so let's wait for that before deciding anything

**Comment by yaira2** [comment]
Merging with #8129
