### ISSUE TITLE
Feature: Option to hide the address toolbar

### ISSUE THREAD

**Issue by cinqmilleans** [files-community/Files#10417]
### What feature or improvement do you think would benefit Files?

It would be practical and beautiful to be able to hide the toolbar. Basic users do not use the toolbar or not often. It is an idea to discuss if it is relevant and how to set it up. This can also be done with an Fn key to swap.

### Requirements

- Decide how to hide it.

### Files Version

Version: 2.3.57.0 OS Version: 10.0.22621.675

### Windows Version

Windows 11 22621.674

### Comments

![Small](https://user-images.githubusercontent.com/46631671/200185667-f7bb9601-b72f-4519-82a1-44642c2ee0c7.png)

**Comment by yaichenbaum** [comment]
> Basic users do not use the toolbar or not often.

Is this accurate? We ran a poll a couple of months ag and 80% of users are using the toolbar.

**Comment by cinqmilleans** [comment]
I think rather that it is necessary simply to reselect by default the options chosen the previous time. No need to clutter up the settings with this.

**Comment by cinqmilleans** [comment]
It is likely that Files users are mostly advanced users, since they have made the effort to look for an alternative.

**Comment by yaichenbaum** [comment]
> It is likely that Files users are mostly advanced users

That's a fair assumption but we're targeting a wide range of users here and don't want to move too much in either direction. The preferred way to change the layout, create a new item and take just about any other action is through the toolbar.

**Comment by cinqmilleans** [comment]
It's the address bar that is hidden and the navigation buttons moved to the tabs.  The quick options buttons are missing on the screenshot but that's an issue with my mockup unrelated to functionality.

**Comment by yaichenbaum** [comment]
I think I misunderstood the request to hide the actions toolbar.

**Comment by yaichenbaum** [comment]
This brings up some questions,

1. How can users access settings?
2. How do you handle moving the navigation buttons between the address and title bar without making the code complex?
3. What happens with smaller window sizes, it seems like there is less room for tabs.
4. How do users access search?
5. How do you workaround that tabs no longer connect with the content?

**Comment by cinqmilleans** [comment]
1) They no longer access it. Parameters are not used on a daily basis. The user knows that he is using a reduced mode and that he can exit it to display the address bar.
2) It is a simple boolean which modifies 2 visibilities.
3) It will take up less width than the address bar.
4) As for the first point.
5) I don't understand your question. Tabs work exactly the same.

**Comment by yaichenbaum** [comment]
> They no longer access it. Parameters are not used on a daily basis. The user knows that he is using a reduced mode and that he can exit it to display the address bar.

How do they show the toolbar again without a setting? Shortcuts are good but there is usually an additional toggle or way to change the option.

> It is a simple boolean which modifies 2 visibilities.

The title bar and address bar are very different controls, there will have to be duplicate code that adds extra complexity to the codebase.

> It will take up less width than the address bar.

The issue is that the navigation buttons are now combined with the title bar and there is less room.

> As for the first point.

Search is used by the majority of users, hiding the option doesn't seem like an option.

> I don't understand your question. Tabs work exactly the same.

They work they same but the UI doesn't look very good as it no longer flows into the rest of the apps UI.

![image](https://user-images.githubusercontent.com/39923744/200195837-36538a0c-0298-47c4-8bd9-cbbbb271706d.png)
![image](https://user-images.githubusercontent.com/39923744/200195844-016b7cfa-12ea-489b-8d4a-2d64515fd205.png)
