### ISSUE TITLE
Bug: Progress percent always showing 0% while copying files to the my pc's storage

### ISSUE THREAD

**Issue by IBR-41379** [files-community/Files#10755]
### Description

While I copy files from my PC to external storage, progress percent is showing but when I do the vice versa, Progress percent always shows 0% even though the file is being succesfully copied.

### Steps To Reproduce

1. Copy a file from External storage
2. Paste it on your computer's storage(Local Disk C,D,E...)

### Steps to fix

-Fix the issue by updating the percentage bar

### Files Version

Version 2.4.2.0

### Windows Version

Windows 11 Home 22H2

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/84517374/208301605-0fe38653-a702-4a6b-97b2-06e25c46265b.png)
This is the issue

**Comment by yaira2** [comment]
I can reproduce this, it seems that progress only changes when deleting items.

**Comment by carlosvsilva** [comment]
I would hope that a GUI element like a progress bar would show up visible, when copying files, otherwise I see no visible signs of copying taking place, and sometimes I retry paste multiple times large stuff which is annoying for duplicates and bottlenecking disk access.

**Comment by ferrariofilippo** [comment]
@yair100 I just found out that progress still doesn't work when creating an archive (always 0%). This doesn't depend on us, it's a bug of seven zip library. The event that notifies progress is never invoked

**Comment by yaira2** [comment]
We have a fork of the library (https://github.com/files-community/SevenZipSharp), is it a simple fix to notify the event?

**Comment by ferrariofilippo** [comment]
We should report progress in two different ways:
- if the user is compressing one item only, be it a folder or a file, we should subscribe to `SevenZip` event (which I'll have to fix);
- if the user is compressing multiple items, we should report progress as the number of items processed (as we do for archives extraction). An alternative is to report a "weighted" percentage: let's say we are compressing 10 items, we might report the progress as [(SingleItemCompressionPercentage / NumberOfItems) + OldProgressPercentage]

We can't use only the first method since the event reports the compression status of a single item
