### ISSUE TITLE
Scroll bar does not respond to clicks

### ISSUE THREAD

**Issue by marius-sucan** [files-community/Files#10995]
### Description

Scroll bar does not respond to clicks.

### Steps To Reproduce

1. Open Files app.
2. Go to any folder with many items.
3. Make sure the list is in Details mode
4. Make sure the columns are wider than the available width.
5. Scrollbars are not clickable.

### Steps to fix

Make it respond to mouse clicks on scrollbar.

### Files Version

Version : 2.4.21.0

### Windows Version

OS Version: 10.0.19045.2486

### Relevant Assets/Logs

None.

**Comment by yaira2** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
