### ISSUE TITLE
Reorder columns in Layout > Details view

### ISSUE THREAD

**Issue by Krojack** [files-community/Files#11494]
### What feature or improvement do you think would benefit Files?

Drag and drop the columns in the detail layout view to change their order. I would like to drag the "Size" column to the left so it's first, as in before the "Name" column.

### Requirements

- Drag and drop column headers in the Details view.

### Files Version

2.4.40.0

### Windows Version

Win 11 Pro 10.0.22621.1105

**Comment by yaira2** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
