### ISSUE TITLE
Code Quality: Replace `IAction` with `XamlUICommand`

### ISSUE THREAD

**Issue by lukeblevins** [files-community/Files#11877]
### Description

`IAction` needs to be replaced altogether with [XamlUICommand](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.xamluicommand?view=winrt-22621). It is entirely incompatible with what already exists in WinUI.

### Concerned code

src/Files.App/Actions/IAction.cs

### Gains

`XamlUICommand` lets us specify UI through the control binding, such as an icon, label, description, and keyboard shortcuts (both an access key and a keyboard accelerator), without setting the individual properties repeatedly.

### Requirements

- Remove `IAction`
- Redefine actions as the standard UI commands provided by WinUI
- Prevent flawed or redundant concepts like `IAction` from entering the codebase again

**Comment by yaira2** [comment]
@cinqmilleans

**Comment by cinqmilleans** [comment]
At first glance, this seems like a good idea. XamlUICommand automatically populates label, description, hotkeys, accesskey and icon. But,
* The icon is an IconSource and not a control, therefore incompatible with our OpacityIcon. It will be necessary to redo all the icons in this format, if possible. With this command, it is no longer possible to define the icon of the control otherwise. This is no longer taken into consideration.
* Hotkeys use KeyboardAccelerator. OEM keys (as for OpenTerminal) are not taken into consideration. These keys are different according to the keyboards. The custom hotkeys will not be able to use the OEM keys which are however practical.
* We cannot control the display of hotkeys in the menus, so no localization or adjustment for keys called XButton1 or Number8.
* Other changes (label, isOn, ...) are not notified. You will have to go through an abstract class that inherits from XamlUICommand.

Replacing only IAction with XamlUICommand but keeping IRichCommand wouldn't make sense. Action properties are only used to define richcommands. No need to have any mandatory dependencyproperty and parent class, just a few properties from an interface tailored to our needs.

If I understand correctly, your objective is to remove the IRichCommand/IAction duality by a single class.
* It will be necessary to create an abstract class that inherits from XamlUICommand, provides many other properties and is observable.
* XamlUICommand may be standard, but not suitable. You have to create a sub-command that is used during invocations and the properties can be modified by the callers.
* Useless parameters are kept for commands.
* The management of hotkeys for commands without control (menu/button) will be more complex.

Could you explain the advantages of using this standard class? How will this simplify the code for us?

**Comment by lukeblevins** [comment]
@cinqmilleans @yair100 

Those are reasonable points. I'm going to close this for now while I draft a more precise way to standardize the command system.
