### ISSUE TITLE
鼠标移动和右键选择太少

### ISSUE THREAD

**Issue by bfqbpq567** [files-community/Files#11904]
### What feature or improvement do you think would benefit Files?

1，鼠标滚动不能上下移动，这有点难受，只能用触摸板才行o((>ω< ))o
2，右键选择太少了，和原来资源管理器一样多的选择就好了，比如少了固定到开始菜单。
3，这软件真是美观和强大ヾ(•ω•`)o

### Requirements

1，鼠标滚动不能上下移动，这有点难受，只能用触摸板才行o((>ω< ))o
2，右键选择太少了，和原来资源管理器一样多的选择就好了，比如少了固定到开始菜单。
3，这软件真是美观和强大ヾ(•ω•`)o

### Files Version

2.4.59.0

### Windows Version

10.0.19044.2788

**Comment by Josh65-2201** [comment]
Thanks for the feedback but this doesn't make sense. The context menu shows all option the file explorer would and doesn't relate to the start menu.

As for scrolling issues
- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`
- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`
- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it can not be fixed in Files but the above option should get it working.
