### ISSUE TITLE
internet shortcut (.url) not showed on Files app

### ISSUE THREAD

**Issue by Wurushu** [files-community/Files#11973]
### Description

I have files with extension .url from OneNote notebooks. I can see and open them on Windows Explorer, but not on Files app. I have tried creating .url files in different locations. Results are the same.

The left one is Windows Explorer. The right one is Files app
![image](https://user-images.githubusercontent.com/19490316/229867175-2ef722cb-6d6b-4740-bb5c-66ef78c44f46.png)

Display Settings:
![image](https://user-images.githubusercontent.com/19490316/229873680-97be776d-ab3c-4eda-a71f-c869dd662f69.png)

### Steps To Reproduce

1. Open Files app. Go any location.
2. Click "New" to create a file
3. Select "File"
4. Type a normal file name end with .url
5. Nothing appeared, but you can see the file you created on Windows Explorer

Or

Open Files app and go to any location that has .url files inside. 

### Requirements

Cannot fix the issue.

### Files Version

2.4.60.0

### Windows Version

10.0.22621.1413

### Log file

[debug.log](https://github.com/files-community/Files/files/11151324/debug.log)

**Comment by hecksmosis** [comment]
I can reproduce this in preview and stable

**Comment by gave92** [comment]
For me it only happens if the url file is invalid. Url files of 0KB like shown in the screenshot are for sure invalid.
If I do (from Files): "New"  > "File" > Type a normal file name end with .url -> file does not appear
If I do (from Files): "New"  > "Shortcut" > Type a valid url ->file _does_ appear
Url files created from explorer appear ok in Files.
Still we should not filter out shortcuts even if they are invalid.

**Comment by yaira2** [comment]
If I recall correctly, we filtered them out because there were some issues. Are these no longer a problem?

**Comment by gave92** [comment]
No issue that I could find. Do you recall what issues there were?

**Comment by yaira2** [comment]
I can't find the issue but I might be mixing it up with something else, it's been a while...
