### ISSUE TITLE
The more it goes on, the less it goes

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12064]
### What feature or improvement do you think would benefit Files?

Besides unpacking the executable package in the latest version, I had to revert to Version 2.3.12.0 yet again.
v2.4.60 always crashed when first started, and every time it was closed to reopen there were very long times.

The solution now to have files with installation package is to buy it on the Store? it's fine for me to pay for it, in fact I'm happy, but first replenish the acrylic backgrounds.

### Requirements

.. there is also no option to make custom dark mode theme for automatic dark mode switching

### Files Version

Versione 2.4.21.0

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

so sad...

**Comment by Josh65-2201** [comment]
What's your issue? 2.4.21.0 is not supported anymore, If it crashing in 2.4.60 try 2.4.62 by clicking preview at https://files.community/download. Then make a bug report following the template.

**Comment by Josh65-2201** [comment]
You also don't have to buy it on the store you can use the classic installer from the above link too.

**Comment by yaira2** [comment]
> v2.4.60 always crashed when first started, and every time it was closed to reopen there were very long times.

This sounds like a bug, v2.4.61 is now available which may have fixed this issue but if it's still crashing, can you open a new bug report so that we can look into it?

> it's fine for me to pay for it, in fact I'm happy, but first replenish the acrylic backgrounds.

Removing acrylic was a tradeoff we had to make when we transitioned to WinAppSdk but if you have Windows 11, there is a similar and more efficient background effect called "mica".

> there is also no option to make custom dark mode theme for automatic dark mode switching

Like most apps on Windows, Files doesn't have and auto switching for themes but there are a number of free apps (such as Auto Dark Mode) that can do this for you.

**Comment by yaira2** [comment]
We're excited to share to acrylic will be returning in v2.5.
