### ISSUE TITLE
Desired Improvements for File Explorer: Faster Launch and Enhanced Favorite Icons

### ISSUE THREAD

**Issue by Lukiluc29** [files-community/Files#12101]
### What feature or improvement do you think would benefit Files?

Hello, I would like to know if it would be possible in a future update to improve the file explorer so that it launches like the default Windows file explorer, which means it would open faster and not crash at certain times or even all the time when using a shortcut to open it. Additionally, would it also be possible to use the same icons as in the default Windows file explorer in the "Favorites" space? This would mean having the logo displayed instead of a file with a logo on it, and if possible, enlarging the icons as well.

### Requirements

- Reduce the time it takes for the file explorer to open.
- Prevent file explorer crashes, especially when opening it with a shortcut.
- Use the same icons as in the default Windows file explorer in the "Favorites" space.
- Display the logo instead of a file with a logo on it.
- If possible, enlarge the icons.

### Files Version

Version : 2.4.62.0

### Windows Version

Windows 11 22H2 22621.1555

**Comment by Josh65-2201** [comment]
Thanks for the feedback. In future please open a separate request for each issue you have for better tracking.

> Reduce the time it takes for the file explorer to open.

Speed improvements are being worked on. Mostly blocked by Microsoft right now.


> Prevent file explorer crashes, especially when opening it with a shortcut.

If you have a crash then please open a bug report. Otherwise a fix cannot be worked on.


> Use the same icons as in the default Windows file explorer in the "Favorites" space.

What icon are you seeing? Explorer doesn't have an icon for favorites.


> Display the logo instead of a file with a logo on it.

What do you mean by this? The favorites section is there to match the sidebar and to be an obvious place they will show.

**Comment by Lukiluc29** [comment]
![Capture d'écran 2023-04-17 144232](https://user-images.githubusercontent.com/128183422/232487383-9f7f6b6e-8249-4ffd-ac6f-2cf6712e6035.png)
Je parle de ces logos et que si possible ceux actuellement sois agrandi
