### ISSUE TITLE
I can't scroll, is it supposed to be like this or did I change a setting that I don't know off.

### ISSUE THREAD

**Issue by OscarHdz13** [files-community/Files#12125]
### What feature or improvement do you think would benefit Files?

Is it possible to scroll through folder files?

### Requirements

- This proposal will increase comfort

### Files Version

2.4.62.0

### Windows Version

10.0.22621.1555

**Comment by Josh65-2201** [comment]
Thanks for the report can you check the below.

- Is it still and issue in 2.4.66.0?

- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it cannot be fixed in Files but the above option should get it working.

**Comment by yaira2** [comment]
@OscarHdz13

**Comment by NightsLight-hub** [comment]
@Josh65-2201 `creating a separate profile for Files.exe > Options > enable Disable Scroll Window Under Cursor`

Really useful
