### ISSUE TITLE
Feature: Purging logs after a given size

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#12182]
### What feature or improvement do you think would benefit Files?

While filling what we may expect of it, the logs saving management we have in Files is currently very limited. All the logs are save within the same file which is never cleared. It can be detrimental to debug when the logs are very populated.

For example, here is an extract of my log file, where four sessions are logged:

```
2023-04-15 11:47:54.9380|Information|Running on ARM: False
2023-04-23 21:44:33.6420|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-04-23 23:46:49.9762|Information|App launched. Launch args type: LaunchActivatedEventArgs
2023-04-24 10:05:09.8545|Information|App launched. Launch args type: LaunchActivatedEventArgs
```

We should implement a system that cleanse the log files once in a while.

### Requirements

- When reaching a given size or number of lines in the log file, it should be cleared.

### Files Version

Version 2.4.68 Dev

### Windows Version

W11 21H2 22000.1098

**Comment by QuaintMako** [comment]
I am not sure about the path of the log for the most recent log. Should it be
1- Still in the `LocalState/`, and then moved to `LocalState/Logs/` when a new session is done.
2- Directly created inside the `LocalState/Logs/` folder.

**Comment by yaira2** [comment]
> Separate logs from different session in different files, with the name debug_DATE.txt

I don't think we want to do this, it can make it harder to collect the right logs from users.

**Comment by QuaintMako** [comment]
> I don't think we want to do this, it can make it harder to collect the right logs from users.

Would you have any idea to differenciate different logs? 
Is the idea of separating them actually a good one?

**Comment by yaira2** [comment]
In our use case, I'd say it's better to have a single file but to clear it out once it surpasses a certain size.

**Comment by QuaintMako** [comment]
I modified the issue to reflect the discussion.

**Comment by yaira2** [comment]
What size do you think is a good threshold?

**Comment by heftymouse** [comment]
I think there should be one log file per app launch up to some threshold (say, the last 16 sessions). The latest one can be called something like `latest.log` for ease of use. Having it all in a single file and clearing the entire thing beyond a threshold is problematic because it's possible that error info from the last launch gets cleared on the next, and maintaining a rolling log of the last n sessions is hard because it would involve parsing the file itself.

**Comment by yaira2** [comment]
I don't want to limit the sessions in case there is a crash in the log file and we lose it because the user opens the app a couple of times since then.

**Comment by heftymouse** [comment]
How about doing it based on how old they are, for example the last couple weeks' worth of logs?

**Comment by yaira2** [comment]
I think size is the best threshold as the main issue is to prevent the file from getting too big, 1mb (maybe even lower) could be a good threshold.

**Comment by heftymouse** [comment]
Size also makes it effectively random whether something will still be there or not after some time.

**Comment by ferrariofilippo** [comment]
I think we should check the size only at startup, otherwise it may happen that the file is cleared in the middle of the session and we might lose important info.
For the same reason, I think we shouldn't have a hard limit, but rather a range (like 10MB ± 0.1%). We should do so because it may happen that a session starts under the bound, but it exceeds it before it ends. In this case, all logs will be deleted at the next startup, errors included

**Comment by ferrariofilippo** [comment]
Is there any chance that this will be moved to `Ready To Build`?
My logs grow fast (at least 1000 lines per week) and it is annoying to have to clear them manually or waste time to find some specific exceptions.

**Comment by yaira2** [comment]
> I think we should check the size only at startup, otherwise it may happen that the file is cleared in the middle of the session and we might lose important info.

We can solve this by keeping the most recent 100 lines and only clearing out the older ones.
