### ISSUE TITLE
Important integration

### ISSUE THREAD

**Issue by redhotideas** [files-community/Files#12387]
### What feature or improvement do you think would benefit Files?

I am forced to work with version Version 2.3.12.0. it's full of bugs it crashes all the time and makes me unable to work.
Can you re-integrate the Acrylic option for the background?
I would like to keep up with the times with your updates, but the "mica" version is unusable for me.

### Requirements

- go to setting
- Acrylic mode ON/OFF

### Files Version

Versione 2.4.71

### Windows Version

Windows 11 Pro Versione 22H2

### Comments

I ask you for a personal courtesy, I'm really in trouble. Files is worth 100 Explorer to me.

**Comment by Josh65-2201** [comment]
Thanks for the feedback. Acrylic is not planed on coming back as it still has the same issues as before.
1. Bad performance
2. It not working/looking the same in WinAppSDK compared to UWP

**Comment by redhotideas** [comment]
Can you send me an installable package of at least the latest version 4.7 with Acrylico? I would just use it.
I tried to work on the source files but it's not my job and even with so much effort I was not able.

**Comment by redhotideas** [comment]
Can I make a donation to get the Acrylic program?

**Comment by Josh65-2201** [comment]
See https://github.com/files-community/Files/issues/10690#issuecomment-1387266512. 
Because of the issues with WinUI and/or WinAppSDK (These are made by Microsoft and not Files) not supporting it well or even having the same look as acrylic from 2.3.12, means spending time implementing it wouldn't be worth it and is ultimately a small part of Files looks.

If it gets better supported or a way of doing it without issues then it might be reconsidered.
