### ISSUE TITLE
Bug: "Format..." shouldn't be visible if items are selected

### ISSUE THREAD

**Issue by imhe6** [files-community/Files#12401]
### What feature or improvement do you think would benefit Files?

As title. The top option is "Format" instead of "Open" / "Open with". This could cause a mistaking operation.
P.S. This happens only in the root directory of a drive.
![image](https://github.com/files-community/Files/assets/95729258/7512bddf-8153-4642-9d91-023209b00aef)

### Requirements

- "Format..." should not display in item context menu at all (since it only relates to the drive itself, not items in it), or at least stay at the second or the third part of context menu.

### Files Version

2.4.82.0 (Preview)

### Windows Version

10.0.22621.1702

**Comment by yaira2** [comment]
Do you have any items selected? This looks like a bigger issue where right clicking an empty space is showing the menu options for the selected items.

**Comment by yaira2** [comment]
#12402

**Comment by tsurrdurr** [comment]
Good day!

I'm new here. I've done a bit of research on this one, and I think it is not connected to the other issue highlighted.
To replicate this one, you have to have more than 1 drive on your system, it only occurs on a non-system drive.
The cause is in this piece of code:
https://github.com/files-community/Files/blob/b1fa9ec45d641d2f99506ad63d627ac709c2ffdf/src/Files.App/Actions/FileSystem/FormatDriveAction.cs#L24
The property is calculated without taking into account if any files are currently selected. This command should only be executable, if the right click was performed on an empty space, and thus no files were selected (I assume).

@yaira2 May I have a permission to fix this one? In accordance with contribution guidelines of the repo, of course.

**Comment by yaira2** [comment]
@tsurrdurr by all means, please let us know if you have any questions.

**Comment by imhe6** [comment]
Sorry that I have not check GitHub for a while, but thanks for mentioning. (so it is really a bug...)
(p.s. sorry that i mistouched the close issue button)

**Comment by yaira2** [comment]
@imhe6 this issue is resolved in `main` and will be included in the next release.
