### ISSUE TITLE
Bug: Crash when trying to unpin from favorites

### ISSUE THREAD

**Issue by Berruti06** [files-community/Files#12551]
### Description

When I try to unpin one of the folders on the Favourite left side of the app it doesn't do anything, and when I try to unpin that same folder from the folder ubication the app crashes. When you reopen the app the folder stays pinned

### Steps To Reproduce

1. Open the app.
2. Go to the folder location you want to Unpin
3. Right click and click on the Unpin form Favourites option.

### Requirements

Unpin the mentioned Folder without the appCrash

### Files Version

2.4.71.0

### Windows Version

Windows 11 (22H2): 22621

### Log File

[debug.log](https://github.com/files-community/Files/files/11664785/debug.log)

**Comment by yaira2** [comment]
@Berruti06 thank you for the report, can you check if this is fixed in the preview build? https://files.community/download

**Comment by cardin** [comment]
I'm able to reproduce this in the latest build 2.5.10.0 on Windows Version 10.0.22621.1928.

Related to #12785

**Comment by yaira2** [comment]
Thank you for the update

**Comment by kaushikramabhotla** [comment]
Hello @yaira2 , I had setup the local env and can see that this issue is no more reproducible

1. After setting as favorite:
![image](https://github.com/files-community/Files/assets/44550184/2ed7edae-a01a-4242-9f66-35ddbfec9291)

2. After "Unpin as favourite" :
![image](https://github.com/files-community/Files/assets/44550184/f83af285-4423-4f0d-9ea6-f774b0c377ff)

**Comment by yaira2** [comment]
@Berruti06 thanks for comment, I can confirm that this was fixed in #13046.
