### ISSUE TITLE
Feature: Save tabs on Windows shutdown or app crash

### ISSUE THREAD

**Issue by HobbesKo** [files-community/Files#12624]
### What feature or improvement do you think would benefit Files?

See #12619 - Startup Setting Ignored if Files Not Closed Before PC Shutdown.

### Requirements

- Honour the startup state if Files is open when the PC is shutdown.

### Files Version

2.5.1.0

### Windows Version

Windows 11 (22H2): 22621

**Comment by clackwell** [comment]
Just a note on implementation: One must always assume that the computer can be turned off "hard", that the application crashes or that the whole computer crashes - at any point in time. This means that one must save (relevant and modified) state ASAP, immediately.

Also, the saving process may equally be interrupted by power outage, etc. So the writing should be done in a way that no data corruption can occur, for example into a "temporary" settings file, and then replace the current file with this new file in an atomic step, or in well known steps that can be recovered. (When interrupted in between individual file renames, one must be able to detect this and take the right measure to roll back or roll forward, pushing through with the update of the stored state.)

**Comment by MarathonMax** [comment]
I see a lot of mention of opened tabs. Can opened windows (i.e.: multiple instances of app) be saved as well?

**Comment by Dennis-AS** [comment]
I just lost my tabs again and this time I am not sure why. I had Files open with multiple tabs when I left my computer. When I returned it had closed and when I reopened it my tabs were gone.
Maybe it closed because the Microsoft Store automatically installed the latest update.

Files needs to somehow always remember tabs (and possibly windows as well) no matter how it gets closed. Currently it only seems to remember tabs if it is closed normally. If it is closed in any other way (app crash, Windows crash, automatic update, anything else, etc.) it does not remember them.

I also submitted a Feature Request # 14545 which is related and would at least make it not as bad if Files doesn't remember the tabs when started.

I have attached my current debug.log file in case it is helpful.
Like I stated earlier, I am not sure why Files was closed when I came back to my computer.

[debug.log](https://github.com/files-community/Files/files/14350502/debug.log)

**Comment by yaira2** [comment]
This issue will be resolved in the next release.

**Comment by yaira2** [comment]
> I see a lot of mention of opened tabs. Can opened windows (i.e.: multiple instances of app) be saved as well?

This isn't supported yet, can you open a feature request to track this feedback?

**Comment by yaira2** [comment]
> This issue will be resolved in the next release.

The fix doesn't seem to be so reliable so I'm reopening this issue.
