### ISSUE TITLE
Recycle Bin causes crashes from Desktop shortcut

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12679]
### Description

I have the files app set to be my default files app through the advanced settings. From the desktop when I try to open the recycle bin using the icon, it tries to open the files app but crashes after loading for about 2 seconds. It shows the default grey files app background then it shows the styling which I have (acrylic and blue background) then it closes itself. I have about 20GB of files in the recycle bin

### Steps To Reproduce

1. Have files in the trash
2. From the desktop click on the icon to open it in the files app
3. It crashes

### Requirements

It should open the recycle bin from the files app

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11820404/debug.log)

**Comment by Lukiluc29** [comment]
#12667 I encountered the same problem but when I put it in my favorites bar it does not crash

**Comment by Antonel-Art** [comment]
I experience the exact same issue, with the addition that if I open "This PC" from the quick access on the desktop, it also breaks, and I have to end the process from the task manager (recently, the same happens with any shortcut on the desktop)... Furthermore, when I'm inside the explorer and I middle-click on a shortcut in the desktop favorites, the same thing happens... I noticed that when I reinstall the program, the errors disappear until I modify the settings... I haven't been able to determine yet if there's a specific setting that triggers the rest of the errors, but these are just assumptions. I hope you can fix this because I don't want to go back to the ugly native file explorer of Windows 11.

**Comment by Lukiluc29** [comment]
> I experience the exact same issue, with the addition that if I open "This PC" from the quick access on the desktop, it also breaks, and I have to end the process from the task manager (recently, the same happens with any shortcut on the desktop)... Furthermore, when I'm inside the explorer and I middle-click on a shortcut in the desktop favorites, the same thing happens... I noticed that when I reinstall the program, the errors disappear until I modify the settings... I haven't been able to determine yet if there's a specific setting that triggers the rest of the errors, but these are just assumptions. I hope you can fix this because I don't want to go back to the ugly native file explorer of Windows 11.

Yes, I have also noticed the bug with the "This PC" shortcut causing Files to crash. In order to prevent the crash when launching the shortcut, I had to add "This PC" to my favorites as well while waiting for the developers to find a solution to these numerous bugs

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
@IlyaSulli Is this still an issue in the preview version? https://files.community/download?
