### ISSUE TITLE
Mouse scrolling not functioning

### ISSUE THREAD

**Issue by ppoythress** [files-community/Files#12695]
### Description

Hello! The scroll wheel does not function within Files. I have to grab the right hand slider. I have tried two different mice and double-checked my Windows 11 settings. 

### Steps To Reproduce

Launch Files
Window of my project files appears
Want to scroll down with mouse but, scroll wheel does nothing. 

### Requirements

- e.g. Fix crash that occurs when...
Allow mouse scroll wheel to scroll window contents

### Files Version

2.5.1.0

### Windows Version

10.0.22621.1848

### Log File

[debug.log](https://github.com/files-community/Files/files/11839293/debug.log)

**Comment by Josh65-2201** [comment]
- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it cannot be fixed in Files but the above option should get it working.

**Comment by ppoythress** [comment]
You are awesome - thank you. It was the "scroll inactive windows when hovering over them" solution. Thank you.
