### ISSUE TITLE
Sidebar icon size

### ISSUE THREAD

**Issue by iron2000** [files-community/Files#12707]
### What feature or improvement do you think would benefit Files?

Is it possible to change the sidebar icon size to that of the File Explorer?

![files](https://github.com/files-community/Files/assets/43039016/6678e60c-0395-42bd-b78b-c6adaec0b2ef)
_File Explorer (left) and Files (right)_

Use the 16x16 icon size by default instead of just resizing?

### Requirements

- Make the sidebar icons clearer instead of the current blurry resize

### Files Version

2.5.1.0

### Windows Version

Windows 11 Home	22H2 22621.1848

**Comment by yaira2** [comment]
Thank you for your feedback, we're currently tracking this request in #11370.

**Comment by yaira2** [comment]
@iron2000 my apologies, I reread this issue and I realized you were referring to the icon size we request from the API. This issue will be addressed in the upcoming release of v2.5.20.

**Comment by Lukiluc29** [comment]
@yaira2 Wouldn't it be better to also change the resolution of the other icons so that all File Explorer icons have the same resolution? For example, when a folder is pinned (with the new resolution), it has a different resolution than when we browse through files and encounter a folder. So, I propose that the resolution of the sidebar stay as it is and that the rest of the Files icons be the same resolution as the sidebar so that there is no resolution difference.
