### ISSUE TITLE
Feature: Include Git Repo name and current branch in Folder's Details pane

### ISSUE THREAD

**Issue by mdtauk** [files-community/Files#12779]
### What feature or improvement do you think would benefit Files?

Can we display basic git info on the Details page?  Repo name, and current branch?
Of course any more detailed Git info would need to be in its own tab/page.

I think if the Status Bar Buttons are being collapsed or truncated, the details pane may be a useful place to have the branch name visible
the full git tab, will be quite busy, and it seems like a top level enough "detail" to display.

This should probably also be displayed in the Properties Dialog also.

![image](https://github.com/files-community/Files/assets/7389110/4d8faf47-d7a2-4b46-ae95-fc03476c56f2)

![image](https://github.com/files-community/Files/assets/7389110/9331f0d5-0379-4e59-9333-0cdd5cb55edb)

### Requirements

- This proposal will ensure git repo folders are recognisable on the main details page.

### Files Version

2.5.10

### Windows Version

22621.1928

**Comment by QuaintMako** [comment]
@mdtauk what are you referring as the repository name? As far as I know, repositories do not have name, or rather it's a very fusy concept. (see [this stack overflow post](https://stackoverflow.com/questions/15715825/how-do-you-get-the-git-repositorys-name-in-some-git-repository))

Maybe you're thinking about the origin name used to identify the repository? (For example, `Files` for `https://github.com/files-community/Files`, or `Website` for `https://github.com/files-community/Website`)

**Comment by mdtauk** [comment]
> @mdtauk what are you referring as the repository name? As far as I know, repositories do not have name, or rather it's a very fusy concept. (see [this stack overflow post](https://stackoverflow.com/questions/15715825/how-do-you-get-the-git-repositorys-name-in-some-git-repository))
> 
> Maybe you're thinking about the origin name used to identify the repository? (For example, `Files` for `https://github.com/files-community/Files`, or `Website` for `https://github.com/files-community/Website`)

![image](https://github.com/files-community/Files/assets/7389110/d6e90112-2918-43a4-a5a9-da0dd0aafdff)
What is displayed here, I am not sure of the official API term for this string, but this text, and the current branch name

**Comment by QuaintMako** [comment]
Instead of the name, I'd suggest displaying the `remote origin`. Instead of `Files`, something like `github.com/QuaintMako/Files.git` - As a developper, I think it's gives more valuable information then solely the name.

About the branch, should we just display the name? Should we also display if the its synchronized to another branch on the remote origin _if there is an origin_?

**Comment by mdtauk** [comment]
> Instead of the name, I'd suggest displaying the `remote origin`. Instead of `Files`, something like `github.com/QuaintMako/Files.git` - As a developper, I think it's gives more valuable information then solely the name.
> 
> About the branch, should we just display the name? Should we also display if the its synchronized to another branch on the remote origin _if there is an origin_?

I think this information is a bit technical for the details pane, but is more suited to the upcoming Git specific pane.
#12440

**Comment by QuaintMako** [comment]
> I think this information is a bit technical for the details pane, but is more suited to the upcoming Git specific pane. #12440

I did not know of that pane, in that case, the name is enough!

**Comment by mdtauk** [comment]
> > I think this information is a bit technical for the details pane, but is more suited to the upcoming Git specific pane. #12440
> 
> I did not know of that pane, in that case, the name is enough!

Something we are working on the design for, please feel free to submit ideas and comment in that issue!

**Comment by Lukiluc29** [comment]
@QuaintMako @mdtauk Since the implementation of this new feature, I no longer have access to the overview of Git folders
![Capture d'écran 2023-07-05 175619](https://github.com/files-community/Files/assets/128183422/cae37cc7-d89f-4366-b232-363612e3eec4)
![Capture d'écran 2023-07-05 175645](https://github.com/files-community/Files/assets/128183422/4b9efc05-a30a-4763-8451-318497218f57)

**Comment by QuaintMako** [comment]
I will look into this regression as soon as I can.

**Comment by QuaintMako** [comment]
@Lukiluc29 I cannot seem to reproduce this regression. I tried switching my language to French to see if this might be linked to this, but it doesn't seem to be linked.

Does the issue happen everytime? Do you have a log for it?

Since we might have to discuss about the issue, I'd suggest you open an issue about it.

**Comment by Lukiluc29** [comment]
@QuaintMako It's ok, I just opened a report on this problem
