### ISSUE TITLE
Mouse Wheel is not working

### ISSUE THREAD

**Issue by mikex2023** [files-community/Files#12858]
### Description

Mouse Scrolling is not working!
The mouse itself works - click, right click, even a click with the wheel works perfectly, but scrolling is not possible.

### Steps To Reproduce

Just start the actual Version. Don't know if it was okay with last version

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.5.10.0

### Windows Version

10.0.19045.3086

### Log File

[debug.log](https://github.com/files-community/Files/files/11957399/debug.log)

**Comment by Josh65-2201** [comment]
- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it cannot be fixed in Files but the above option should get it working.

**Comment by mikex2023** [comment]
Dear Josh,
thank you for your suggestions.
I was able to solve the problem under the standard Windows settings for the mouse -> "scroll inactive windows when hovering over them" change to enable!

**Comment by wbokkers** [comment]
This setting again causes issues with Windows App SDK 1.6.1

**Comment by 0x5bfa** [comment]
Thank you for letting us know that. It won't be an issue for the time being because we currently don't use that and still use 1.5.6. I'll add a label in case.
