### ISSUE TITLE
Bug: Error notification when opening a new tab

### ISSUE THREAD

**Issue by mtmsla** [files-community/Files#12863]
### Description

Says it crashed, idk. Still working. Didn't have to reopen it.

### Steps To Reproduce

I opened three individual tabs, each pointing to different directories on OneDrive. Then I right-clicked and "send to" VS Code. (I had previously set up a "send-to" for VS Code.

It crashed after the second tab and as I was opening the third.

### Requirements

- e.g. Fix crash that occurs when...
see above "steps to reproduce"

### Files Version

2.5.10.0

### Windows Version

Windows 11 Home 22H2 22621.1928

### Log File

[debug.log](https://github.com/files-community/Files/files/11963654/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this, it seems to be an exception from the recent files widget.
```
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-07-05 20:46:23.1507|Warning|System.ComponentModel.Win32Exception (15): The system cannot find the drive specified.
   at Vanara.PInvoke.Shell32.ShellUtil.GetShellItemForPath(String path)
   at Vanara.Windows.Shell.ShellLink.get_Target()
```

**Comment by hishitetsu** [comment]
I believe the following is the log of the crash.
`2023-07-05 20:42:53.8369|Error|Microsoft.UI.Xaml.Markup.XamlParseException: XAML parsing failed.`

**Comment by GH0STDATA** [comment]
I'm also seeing a similar error when opening a specific folder with roughly 9,000 files in it. Here is the log file, its pretty generic and doesn't really show why the error occurred, only that an error did occur. I did some troubleshooting and it looks like its due to me trying to view the files in "Medium Icons" mode, meaning that thumbnails are being generated for all 9,000 files since they are all either images or videos. Once I switched the view mode to "Details" the error no longer happens.

[debug.log](https://github.com/files-community/Files/files/12063484/debug.log)

**Comment by yaira2** [comment]
@mtmsla Is this still an issue in the latest preview version? https://files.community/download?

**Comment by yaira2** [comment]
@mtmsla

**Comment by mtmsla** [comment]
Sorry, will check tomorrow and reply

**Comment by mtmsla** [comment]
Seems to be ok now @yaira2

**Comment by yaira2** [comment]
Thanks for checking
