### ISSUE TITLE
Code Quality: Introduce ViewModels for layout pages

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#12976]
### What feature or improvement do you think would benefit Files?

Current codebase of layout pages are kind of mess. we have to separate code from code-behind to follow MVVM pattern(according to the guideline preface `All code contributed to the repository must follow our Model-View-ViewModel design path`).

- Related #10305

### Requirements

- [x] Rename namespace `LayoutModes` with `ContentLayouts`
- [x] Rename page classes (according to the guideline, section 1, item 11)
  - Rename BaseLayout with BaseLayoutPage
  - Rename IBaseLayout with IBaseLayoutPage
  - Rename ColumnViewBase with ColumnsLayoutBasePage
  - Rename ColumnViewBrowser with ColumnsLayoutPage
  - Rename DetailsLayoutBrowser with DetailsLayoutPage
  - Rename GridViewBrowser with GridViewLayoutPage
- [ ] Move styles into separated ResourceDictionary file; ContentLayoutsStyles.xaml
- [ ] Use ICommand instead of using Event Handler.
- [ ] Introduce ViewModel classes.
  - Introduce BaseLayoutViewModel abstract class
  - Introduce IBaseLayoutViewModel interface
  - Introduce ColumnsLayoutBaseViewModel class
  - Introduce ColumnsLayoutViewModel class
  - Introduce DetailsLayoutViewModel class
  - Introduce GridViewLayoutViewModel class
  - Introduce GroupabeBaseLayoutViewModel abstract class
- [ ] Move page-unrelated methods into each ViewModel.
- [ ] Remove StandardLayoutMode class

### Files Version

2.5.10

### Windows Version

10.0.22000

**Comment by 0x5bfa** [comment]
@d2dyno1 do you agree upon this?

**Comment by 0x5bfa** [comment]
@d2dyno1 @QuaintMako do you agree upon this?

**Comment by d2dyno1** [comment]
1. Could you elaborate "Use ICommand instead of using Event Handler"? I think we should be careful where we do that since not all UI events should be handled in VMs
2. Is IBaseLayoutViewModel interface really necessary?
3. What classes would derive `GroupableBaseLayoutViewModel`? Perhaps using composition pattern would be better instead of nesting another abstractions?
4. Columns are a different story if you ask me. In an ideal world, all layouts (including Column View) would inherit from BaseLayout and use BaseLayoutViewModel. However, with that approach we'd have to eliminate all methods/properties from BaseLayout that depend on a list of `Items` *since Column View uses blades and there's no single layout*. I can only see two options to solve the aforementioned issue:
  - Create another level of abstractions that'd separate a Layout class with items and without.
  - Keep the BaseLayout as is (with the Items) and just update the collection to only reflect changes in the topmost blade

**Comment by 0x5bfa** [comment]
This should be done gradually. And to close this issue, we need to refactor so many classes including storage item classes and storage enumeration classes.
