### ISSUE TITLE
Feature: Create Shortcut when dragging from address bar

### ISSUE THREAD

**Issue by 333csx** [files-community/Files#13086]
### What feature or improvement do you think would benefit Files?

When dragging a location from the address bar, a shortcut should be created.

### Requirements

- Items in adress bar (folders) are dragable
- Shortcut to the location is created at the destination when dragged

### Files Version

2.5.21.0

### Windows Version

10.0.19045.3208

**Comment by Josh65-2201** [comment]
Thanks for the feedback and sorry for the delayed response. I've added this to the project board.
Few things I don't see working well as dragging selects the text since the address bar is text based. You can also already right click folders/files to make a shortcut.

> When dragging to the taskbar on the "Files" icon, the location is pinned to the jump list

I don't think this is even possible as Windows taskbar doesn't allow it

**Comment by yaira2** [comment]
> Few things I don't see working well as dragging selects the text since the address bar is text based. You can also already right click folders/files to make a shortcut.

I think this is referring to dragging an item in the breadcrumb bar.

**Comment by yaira2** [comment]
@333csx thank you for your feedback, we wanted to let you know that we currently don't have plans to implement this option.
