### ISSUE TITLE
Mouse scroll

### ISSUE THREAD

**Issue by klgr** [files-community/Files#13267]
### What feature or improvement do you think would benefit Files?

Mouse scroll wheel support is a pretty basic feature

### Requirements

Reaching constantly for the scroll bar or using the keyboard isn't really productive

### Files Version

2.5.21.0

### Windows Version

Win 10 Pro 10.0.19045

**Comment by Josh65-2201** [comment]
Thanks for the report, this is already supported

- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it cannot be fixed in Files but the above option should get it working.

**Comment by klgr** [comment]
Thanks Josh, it was the windows setting that fixed it. I wasn't even aware of this option
