### ISSUE TITLE
Tags Display

### ISSUE THREAD

**Issue by jvduval** [files-community/Files#13310]
### What feature or improvement do you think would benefit Files?

Would like to be able to control the "order" of the files and directories when displaying the Tags Widget on the Home page like we can when we display a "folder" after clicking on it.  Is this already there and I'm missing something or can we make this happen when displaying the Tags widget on the Home page.

Thanks,

Jason

![FolderView](https://github.com/files-community/Files/assets/37410804/37d4b62d-23da-4bb5-9b48-0d86d8f03147)
![HomePage_TagWidgetView](https://github.com/files-community/Files/assets/37410804/8cfe093a-f4b7-48ea-9da9-75e7f450e01d)

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2134

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for your feedback, the items in the Tags widget aren't designed to have features like sorting. To access these options, you can click the Tag title to view the list of tags in whichever layout you prefer.

**Comment by jvduval** [comment]
> Thank you for your feedback, the items in the Tags widget aren't designed to have features like sorting. To access these options, you can click the Tag title to view the list of tags in whichever layout you prefer.

While I realize this, the idea was that this would be a great feature enhancement to how tags work...I thought that was the whole point of submitting feature requests?!?!?!

**Comment by yaira2** [comment]
Hi @jvduval, feature requests are an important part of the process, and we regularly implement ideas based on user feedback. That said, not every request fits into our vision for Files and we try to let users know sooner than later instead of stringing them on. Things do change and it's possible that we'll reevaluate in the future, but we wanted to be transparent that this doesn't fit our current vision for the tags widget.

The tags widget is intended to be a very basic preview of the tags and to let users get into tagged folders or files. It's not designed to have the full functionality that's available when browsing a folder. This applies to the other widgets as well.
