### ISSUE TITLE
Bug: Rename duplicate "Artist" to "Contributing Artists" in properties window

### ISSUE THREAD

**Issue by leafpmpmp** [files-community/Files#13423]
### Description

<img width="882" alt="image" src="https://github.com/files-community/Files/assets/49824741/6ef85c08-5d2b-4feb-bad8-433f1ca2bb73">
The "Album Artist" can only show the last person in that section, and the first "Artist"(which doesn't exist in other apps) seems to be copying "Album Artist".

### Steps To Reproduce

Open the Properties of any audio file, switch to Details, and that should happen.

### Requirements

- Rename duplicate "Artist" to "Contributing Artists" in properties window (match File Explorer)

### Files Version

2.5.21.0

### Windows Version

10.0.22621.2283

### Log File

[debug.log](https://github.com/files-community/Files/files/12708229/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by yaira2** [comment]
It looks like File Explorer calls it "Contributing Artists".

**Comment by hemalshah28** [comment]
Hello,
I have looked into issue. Look like there are one more artist. So I have added detail properties in the file detail via explorer detail tab and comparing with `Files` app properties. I get duplicate `Artist`   Please see below image. I am new to open source world. Please guide me what is expected behavior.  I would like to work on it. Please let me know.

![image](https://github.com/files-community/Files/assets/33328907/1067aa1c-2e01-4658-9743-30ed6f70ce51)
