### ISSUE TITLE
Launch and overall speed during use seems slow

### ISSUE THREAD

**Issue by sstubblefield** [files-community/Files#13480]
### What feature or improvement do you think would benefit Files?

I just purchased Files from the Microsoft Store, and I've noticed that it seems awfully laggy and slow. I have a NVME SSD with 1950MB/s write and 2250MB/s read speeds. I'm running Windows 10 Business (22H2), I have an i7-10750H and 32GB of RAM. Obviously I know the app isn't written into Windows like Explorer is, but I wouldn't have expected it to be as slow as it is.

### Requirements

I would just expect some speed improvements mostly. I don't expect it to be AS fast and snappy as Explorer, but getting it closer would be much appreciated. I've also attached my settings file in case I might have missed a setting that's causing it to be slower than normal.
[user_settings.json.txt](https://github.com/files-community/Files/files/12831719/user_settings.json.txt)

### Files Version

2.5.21.0

### Windows Version

Windows 10 Business Version	22H2 | OS build 19045.3324 Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by yaira2** [comment]
Thank you for your feedback, we're excited to share that improvements to startup speed will be included in the next release.

**Comment by yaira2** [comment]
We don't have a release date yet, but the plan is to release v3 before the end of the year.

**Comment by sstubblefield** [comment]
@yaira2 thank you for the quick response. I did just download the preview which seems to be much faster. I'm looking forward to v3.

**Comment by yaira2** [comment]
Thank you! I want to add that we aren't done working on performance improvements, we'll continue working on this in the future.

**Comment by PatronNick** [comment]
> but the plan is to release v3 before the end of the year.

this would be the best gift for the new year)

**Comment by LM1LC3N7** [comment]
Hi,

I'd also like to share my experience.

### version 2: slow and bugs on OneDrive Enterprise folder
I tried v2 and was very enthusiastic because the application is very beautiful and has a column view that I had been waiting so long to find on Windows! **And an open-source software with a beautiful UI is not that common,** thanks for that 😄  
But after few weeks, I drop the v2 because it was very slow to start and crashed a lot on my OneDrive Enterprise folder (at work).

### version 3: still slow to start?
Yesterday I found the v3 and tried again, hoping for a faster startup. I haven't found the previous bugs on OneDrive, so great news. **But the startup is still very slow, up to 35 seconds** with an instance already open (mouse click to the taskbar icon to open a new instance) !
I have a work laptop with few security tools that could slow down startup, sure. But with a 1TB NVME (2Gb/sec write speed), an 8 core i7 CPU and 32Gb RAM, it's not acceptable to wait more than 5 seconds for a browse window. For me, this slow start-up kills the application's user-friendliness and use.

### Why and how to improve?
Newbie question: what could case this slow startup, as it is based on C# or C++, not electron for example, which is known to be slow to start?
Are they any advice to speedup the startup?
I already check the option "start Files when Windows starts" and "keep app running in background".

Sorry for saying I am not satisfied, but it is important to me to say what could (or must) be improved, not just "this is crap, that's all" 😅

**Comment by Josh65-2201** [comment]
Startup speed is depend on optimization in the code. Is the a reason you opening a new window rather then a tab?

**Comment by yaira2** [comment]
> But the startup is still very slow, up to 35 seconds with an instance already open (mouse click to the taskbar icon to open a new instance) !

This is indeed the case, the solution we're planning to implement (see #12689) will solve this by switching Files to a single instance app, but we can't provide a timeframe on this.

> Newbie question: what could case this slow startup, as it is based on C# or C++, not electron for example, which is known to be slow to start?

WinUI apps in general take a little longer to load due to the nature of the technologies being used. We're expecting it to get a lot better once they add Native AOT support, but it's hard to know when Microsoft will add this.

**Comment by LM1LC3N7** [comment]
That's good to know, thanks @yaira2!

Regarding your comment @Josh65-2201, the idea was to try with File already opened as sometimes it is faster to open a new window. The point was to show this is slow, even if the app is already started.
For example, I use 2 to 3 virtual desks on Windows 11, and I need accessing files from theses desks without being redirected to the desk where my app is already opened. This will be the case if you switch to "single instance app".
Another example: Firefox (or Chrome). The first startup is a little longer than opening a new window.

It is very weird that Microsoft created a new software type (WinUI) that takes longer to load. It should be the opposite no?

**Comment by yaira2** [comment]
> For example, I use 2 to 3 virtual desks on Windows 11, and I need accessing files from theses desks without being redirected to the desk where my app is already opened. This will be the case if you switch to "single instance app".

That's something we'll have to test with single instance, there are posible workarounds should there be an issue.

**Comment by LM1LC3N7** [comment]
Little follow up: this morning the File app started fast enough to be usable like the default file explorer. Thanks for keeping the effort on trying to make is faster, I really love the app and possibilities 😍
