### ISSUE TITLE
Mouse Scroll Ball does not Work Windows 10 Pro

### ISSUE THREAD

**Issue by LamprosPapou** [files-community/Files#13539]
### Description

Mouse Scroll Ball does not Work Windows 10 Pro for moving up-down to lists of files/folders.
Click in side scroll bar works

### Steps To Reproduce

each time i try it

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

2.521.0

### Windows Version

Windows Pro 22H2

**Comment by Josh65-2201** [comment]
Thanks for the report in future upload the debug.log file and DON'T copy and paste the contents.
- If you have software called XMouse control? if so you can try creating a separate profile for Files.exe > Options > enable `Disable Scroll Window Under Cursor`

- You can also try going to Windows Settings > Bluetooth & devices > Mouse > Enable `Scroll inactive windows when hovering over them`

- It may also be caused by https://github.com/microsoft/WindowsAppSDK/issues/2791 in this case it cannot be fixed in Files but the above option should get it working.
