### ISSUE TITLE
Color drives when getting Full like Windows Explorer

### ISSUE THREAD

**Issue by MichaelAdamScott** [files-community/Files#13553]
### What feature or improvement do you think would benefit Files?

It would be really useful to have the blue bars showing drive space be colored differently for drives that are getting full like the original windows explorer. Having them be red makes it easier to see quickly. If it is also possible to use your own custom color that would be even more awesome but the default red is also fine. Just something to make the full drives stand out. I have many drives as an editor and it is super useful. 

![Screenshot 2023-10-21 223121](https://github.com/files-community/Files/assets/50979496/e756ff9f-1946-4605-8896-876744cabd53)

vs 

![Screenshot 2023-10-21 223226](https://github.com/files-community/Files/assets/50979496/551b08e3-b207-4bd3-aa3f-647276576b91)

### Requirements

- This proposal will make it easier for users to quickly see at a glance what drives are getting full easily instead of just blue bars on all drives.

### Files Version

2.5.21.0

### Windows Version

Win 11 Pro 22621.2428

**Comment by Lukiluc29** [comment]
I find this added feature very useful because I also sometimes have certain disks full, and it will allow me to identify them more quickly.

**Comment by hecksmosis** [comment]
This would make the bar inconsistent with the color theme

**Comment by yaira2** [comment]
Thank you for your feedback. The choice not to change the drive color is by design, this allows us to follow the system accent color and to keep things consistent throughout the app. However, you might have noticed the information icon that's displayed next to certain drives. This helps indicate when drives are getting full and provides a shortcut to the storage settings in Windows.
