### ISSUE TITLE
Files - is a good name?

### ISSUE THREAD

**Issue by konashevich** [files-community/Files#13619]
### What feature or improvement do you think would benefit Files?

Dear Community,
You are doing a great job! No doubts, the project can have a bright future.
However, its name is a weak point. It's not unique enough for successful Googling, and it lacks a memorable quality for its users. According to naming standards, it's the worst name you could ever choose for your project.

Files must have a bright future—so it should have a distinguishing and memorable name!

Best regards!

### Requirements

- rename and rebrand Files

### Files Version

all

### Windows Version

all

**Comment by yaira2** [comment]
It depends on how you look at it, there are obviously more unique names that we could have gone with but at this point any changes would be confusing. And at the end of the day, you were able to find the repo to post this question...

**Comment by yaira2** [comment]
We're not against changing the name if someone comes up with a good idea, but it's not something we plan to do in the immediate future. Our main focus is on the upcoming release of v3 and to continue improving the app.

**Comment by Cambridgeport90** [comment]
I have to agree with this, completely…though…what name to give it? That is the million dollar question.

From: Oleksii Konashevych ***@***.***>
Sent: Monday, October 30, 2023 18:35
To: files-community/Files ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [files-community/Files] Files - is a good name? (Issue #13619)

What feature or improvement do you think would benefit Files?

Dear Community,
You are doing a great job! No doubts, the project can have a bright future.
However, its name is a weak point. It's not unique enough for successful Googling, and it lacks a memorable quality for its users. According to naming standards, it's the worst name you could ever choose for your project.

Files must have a bright future—so it should have a distinguishing and memorable name!

Best regards!

Requirements

  *   rename and rebrand Files

Files Version

all

Windows Version

all

Comments

No response

**Comment by yaira2** [comment]
"Files" is pretty descriptive and it's very good for discoverability. The downside is that there are multiple other apps with similar names, and it can make it a little hard to find documentation. We do our best to mitigate this with own documentation site https://files.community/docs.

**Comment by jefflord** [comment]
Bite the bullet and change the name. 

You will lose a lot of potential users because the product cannot be found by name. If "we're" fine keeping it to ourselves, keep the name.

Of course, what to call it... 

I think sticking with something with "Files" in the name might be the least confusing even if limits name options. 

- "With its _sleek_ and _intuitive_ design..." --> "SI Files"
- "Introducing Files, the _ultimate_ file manager app for Windows" --> "Ultimate Files"
- "Whether you're a _power_ user..." --> "Power Files"
- "With its combination of _powerful_ features and _ease_ of use..." (user-friendly)  --> 
  - "Friendly Files"
  - "Effortless Files"

Also, though it claims to be a "file manager app", clearly a name with "file manager" would also make sense. 
 
Remember, "Google" started as "BackRub". A name change might be one of the best things that could happen to this product.
