### ISSUE TITLE
Takes too long to open Files

### ISSUE THREAD

**Issue by Quietbeat** [files-community/Files#13726]
### Description

When I open File Explorer using Win+E, Explorer opens immediately but with Files, it takes at least 5+ seconds.

### Steps To Reproduce

1. Press Win+E to open Files

### Requirements

Files needs to open immediately.

### Files Version

3.0.0.0

### Windows Version

10.0.22621.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13290383/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, was there already an open instance of Files when you used the shortcut?

**Comment by gave92** [comment]
Should be the same as #13710

**Comment by yaira2** [comment]
The underlying issue is the same, opening Files when an existing instance is open takes a long time.

**Comment by TheBestPessimist** [comment]
I think my use-case is similar: 

- Files replaces Explorer
- close all Files instances, but leave files open in the background
- press <kbd>Win</kbd>+<kbd>E</kbd>: Files opens instantly (as it runs in the background) ✅ 
- press <kbd>Win</kbd>+<kbd>E</kbd> again: Files seems to open as if a new instance of Files is cold started, not using the background process ❌ 
- press <kbd>Win</kbd>+<kbd>E</kbd> again: Files seems to open as if a new instance of Files is cold started, not using the background process ❌ 
- press <kbd>Win</kbd>+<kbd>E</kbd> again: Files seems to open as if a new instance of Files is cold started, not using the background process ❌ 

I guess you can see where i am going with this. Every time i open a new Files window, it "cold starts" instead of using the background version and simply opening a new window

**Comment by Josh65-2201** [comment]
Right now the background process will only work on one window. When #12689 is implemented it can be used on multiple windows

**Comment by alfio95it** [comment]
I specify that my case happens both in background and not
