### ISSUE TITLE
Bug: Highlight and selection gets cancel if upper arrow key pressed afterwards

### ISSUE THREAD

**Issue by sfksuperman** [files-community/Files#13798]
### Description

Selection of the part of the file name gets canceled after reaching the start position and again keep pressing (once or more than once) the up arrow key.

This screenshot shows that I selected (shift+left arrow) the full file name from the last and reached the starting letter.
After this, if I press even for once the left arrow key, the whole selection cancels out and the arrow returns to the starting letter only.

<img width="160" alt="2" src="https://github.com/files-community/Files/assets/34414624/87a63734-8197-4eeb-ab39-f0866480de1b">

### Steps To Reproduce

1. Select the file to rename.
2. Choose "rename' to either add or delete the texts as per your choice.
3. Keep the cursor anywhere except for the starting first letter.
4. Use shift+left arrow key to start the selection and select all the letters till you cover the starting letter as well.
5. Now press the shift+left key once more and the whole selection will cancel out. And your cursor will be at the beginning.

### Requirements

It should not cancel out the selection even after reaching and covering till first starting letter.

### Files Version

3.0.3.0

### Windows Version

10.0.22631.2506

### Log File

[debug.log](https://github.com/files-community/Files/files/13320658/debug.log)

**Comment by yaira2** [comment]
Thank you for the report

**Comment by MrFrawsty** [comment]
I am having trouble reproducing this. Am I understanding correctly that this is happening when the arrow is pressed while holding shift?

**Comment by yaira2** [comment]
After using `shift + left arrow` to select all the text, pressing `shift + left arrow` another time clears the selection.

**Comment by sfksuperman** [comment]
> After using `shift + left arrow` to select all the text, pressing `shift + left arrow` another time clears the selection.

Little correction. Shift+Up arrow.

**Comment by RieBi** [comment]
> > After using `shift + left arrow` to select all the text, pressing `shift + left arrow` another time clears the selection.
> 
> Little correction. Shift+Up arrow.

So In the issue name you say about up arrow key, in steps to reproduce you say about shift + left arrow key, and now you say about shift+ up arrow key.

Just want to clarify. If you actually meant the shift + up arrow key, I would like to give some additional information.

It turns out that if you place your cursor anywhere but start of name and select up to the start either with shift+left arrow, or by pressing shift+up arrow, pressing the shift+up arrow again does nothing, but pressing it once more clears the selection.

Basically, If you place cursor anywhere but start and press shift+up arrow, it selects up to start of name. Pressing shift+up arrow again does nothing. Pressing shift+up arrow once more (3rd time, or 2nd time if the selection already was from the start), the selection gets canceled.

I also noticed that pressing shift+down arrow has similar effects but with some changes. If you have your cursor anywhere but end of name, it selects till the end. Pressing shift+down arrow again clears the selection. It is interesting that there's no room for another press that does nothing, as opposed to pressing shift+arrow key several times.

I think the behavior with shift+arrow down key also shouldn't clear the selection, so I think those are related and maybe should be fixed together.

**Comment by RieBi** [comment]
I think I found the fix to the bug. Just need a few more checkups to make sure it actually works

**Comment by RieBi** [comment]
Well the fix is working for the main issue but there are some other semi-issuee, semi-bugs related to it that might also be fixed. I'll try fixing it all.

**Comment by sfksuperman** [comment]
Working fine now. Thanks and closing this.
