### ISSUE TITLE
Bug: Foreign language in Office file types

### ISSUE THREAD

**Issue by the-frost** [files-community/Files#14096]
### Description

I have the Japanese IME installed on my PC, but its main interface is English. However, Files shows Microsoft Office file types in Japanese for some reason. File Explorer doesn't. Like so:
![image](https://github.com/files-community/Files/assets/152221499/b5662cee-4f43-4164-9844-dce805d0e4b5)
![image](https://github.com/files-community/Files/assets/152221499/5e1ac0d5-340f-4527-a03c-f80033ccf416)

### Steps To Reproduce

1. Install Japanese IME
2. Open a folder containing Microsoft Office files

### Requirements

Fix incorrect display of files

### Files Version

3.0.8.0

### Windows Version

10.0.22635.2771

### Log File

[debug.log](https://github.com/files-community/Files/files/13480151/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, I've added this to the project board.

**Comment by 0x5bfa** [comment]
Thank you for the bug report. I have the same issue.

I guess the Office product has added those values in the Windows Registry on installed, in language you set on installing. And those values are, of course, hardcoded so we won't have no way to change them to be shown in the same language as Files app. The File Explorer follows Windows system language so you have probably never encountered this issue yet, however, once you changed the system language to another one you, I assume, will encounter this issue in the File Explorer as well.

If you have time, please change the system language to another one and see what will happen in File Explorer.

**Comment by 0x5bfa** [comment]
Thank you for the bug report. I have the same issue.

The Office product has added those values in the Windows Registry on installed, in language you set on installing (Japanese/ja-JP). And those values are hardcoded and I think this issue persists in the File Explorer too. The reason why the others are shown properly is because Windows have modified the Windows Registry when you've changed system language. But these are from the  Office product no from Windows and so neither of us nor Windows cannot figure our a way to modify when you change the system language.

You can see those values in `regedit.exe` with the path `HKEY_CLASSES_ROOT` -> `.xlsx` -> `...`
