### ISSUE TITLE
Icons appeared delay in column view

### ISSUE THREAD

**Issue by panbeep** [files-community/Files#14215]
### Description

When the files are displayed in column view mode the file icons appear after the list has been shown.
Summarizing - first file names appear then icons show up.

### Steps To Reproduce

Switch to columns view

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.0.15

### Windows Version

Windows 11 22621.1848

### Log File

no log

**Comment by yaira2** [comment]
Thank you for your feedback, the icons are indeed loaded after the items to improve performance. Of course it would be great if they loaded instantly and we're working towards improving the performance, but as it is today, the thumbnails take a bit of time to load, and we didn't want to slow down the loading items because of that.

**Comment by yaira2** [comment]
We'll continue tracking this in #4180.

**Comment by ErickYu-code** [comment]
希望能及时解决这个问题，加载延迟很影响使用体验
