### ISSUE TITLE
Bug: `Boolean operators` isn't working in searches

### ISSUE THREAD

**Issue by Rayds123** [files-community/Files#14331]
### What feature or improvement do you think would benefit Files?

Unlike File Explorer, I am unable to perform a negative search running Windows 11.  What am I doing wrong?

### Steps to repro

- Create text file named "Text 1.txt" and another file called "Text 2.txt"
- Search for `Text NOT 2` and see that no results are returned

### Expected behavior

Support `Boolean operators`

### Files Version

3.0.15.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files uses the same system and Windows File Explorer, What does Files show compared to Windows Files Explorer when doing the search?

**Comment by Josh65-2201** [comment]
If you tried to upload an attachment you will have to do that directly in GitHub. Click `View it on GitHub` link > Goto the comment box > Drag and drop, Pastes or click add attachment > Selected the images > wait a few seconds > Click comment

**Comment by Rayds123** [comment]
Thank you but I’ve burned up enough time.
________________________________

**Comment by yaira2** [comment]
We'd like to investigate this issue but we need some more info to debug.

**Comment by fazioliamboina** [comment]
> If you tried to upload an attachment you will have to do that directly in GitHub. Click `View it on GitHub` link > Go to the comment box > Drag and drop, copy and paste or click add attachment button > Selected the images > Wait a few seconds > Click comment

you can actually ctrl+V right into the message to paste an image inline.

**Comment by Qin-shihuang** [comment]
I think the issue is that Files does not support the [Advanced Query Syntax](https://learn.microsoft.com/en-us/windows/win32/lwef/-search-2x-wds-aqsreference) feature.

For example, for files like 
![image](https://github.com/files-community/Files/assets/68013339/74e4f5e8-8dd7-4af1-8446-12c704522daf),

you can search in Explorer using "file -3" to find the remaining two files,
![image](https://github.com/files-community/Files/assets/68013339/6c073cf2-083c-48e2-a4d1-1fd167c5fba2)

 or use "kind:txt" to find "file 2.txt"
![image](https://github.com/files-community/Files/assets/68013339/39adc592-8aaf-483f-bf3f-ab2ae7e10d37)


 However in Files, any combination of AQS strings produces no search results **before clicking on "Search unindexed items"**
![image](https://github.com/files-community/Files/assets/68013339/d945bb3e-eb6f-46d1-9084-54c83f0d9df0)

After clicking that, Files behaves the same as Explorer.
![image](https://github.com/files-community/Files/assets/68013339/085e9086-77da-4c11-8f7f-93eef1ab556c)

**Comment by yaira2** [comment]
> I think the issue is that Files does not support the [Advanced Query Syntax](https://learn.microsoft.com/en-us/windows/win32/lwef/-search-2x-wds-aqsreference) feature.

Files does support Advanced Query Syntax so I don't think that's the case.

**Comment by yaira2** [comment]
It should already work as long as the items are indexed, where are the files located?

**Comment by Rayds123** [comment]
Within a folder on C Drive, note setting…

**Comment by yaira2** [comment]
Depending on what you set for Windows to index, that would explain why it's not working. Can you see what happens if you add that location to the search index?
![image](https://github.com/files-community/Files/assets/39923744/20a0b855-a714-4afa-a50a-038efba0acb7)

**Comment by Rayds123** [comment]
No go, negative search does not work…

**Comment by yaira2** [comment]
@Rayds123 did you add that location to the search index? It can also take some time for Windows to index those files, you can confirm by checking how many files are pending.
![image](https://github.com/files-community/Files/assets/39923744/950f4bf3-0f50-4ae2-9409-9aba4a74e5c9)

**Comment by yaira2** [comment]
I did some further tests and was able to reproduce this issue. AQS is supported and works correctly for `File kinds` but it appears  that `Boolean operators` is not.

**Comment by yaira2** [comment]
@Rayds123 can you check what happens if you start the query with `$`?

**Comment by yaira2** [comment]
Excellent

**Comment by Rayds123** [comment]
Thank you for your guidance.  One final Q, will $ be built in or have to be manually added?

**Comment by yaira2** [comment]
I think we can build it in once #9711 is implemented but we'll have to see then.
