### ISSUE TITLE
More folder global edit view options in settings

### ISSUE THREAD

**Issue by CrisA-Works** [files-community/Files#14347]
### What feature or improvement do you think would benefit Files?

Currently limiting folder global view editing to only Mosaic, Icons (only medium size), Columns and Details it's a bit lackluster, considering that you can actually change the view to small icons manually. I dislike BIG ICONS, they just take too much space, and since I can't set the view to small icons to all folders I'm left with options I wouldn't use.

### Requirements

- Add another options for "Small icons", "Medium icons" and "Large icons" in the global edit view in folder settings.
- (Optional) Maybe even add a personalized bar/field where you can input a specific percentage, for even more flexibility and ease of use.

### Files Version

3.0.15.0

### Windows Version

10.0.19045.3803

**Comment by yaira2** [comment]
> "Small icons", "Medium icons" and "Large icons" 

These are sub options for the grid layout so that's why they aren't displayed in the "default layout" dropdown. We're planning to add additional flexibility in this area including support for changing the defaults in #10492. Please add a comment or subscribe to that issue to be notified of any updates. In the meantime, you might be interested in the option to sync folders settings across all directories.

**Comment by CrisA-Works** [comment]
Ah ok, thank you. Sync folders settings will do the trick for now, unless there there comes the time I need a specific setting I don't want to sync hehe.
