### ISSUE TITLE
Python Scripts are executed in %windir%\System32 instead of the current working directory

### ISSUE THREAD

**Issue by A-Loot** [files-community/Files#14419]
### Description

When executing a python script by double clicking it, it is executed in %windir%\System32 instead of the current directory. I checked and the scripts aren't run as admin so that can't be the problem.

A workaround would be to open the current folder in cmd and excecute the script with "python script.py" or to directly type "python script.py" in the address bar

### Steps To Reproduce

1. execute the following python script by double clicking it. it prints out the current working directory and if the script is executed with admin privileges:
```py
import os
import ctypes

def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

# Print the current working directory
print("Current working directory: ", os.getcwd())

# Check for admin permissions
if is_admin():
    print("The script is run with administrator permissions.")
else:
    print("The script is not run with administrator permissions.")

# Prevent the script from automatically exiting
input("Press Enter to exit...")
```

2.  in Windows Explorer I get the following output:
```
Current working directory:  C:\test
The script is not run with administrator permissions.
```

3. in Files I get the following output:
```
Current working directory:  C:\WINDOWS\system32
The script is not run with administrator permissions.
```

### Requirements

- Fix Python scripts not being executed in the current working directory

### Files Version

3.1.1.0

### Windows Version

10.0.23612.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/13888098/debug.log)

nothing there

**Comment by yaira2** [comment]
I'm pretty sure this is the same as #12950

**Comment by Qin-shihuang** [comment]
In the `OpenPath()` method of `Files.App\Helpers\Navigation\NavigationHelpers.cs`, the working directory for the file executed through` Win32Helpers.InvokeWin32ComponentAsync()` is normal, but when executed through `Launcher.LaunchFileAsync()`, it's the case of this issue. I'm not sure if it is intentional that there's two different execution methods.

You can verify this by setting the file as hidden, as the latter method is the default, and `OpenPath()` executes all hidden items in the former method.

|  Win32Helpers.InvokeWin32ComponentAsync()    |   Launcher.LaunchFileAsync()   |
| ---- | ---- |
|    ![image](https://github.com/files-community/Files/assets/68013339/7bb08c83-a0b7-4299-9e3b-a7e13b8fb8e4) |   ![image](https://github.com/files-community/Files/assets/68013339/4031b618-b96a-4a1d-9fce-b8d50062fad4) |

**Comment by Josh65-2201** [comment]
Should this be merge with https://github.com/files-community/Files/issues/12950 ?

**Comment by yaira2** [comment]
> Should this be merge with https://github.com/files-community/Files/issues/12950 ?

@hishitetsu

**Comment by hishitetsu** [comment]
> Should this be merge with #12950 ?

I believe so.
