### ISSUE TITLE
Feature: Add an option to "pin" the dual pane option to the toolbar

### ISSUE THREAD

**Issue by NightmareZero** [files-community/Files#14426]
### What feature or improvement do you think would benefit Files?

I often use your "new pane" and "close pane" features
But it is in the "see more" button
Can you add an option to customize the buttons displayed in the toolbar, or simply move it from "see more"?
Maybe you have already implemented this feature, but I haven't found it. I have tried dragging and searching it in the options, but it doesn't work

### Requirements

Add customization options for which buttons to be displayed in the toolbar
Or
Simply move them from "see more" to the toolbar

### Files Version

3.1.1.0

### Windows Version

10.0.22631.3007

**Comment by yaira2** [comment]
Thank you for your feedback

**Comment by Draise14** [comment]
To expand...

### What feature or improvement do you think would benefit Files?

![image](https://github.com/files-community/Files/assets/35357409/ddb66b42-059c-4c52-9011-66330a9eda29)

Allow the ability to pin any layout and view operators to go to a top level for user customizability. 

### Requirements

- Allow power user customizability
- Allow some user preferred operators to not be so deep or need to be reliant on a hotkey that may conflict with another software
- Allow to quickly use an operator with a single click (no menu) if needed


### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

### Comments

Typically this could be done using Dolphin or the W10 file explorer - where you can pin and re-order different operators to customize the explorer to your needs, like pin the ascending or descending toggles to a top level (instead of 3 deep)
![image](https://github.com/files-community/Files/assets/35357409/ba150af4-8f80-42b8-a4af-f9d409ec1c88)

**Comment by yair100** [comment]
If the shortcut keys conflict with other apps, you can remap them by manually editing the settings file. https://files.community/docs/customize-settings/actions

**Comment by yaira2** [comment]
Thank you for your feedback, we're going to continue tracking this request in #16188.

**Comment by yair100** [comment]
This feature will be included in the next update.
