### ISSUE TITLE
Bug: File drag and drop crash in Grid Layout

### ISSUE THREAD

**Issue by vavacll** [files-community/Files#14484]
### Description

when I try to drag and drop file it crashes

### Steps To Reproduce

https://github.com/files-community/Files/assets/156901955/7bc8886e-6dfc-42b0-9f71-5d10c7bab831

### Requirements

 Fix crash that occurs when

1. I have files layout type on small, medium or large 
2. and I try to drag and drop to another window

### Files Version

3.1.1.0

### Windows Version

10.0.19045.3930

### Log File

[debug.log](https://github.com/files-community/Files/files/13966918/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
Does this issue occur with the Details layout as well?

**Comment by vavacll** [comment]
no it only occurs in small, large and medium layouts
________________________________

**Comment by vavacll** [comment]
no its an issue in both versions
________________________________

**Comment by vavacll** [comment]
it started to appear in the tile's layout for some reason last time I checked it worked fine but now it crashes to
________________________________

**Comment by vavacll** [comment]
it started to appear in tiles layat for some reason last time I checked it worked fine but now it crashes to
________________________________

**Comment by yaira2** [comment]
Is there any difference in Preview version v3.1.6?

**Comment by vavacll** [comment]
no it still crashes
________________________________

**Comment by benji78** [comment]
This a bug I have had for more than a year, ever since I started using files as my default explorer. I never reported it because I don't have time to test it on another windows machine as mine is heavily de-bloated and customised, I never got anything out of the debug.log file (for this particular kind of crash) and there were may different variations of this bug which seem to have now been fixed.
It never occurred to me that it could be layout dependent as I mostly use tiles and sometimes icons layouts, but it indeed seems that the details and columns layouts are not affected.
However what I found, is that crashes only occur now when crossing or hovering over the status bar at the bottom of the files window, pretty much in the only direction I would want to drag a file to!

**Comment by yaira2** [comment]
@vavacll can you try to repro this in the latest preview build again? I don't see anything in the log file but hopefully the report will show up in App Center.

**Comment by yaira2** [comment]
This is what I see in AppCenter
```
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.DataTransfer
IDataPackageViewMethods.get_RequestedOperation (IObjectReference _obj)
Files.App.Utils.Storage
FilesystemHelpers.PerformOperationTypeAsync (DataPackageOperation operation, DataPackageView packageView, String destination, Boolean showDialog, Boolean registerHistory, Boolean isTargetExecutable, Boolean isTargetPythonFile)
Files.App.ViewModels.Layouts
BaseLayoutViewModel.DropAsync (DragEventArgs e)
CommunityToolkit.Mvvm.Input
AsyncRelayCommand.AwaitAndThrowIfFailed (Task executionTask)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
```

**Comment by vavacll** [comment]
should I still repro ?
________________________________

**Comment by yaira2** [comment]
I think the report I added above is from this crash.

**Comment by hishitetsu** [comment]
I can reproduce.
![Image](https://github.com/files-community/Files/assets/66369541/fe086203-a148-4204-a58b-0cdbc8192784)

**Comment by hishitetsu** [comment]
I believe this is a WinUI 3 issue.
https://github.com/microsoft/microsoft-ui-xaml/issues/9119

**Comment by 0x5bfa** [comment]
@hishitetsu Don't we have to disable this also on List and Details view mode if the issue comes from ListView and GridView? Or you don't see any crash on these views?

https://github.com/files-community/Files/blob/239f4bc8fe6f95c9b5aa83938efb2358fe8cbaab/src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs#L698

**Comment by 0x5bfa** [comment]
The issue in WinUI seems to have been fixed.

> You were right about the needed changes, and they will be part of the next WinUI3 release.
