### ISSUE TITLE
Feature: Add thumbnail options to Files

### ISSUE THREAD

**Issue by 82513931** [files-community/Files#14515]
### What feature or improvement do you think would benefit Files?

Functionally similiar to what https://www.videohelp.com/software/Icaros does. Files seems to already be compatible with it as shown in the attached picture but it would elevate Files greatly if a function like it was built-in & we wouldnt need yet another program for clean thumbnails.
It doesnt handle thumbnails itself, it just does the thumbnail generation for Windows giving u the option to make ur Thumbnails as clean looking within folders as you want.
![image](https://github.com/files-community/Files/assets/157329627/e4e9b595-c334-4bc6-a017-c7de137058a5)
![image](https://github.com/files-community/Files/assets/157329627/c73b26e1-78a9-4293-b141-f8c2ef1d12a1)

### Requirements

- This proposal will accomplish cleaner thumbnails.
- This proposal will accomplish the need for less programs.
- This proposal will accomplish elevating Files by having a feature no other File Manager has.

### Files Version

3.1.1.0

### Windows Version

11

**Comment by Josh65-2201** [comment]
Thanks for the feedback, I've added this to the project board.

**Comment by yaira2** [comment]
Thank you for the feedback, I'm with you when it comes to reducing the need to install extra apps so I know this response might be a little disappointing. Thumbnail generation is a complex process and building/maintaining a feature like this is a major undertaking and is not something we have the capacity to work on in addition to maintaining the rest of the app. There are some exceptions, but our general rule is that if there is already an existing extension that'll work with Files (eg. QuickLook, Power Rename etc), we prefer to let the extension fill the gap instead of "bloating" Files with another feature.

**Comment by 82513931** [comment]
> Thank you for the feedback, I'm with you when it comes to reducing the need to install extra apps so I know this response might be a little disappointing. Thumbnail generation is a complex process and building/maintaining a feature like this is a major undertaking and is not something we have the capacity to work on in addition to maintaining the rest of the app.
> 
> There are some exceptions, but our general rule is that if there is already an existing extension that'll work with Files (eg. QuickLook, Power Rename etc), we prefer to let the extension fill the gap instead of "bloating" Files with another feature.

Not dissapointed at all. I only thought of it as an extra gimmick anyway. Im actually positively surprised at your response to it on discord about how you guys prioritize bug fixes & such. Great Work! Keep it up!
