### ISSUE TITLE
Moving the Files window is lagging across the screen

### ISSUE THREAD

**Issue by BananaAcid** [files-community/Files#14565]
### Description

The window does not move smoothly like any other window when dragging on the titlebar. It feels like using 20 FPS ... or neds 200ms to update the position.
Setting to calculate folder size is off.

Any Chrome window with A LOT of tabs manages it, as well as word or outlook and photoshop, premiere and blender.

GPU: RTX 3070, newest drivers installed.
CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz, 6 cores, 12 logical cores, all windows optional chipset drivers installed.
RAM: 64GB

### Steps To Reproduce

1. grab the titlebar and move the window

### Requirements

Update the position related to the mouse cursor faster (

### Files Version

3.1.1.0

### Windows Version

10.0.22000.2538

### Log File

There is no actual bug to log.

**Comment by Josh65-2201** [comment]
Thanks for the report, can you see if this is an issue in the preview version. https://files.community/download

**Comment by yaira2** [comment]
Thank you for the report, unfortunately this is a known issue with WinUI applications (it's even more apparent resizing the window). Considering this issue is present in all WinUI applications (eg Phone Link) and not just Files, it would be best if you open a bug report on the WinUI repository https://github.com/microsoft/microsoft-ui-xaml and link to this issue here for reference.
