### ISSUE TITLE
 Bug: App becomes unresponsive when deleting certain files

### ISSUE THREAD

**Issue by Qin-shihuang** [files-community/Files#14732]
### Description

I selected a `.tar.gz` file of about 7GB in Files and tried to delete it, but the delete confirmation dialog did not appear until about 1 minute later. PowerToys Locksmith shows that the file was occupied by Files during this time. 

https://github.com/files-community/Files/assets/68013339/9ae6c236-59e9-4f18-ae13-abdc3aa6b327

### Steps To Reproduce

1. Delete a file
2. Observe that nothing happens
3. After waiting for a while, the confirmation dialog appears

### Requirements

The delete confirmation dialog should appear immediately

### Files Version

3.2.0.0

### Windows Version

10.0

### Log File

No log for that

**Comment by Qin-shihuang** [comment]
During this time, Files seems to be unzipping this compressed file. Quite a CPU-intensive work.

**Comment by yaira2** [comment]
Thank you for your feedback, do you have a lot of items already in Recycle Bin?

**Comment by Qin-shihuang** [comment]
No, it still happens when the Recycle Bin is empty.

**Comment by yaira2** [comment]
It usually happens when Recycle Bin is already full, but it can also occur when the shell is busy. As of now I'm not aware of a way to speed it up but we should avoid freezing the app (we can also show a discovering phase in the status center).
Let's continue tracking this in #14108.

In the meantime, you can see if you get better results with permanently deleting items.
