### ISSUE TITLE
advices

### ISSUE THREAD

**Issue by davidp88** [files-community/Files#14824]
### What feature or improvement do you think would benefit Files?

1.Think completely and work and that thinking should be done at once,do like this when writing also ,as little thinking causes mistakes.

2.think of each bit of how it can be improved but don't add useless and unnecessary features

3.Increase patience

4.do important work first

5.If u can't reproduce a bug normally then test thoroughly and try to reproduce for 2,3 times.

6.As far as possible try to reproduce bugs in win10 64bit as most of the users in the world use win10

7. don't use win11 for reproducing bugs as it's new and buggy,it takes many years by microsoft to fix basic issues.(read twice)

Make this read by all of your developers or else mistakes will happen.If they completely think and work then bugs will be properly fixed.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z
none

### Files Version

latest

### Windows Version

win10

**Comment by Josh65-2201** [comment]
Thanks for you feedback, Files is community developed so it the choice of others on what to work on. If you have an issue make a bug report otherwise it likely wont be fixed.

> don't add useless and unnecessary features

This is subjective and Files also fixes many bug too.

> If u can't reproduce a bug normally then test thoroughly and try to reproduce for 2,3 times.

This is what we already do and have multiple people try to reproduce. Not every issue can be reproduce by everyone either has they are different setups and tasks.

> don't use win11 for reproducing bugs as it's new and buggy,it takes many years by microsoft to fix basic issues.

Windows 11 doesn't cause many extra bugs then Windows 10. Files also works on both so if you have an issue make a bug report.

**Comment by davidp88** [comment]
also make the app look very beautiful with beautiful icons,beautiful looking breadcrumb bar and so on
