### ISSUE TITLE
Imrpovement in the speed

### ISSUE THREAD

**Issue by arvindkshukla** [files-community/Files#14820]
### What feature or improvement do you think would benefit Files?

Please improve the launch speed of the app. I like the app very much but it is very slow to open and function.

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.2.3.0

### Windows Version

10.0.19045.4046

**Comment by Josh65-2201** [comment]
Thanks for the feedback, We're tracking this in #4180 . You can check there or click subscribe in the right sidebar for updates.

If you turn on `Files settings > Advanced > Leave app running in the background when the window is closed` Files should only have the delayed startup for the first time. You can also turn on Start with Windows so that it always running for use.

**Comment by yaira2** [comment]
We're actively working on improvements to thumbnails but in the meantime, you can improve performance by turning off the option to show thumbnails.
