### ISSUE TITLE
Sluggish behaviour

### ISSUE THREAD

**Issue by joaopedroserrano** [files-community/Files#14907]
### Description

makes the system slow

### Steps To Reproduce

stops for several seconds when opening a folder or existing tab

### Requirements

- e.g. Fix crash that occurs when...
stops for several seconds when opening a folder or existing tab

### Files Version

3.2.6.0

### Windows Version

10.0.26063.1

### Log File

[debug.log](https://github.com/files-community/Files/files/14500757/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, we're working on improving performance and will continue releasing updates with this goal in mind. You can track our progress in #4180 by clicking the subscribe button on that issue.

In the meantime, you can get the best performance by keeping the default settings as well as using the Details View or List View layouts.

**Comment by Sebbe909** [comment]
@yaira2 No this is crazy, it should never have been a problem in the first place. Files is a magnitude slower than the also slow Win11 Explorer. There is no real benefit in using Files because it's painfully slow. This is mostly due to unthoughtful (lack) of caching and not making use of pre-rendering/pre-calculations. For example, it's crazy that if you open a folder and go back, it has to load and recalculate everything again. Or the fact that opening a new window//tab/instance is slow.

You should use much more inventive/creative ways of improving performance. Like literally caching the recently viewed folders, subcount, thumbnails etc. And for example already have a seperate window/instance ready (cloaked) to show when the user wants a new window. And possibly make use of lower level api's instead of some slower WinUI's.

It's not rocket science to develop a responsive, blazing fast app, even when using WinUI as basis. But apparently a lot of developers don't really think this stuff through. I'm willing to consult you on this.

Take the S Files Pro X app for example. About the same modern look as Files, but a much better alternative due to the blazing fast performance.

Not flaming or anything, just trying to be an eyes opener. Files would have potential if the actual overall performance was okay. Which simply is terrible right now compared to any alternative.

**Comment by yaira2** [comment]
We understand it's frustrating and know there is room for improvement, but drastic improvements don't happen overnight. Long term users can attest to the fact that performance keeps getting better, but aside from committing to continuing improving performance, we don't have much to add to this issue.

It sounds from your comment that you have some ideas, so we'd be happy to work with you if you're interested in contributing towards these efforts. As a side note, caching actually adds more overhead to an app like Files because the file structure is always changing and you anyways need to load the file list in addition to a cache.
