### ISSUE TITLE
Add font/UI size options

### ISSUE THREAD

**Issue by Koronfli** [files-community/Files#15067]
### What feature or improvement do you think would benefit Files?

I feel some fonts are too big! Maybe options to change font/UI size?

![Big fonts](https://github.com/files-community/Files/assets/165186473/595d9a05-12ef-4076-a65c-f9d417a8f10e)

### Requirements

- An option under Settings > Appearance to change side panel and main panel font sizes, and/or, % level options to adjust global UI size.
- Decrease layout options icon size (I believe it used to be different, no?)

### Files Version

3.3.0.0

### Windows Version

10.0.22631.3374

### Comments

![2024-03-27_16-10](https://github.com/files-community/Files/assets/165186473/ac7da0a2-cfc5-4c38-8fb1-94a9a5199d4d)

**Comment by yaira2** [comment]
> Decrease layout options icon size

This is on the todo list in #10492 (the same applies for increasing the icon size).

> An option under Settings > Appearance to change side panel and main panel font sizes, and/or, % level options to adjust global UI size.

If we do this, it will only apply to "crowded" areas of the app such as the sidebar and file list. We aren't committing to this part of the request but I think we can continue tracking it in #10492 since it's closely related.
