### ISSUE TITLE
Jittery scorlling, when displaying a lot of tags

### ISSUE THREAD

**Issue by PaulisX** [files-community/Files#15158]
### Description

When scrolling a folder, containing a lot of other folders with tags, the scrolling is jittery, pausing after every few folders, then continuing. It finishes the scroll animation about 1 second after stopping the scrolling on mouse.

### Steps To Reproduce

1. Create multiple folders (87 in my case)
2. Give every folder a tag
3. Scroll down or up fast with a single motion

### Requirements

The scrolling does not jitter, stop after every few folders when folders have tags.

### Files Version

3.3.0..0

### Windows Version

22H2

### Log File

[debug.log](https://github.com/files-community/Files/files/14949978/debug.log)

**Comment by PaulisX** [comment]
Closed by accident, my bad.

**Comment by yaira2** [comment]
I looked into this further and it turns out it's a known issue with the WinAppSdk framework we use in Files. We're going to close this issue but I'm linking the relevant issues here so you can add a comment to let Microsoft know this is affecting your workflow and usage of Files.

https://github.com/microsoft/microsoft-ui-xaml/issues/9584
https://github.com/microsoft/microsoft-ui-xaml/issues/9308
