### ISSUE TITLE
Impossible to use individual TAGs in the networks folder.

### ISSUE THREAD

**Issue by Markez2002** [files-community/Files#15227]
### What feature or improvement do you think would benefit Files?

In network folder when I create a TAG in file or folder , other colleagues that use same folder or files , appear in their FILE the same TAGs I created before , and if they deleted TAG also is deleted for me.

### Requirements

TAGs information should be stored for each user , and not in the folder where is the folder/file.

### Files Version

3.3.0 and 3.3.4

### Windows Version

10.0.19045.4291

### Comments

Thank you

**Comment by yaira2** [comment]
Thank you for your feedback.

Tags are saved using alternate data streams (and not in a database). We found that alternate data streams is the best approach because it allows items to be transferred between locations (even without using Files) without losing their tags. This does have the limitation you mentioned, but using a database would have its own list of limitations and we feel this is the better appraoch.
