### ISSUE TITLE
Bug: Delete doesn't work for all selected files/folders

### ISSUE THREAD

**Issue by VergilTG** [files-community/Files#15253]
### Description

Was trying to permanently delete some video files after recent update . but seems half of them gets deleted . 

### Steps To Reproduce

1. select multiple files 
2. press delete from tab 
3. confirm the delete 

### Requirements

- e.g. Fix crash that occurs when...
deleting multiple files 

### Files Version

3.3.5.0

### Windows Version

10.0.19045.4291

### Log File

[debug.log](https://github.com/files-community/Files/files/15098874/debug.log)

**Comment by ultenhiemer** [comment]
I have to second this. It's such a huge issue for me. I mostly delete multiple files when it comes to it, but 2 or more files being deleted at once just doesn't work. It just breaks this software in a big way for me.

Can still delete one at a time, but for multiples I'm having to switch over to File Explorer to do that job that this currently doesn't.

I have my own grievances with File Explorer with Windows 11, this was mean't to replace it. So having to go back to do some things this currently doesn't, is a huge pain!

**Comment by SpringsTS** [comment]
I have this problem when selecting multiple folders and deleting them: only the first one is sent to the recycle bin. I have to press the command for each folder.

**Comment by Josh65-2201** [comment]
Can you see if this is an issue in the preview version. https://files.community/download

**Comment by ultenhiemer** [comment]
> Can you see if this is an issue in the preview version. https://files.community/download

No the issue isn't repeated on the insider build after attempting to delete multiple files. I suppose it is just a problem with the stable release.

**Comment by Josh65-2201** [comment]
The update is available for the sideloaded version of stable, If you are using the Microsoft store there's a delay due to Microsoft.

**Comment by ultenhiemer** [comment]
> The update is available for the sideloaded version of stable, If you are using the Microsoft store there's a delay due to Microsoft.

Thank you!

**Comment by ultenhiemer** [comment]
> The update is available for the sideloaded version of stable, If you are using the Microsoft store there's a delay due to Microsoft.

Can I add a bit of context to this issue, because I think I might have figured the cause.

After installing the insider build (Before replying above), I never did any tweaking of the settings. I installed it and then immediately deleted multiple items to prove that it worked.

So I installed the updated sideloaded version you made available for download. I edited the settings to my liking and then the issue returned.

So I suspect the deleting issue is something within the settings that is activated that causes this. I ruled out as many options as I could. I suspect making the software default in the advanced options is the culprit. Because after activating most of my preferred settings, except for making the software default, deleting multiple items was a possibility again.

**Comment by VergilTG** [comment]
> Can you see if this is an issue in the preview version. https://files.community/download

seems the problem is fixed

**Comment by Josh65-2201** [comment]
>  I suspect making the software default in the advanced options is the culprit

Are you able to reproduce it consistently when changing the option, since set as default isn't used by Files actively. It's just for when other programs open Windows File Explorer.
