### ISSUE TITLE
Feature: Add audio file bitrate to details pane

### ISSUE THREAD

**Issue by benjaminfl721** [files-community/Files#15282]
### What feature or improvement do you think would benefit Files?

In file explorer the bitrate for audio files, along with other things like title, contributing artists, album name and length are previewed in the details tab.  But on files app it shows all that except for bitrate.  Instead you have to scroll down and click on 'properties', then 'details', and it will show the bitrate. For me and maybe other people, I sort and download a lot of audio files and its very helpful to be able to see the bitrate at a glance, so it would be nice to have it there next to all the other details.

Sidenote - on file explorer the bitrate is slightly different than what is shown on files app, I'm not sure if this is a bug or its just read differently. For example a 320kbps audio file on file explorer is shown as 312.5 kbps on files app, and a 192kbps file is shown as 187.5 on files app.  Im not sure why

![image](https://github.com/files-community/Files/assets/62226000/86967eea-12da-461e-8cbc-69cac02d9be4)
![image](https://github.com/files-community/Files/assets/62226000/2185aaec-e65c-4dfa-ab54-755430beb5c8)

### Requirements

- This proposal will accomplish ease of access for people who frequently check the bitrate of audio files

### Files Version

3.3.0.0

### Windows Version

23H2

**Comment by AlapanSen** [comment]
Adding bitrate information directly in the details tab of the Files app sounds like a useful enhancement, especially for users who frequently work with audio files and need quick access to such information. It streamlines the process and eliminates the need to navigate through additional menus to find the desired details.

**Comment by Artoryn** [comment]
Howdy! Would I be able to take this item? It might be a good first contribution or a way for me to get started helping with this project.

**Comment by 0x5bfa** [comment]
@Artoryn sure.

**Comment by Artoryn** [comment]
While making changes for this, I noticed that there is already code for formatting these bitrates. I believe the formatting should be moved to utilize the DisplayFunctions for both the Preview Pane and the Details section (of the properties window) for Video.EncodingBitrate and Audio.Bitrate.

I wanted to verify whether this would be acceptable due to the "Did you implement any design changes to an existing feature?" as centralizing and using DisplayFunctions would modify the properties window, which is outside the needed changes. Technically, this change is not required, but it cleans duplicate code.

**Comment by yaira2** [comment]
> Howdy! Would I be able to take this item? It might be a good first contribution or a way for me to get started helping with this project.

Just to pointer to lead you in the right direction, there is a properties json file that lists all the properties to be displayed in the details pane.
