### ISSUE TITLE
"Open terminal here" option missing

### ISSUE THREAD

**Issue by Pushan2005** [files-community/Files#15349]
### Description

Right click drop-down menu no longer lists the "open terminal here" option

### Steps To Reproduce

1. Right click in any directory (or right click on folder name)
2. No option to open in terminal

### Requirements

Expected behavior: ability to open a command line via the drop-down menu after right-clicking in the explorer

### Files Version

3.4.0.0

### Windows Version

10.0.22631.3527

### Log File

[debug.log](https://github.com/files-community/Files/files/15265289/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, the option is added and controlled by Windows Terminal. We don't know why it doesn't always show but it might be because it using the new system Windows 11 added for shell extensions. We're tracking this in #8251. You can check there or click subscribe in the right sidebar for updates.
