### ISSUE TITLE
Files app permanently froze after launching it a few times from cmd

### ISSUE THREAD

**Issue by RalkeyOfficial** [files-community/Files#15380]
### Description

I am using the non-microsoft store version of Files App,
Installed it an hour ago.

All was working fine, a bit slow, but still working.
Until I tried going to directories from the CMD.

I read from a previous issue that there was a cmd command to use Files app
https://github.com/files-community/Files/pull/6558#issuecomment-947072067

Now the app is unresponsive and loads nothing except the default tags
Re-starting the app also does not fix the issue.

![image](https://github.com/files-community/Files/assets/30209145/6472da5d-9437-4b02-97ca-35fd05dd1272)

### Steps To Reproduce

1. Have Files open
2. Try out the following cmd commands (don't know which is actually the faulty one)
    2.1. `files.exe`
    2.2. `files.exe -Directory "..."` (replace `...` with a directory)
    2.3. `files.exe -select "..."` (replace `...` with a directory)
3. re-open files

### Requirements

I expect one of the above commands to work, as I believe this was implemented from a previous issue.
I expect Files to load correctly.

### Files Version

3.4.0.0

### Windows Version

Windows 10 22H2 19045.4291

### Log File

No log file available

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

**Comment by Josh65-2201** [comment]
What happens if you close Files from the system tray and open normally from the Start menu > All apps.

**Comment by RalkeyOfficial** [comment]
> What happens if you close Files from the system tray and open normally from the Start menu > All apps.

Nothing changes then, it remains in this broken state

**Comment by 0x5bfa** [comment]
It looks like InnerNavToolBar doesn’t know what the page is shown in the active shell page, and AddressToolbar looks like its ViewModel is not loaded because SidebarView.PaneHolder property is null. This seems sometimes to happen first TabBar item is not added and loaded before somewhere else starts to load.
As almost all function is in AddressToolBar, the icons such as Back, Forward and Up, but somehow Refresh icon is loaded because it references CommandManager in code-behind. This proves that DI is loaded correctly.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/

If it is, please upload the log file so we can investigate further.

**Comment by Josh65-2201** [comment]
Is this still an issue in 3.7.11?
