### ISSUE TITLE
Video files can't be played in Preview Pane

### ISSUE THREAD

**Issue by Filikzz** [files-community/Files#15480]
### Description

- Video files can't be played in Preview Pane.
- Play button and video timeline are greyed out.
- I can see the play button and timeline for a split second, then it's greyed out.
- HVEC and AV1 + latest Geforce driver are installed.

![Screenshot 2024-05-27 224529](https://github.com/files-community/Files/assets/96303427/b5dcf1ed-ec6c-4965-9f3d-fb3876127e2e)

### Steps To Reproduce

1. open the app.
2. browse folder with video files
3. Video files can't be played in Preview Pane

### Requirements

- Video files can't be played in Preview Pane. No crash.

### Files Version

3.4.1.0

### Windows Version

10.0.19045.4412

### Log File

[debug.log](https://github.com/files-community/Files/files/15457992/debug.log)

**Comment by yaira2** [comment]
Thank you for taking the time to report this. We've tried debugging (via the Discord server) and it came it that this issue is with WinUI.

For future references, @Filikzz tested in the official WinUI gallery and it turns out this issue is present there as well.
![image](https://github.com/files-community/Files/assets/39923744/0e3050bc-b458-4dcf-a9e6-423d80186bfb)

We're going to close this issue but we suggest reposing this on the WinUI repo for them to look at https://github.com/microsoft/microsoft-ui-xaml.
