### ISSUE TITLE
Please add option to turn off animation effects

### ISSUE THREAD

**Issue by roydad** [files-community/Files#15497]
### What feature or improvement do you think would benefit Files?

Please add option to turn off animation effects

### Requirements

Animation effects will affect the experience of low-configuration computers

### Files Version

3.4.1.0

### Windows Version

10.0.19044.4412

**Comment by 0x5bfa** [comment]
For example where do you think you wanna turn off?

**Comment by mdtauk** [comment]
Do the animations not follow the System setting?

**Comment by yaira2** [comment]
Thank you for your feedback, Files has minimal animations to start with but you can disable them from the Windows Settings app.

**Comment by roydad** [comment]
> For example where do you think you wanna turn off?

When opening folders, the file list is not displayed as fast as the default explorer.

**Comment by 0x5bfa** [comment]
That's not caused by animation just WinRT API is much slower than shell Win32API File Explorer uses. We're planning to use Win32API instead. There's a almost solid idea.

**Comment by yaira2** [comment]
Frame.Navigate is also known to be a little slow

**Comment by mdtauk** [comment]
File Explorer still uses GDI for much of its rendering, which is why it can be faster, but also does not look as modern.

Using WinUI gives us lots of modern design and flexibility, but it does impact performance.  When improvements come via the Microsoft teams, we will update Files for them, and ways to improve performance are always being sought.
