### ISSUE TITLE
Default win10 context menu in win11

### ISSUE THREAD

**Issue by Plaban56** [files-community/Files#15583]
### What feature or improvement do you think would benefit Files?

whenever i right click on files to get the context menu, its layout is like the win11 default not the classic ones that can be set as default in win11. moreover it lags, it takes some time to open the context menu.

### Requirements

- This proposal will make the software more accessible to people like me who does not like the win11 context menu.

### Files Version

3.4.1.0

### Windows Version

10.0.22631.2861

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Using Windows 10 like context menu isn't possible as many options wouldn't work as they are for Windows File Explorer and doesn't follow the styles Files uses. 
Unfortunately it been slow is due to Microsoft WinUI framework WinUI framework https://github.com/microsoft/microsoft-ui-xaml/issues/8359. Please add a thumbs up on that issue to hopefully make it more of a priority to Microsoft.

**Comment by 0x5bfa** [comment]
I made a noise and hopefully they respond at least.

**Comment by yaira2** [comment]
> Thanks for the feedback, Using Windows 10 like context menu isn't possible as many options wouldn't work as they are for Windows File Explorer and doesn't follow the styles Files uses. Unfortunately it being slow is due to Microsoft's WinUI [microsoft/microsoft-ui-xaml#8359](https://github.com/microsoft/microsoft-ui-xaml/issues/8359). Please add a thumbs up on that issue to hopefully make it more of a priority to Microsoft.

This is correct, for example, basic options like "rename" are tightly integrated with Files and require a custom menu.
