### ISSUE TITLE
Folder tree structure opening and file drag and drop to folders and tabs

### ISSUE THREAD

**Issue by VinceS2** [files-community/Files#15855]
### What feature or improvement do you think would benefit Files?

A fundamental use of Widows Explorer for me is to easily organise files. A simple example is I have downloaded a fileto the Downloads folder and want to move it to a Loaded folder, or a particular category folder for the content. I am trying the Files app for the first time and cannot deduce a way to do this, simply, or at all.
Normally, I would click in the folder tree to cascade reveal the folder I want to put the file, drag it there and we are done (answering prompts if an identical copy exists). Yet, this Files app does not allow folders to be expanded. Nor can I drag the file to a separate tab with the correct folder open.
I am so amazed I am unable to do this simple function, yet cannot deduce what I have missed and why this is not default behaviour? I didn't come down in the last shower, having been a happy Commodore 64 programmer once and never lost touch with that side of things. But hey, you have me beat. Surely it is me and this is not really a new feature request?
I did try to look at Q&A's on Discord but it wouldn't accept the invite for no reason I could deduce. Hence logging it here.

I also note the help file is insanely rudimentary. For example, wondering what a Data Stream is and the help file assures me that this switch is for turning on the Data stream. Wow eh, who'd a thunk it? But what is it and why do we want it, or not? Thank you.

### Requirements

- This proposal will accomplish really basic functionality that is App-abandoning if not baked in.

### Files Version

3.5.0.0

### Windows Version

10.0.19045.4651

**Comment by 0x5bfa** [comment]
Thank you for the report and feedback, and at the same time I'd like to remind of [our code of conduct](https://github.com/files-community/Files/blob/main/.github/CODE_OF_CONDUCT.md) before submitting issues.

> I am so amazed I am unable to do this simple function, yet cannot deduce what I have missed and why this is not default behaviour?

I hear your pain but this project is driven by its community and the progress is slow because there aren't so many people here willing to help.
With that's said, the community also grows by people who report issues like you.

> Yet, this Files app does not allow folders to be expanded.

This feature is long requested but the codebase of the app isn't ready for that and we're still seeing slightly different request on it. For more information, visit #9182.

> Nor can I drag the file to a separate tab with the correct folder open.

You should be able to move items to another tab. Did you have the app run as admin?

> I did try to look at Q&A's on Discord but it wouldn't accept the invite for no reason I could deduce.

[This invitation link](https://discord.gg/files) does work (this is the expiration-free link)? If so, please try again later.

> I also note the help file is insanely rudimentary.

I don't understand what you mean. Do you mean documentations in https://files.community/docs?

**Comment by 0x5bfa** [comment]
Thank you for the report and feedback.

> I am so amazed I am unable to do this simple function, yet cannot deduce what I have missed and why this is not default behaviour?

I hear your pain but this project is driven by its community and the progress is slow because there aren't so many people here willing to help.
With that's said, the community also grows by people who report issues like you.

> Yet, this Files app does not allow folders to be expanded.

This feature is long requested but the codebase of the app isn't ready for that and we're still seeing slightly different request on it. For more information, visit #9182.

> Nor can I drag the file to a separate tab with the correct folder open.

You should be able to move items to another tab. Did you have the app run as admin?

> I did try to look at Q&A's on Discord but it wouldn't accept the invite for no reason I could deduce.

[This invitation link](https://discord.gg/files) does work (this is the expiration-free link)? If so, please try again later.

> I also note the help file is insanely rudimentary.

I don't understand what you mean. Do you mean documentations in https://files.community/docs?

**Comment by VinceS2** [comment]
Thank you for your kind comments. I apologize for any inadvertently emotive terms used; I am a big fan of community standards and ethics.

I just tried running the Files as admin and get a no drag and drop warning. Yet running as standard, no drag and drop capability turns up in any way I can get to work.

Tried the Discord link (which I do not know what Discord is nor have used it) and it wants to harvest an email address to verify 'something'. This is just to look at some help documentation? It is not a privacy bar I care to step over.

Re my crass comment on help, https://files.community/docs/customize-settings/files-and-folders tells me "Show alternate data streams" help as "This is off by default, enabling it will display alternate data streams." All the other stuff on that page is self-explanatory to me, although an explanation of why you would or wouldn't want to do that stuff should be given. Re data streams, it could mean so many things and, whatever it does mean, should be clear in the help screen. Like any option, whether it is or isn't activated should include a basic statement of what happens and why you do it or not. Whilst most mobo manuals are as ineffective at explaining 'the why' (I have built many a PC) and you are in good company, this kind of public facing software could easily be much better, and should. Thank you,

**Comment by yaira2** [comment]
@VinceS2 thank you for the feedback. I understand your frustration regarding the absence of certain features. The Tree View is a highly requested feature, and we are working hard to implement it. The primary challenge lies in its impact on performance, but we are optimistic about overcoming this hurdle and unlocking the full potential of this feature in the future.

**Comment by yair100** [comment]
@VinceS2 Tree View is currently available in preview https://files.community/download. It will be included in the next stable release.
