### ISSUE TITLE
Tab Actions Button Location Options

### ISSUE THREAD

**Issue by EchoARC9** [files-community/Files#15974]
### What feature or improvement do you think would benefit Files?

I really liked the tab actions button being in the toolbar next to the other layout buttons. The new update forces it to be in the top left of the title bar. The only option is to turn it off. Preferably it goes back to where it was or there is an option to put it on the top left of the title bar, the right side of the toolbar, or off.

### Requirements

Provide an option in the Appearance settings for the "tab actions button" to be on the left of the title bar, the right of the toolbar, or off.
- This proposal will accomplish consistency with the older versions.
- This proposal will provide more options for users.
- This proposal satisfies most people cause it was where it was for so long for a reason and it changed for a reason, so why not have both as an option?

### Files Version

3.6.0.0

### Windows Version

10.0.22631.3958

**Comment by yaira2** [comment]
Thank you so for your feedback Moving these options to a new menu is an important first step towards creating workspaces (#11900). We know how crucial muscle memory is, and we always try to avoid making changes that disrupt your workflow. However, sometimes these adjustments are necessary to improve the overall experience.

> so why not have both as an option?

We totally get that having a setting to customize the location might seem like a good idea. However, adding too many settings can make the app more complex and harder for everyone to use. It seems like the main concern here is muscle memory rather than the actual placement of the actions. Plus, if we added a setting, by the point users would already be used to the new location, making the setting unnecessary. 😊

**Comment by mdtauk** [comment]
I did imagine we would add the options to the right click menu when right clicking on a pane, so that may solve it.

**Comment by EchoARC9** [comment]
I would prefer the workspaces button also be in the toolbar instead of the title bar. I dislike having anything other than titles in the title bar. I use Edge instead of Chrome mostly for this reason.

Making the settings menu more complex is not an issue here, as you already have an option to hide it, just make that a dropdown instead. Plus I'm an advocate for more settings, if the settings UI is well designed it does not make it harder to use, in fact the opposite. The other big reason I use Edge instead of Chrome is due to its much better customization.

It is not just a muscle memory thing, it is also an efficiency thing. Putting it on the left of the title bar moves it as far away as possible from new panes, which is what I use it for the most. And I will not use workspaces very often so for people like me it is not that bad to move to the left to view them since I won't use them even as close to as much as I use panes.

**Comment by EchoARC9** [comment]
> I did imagine we would add the options to the right-click menu when right-clicking on a pane, so that may solve it.

This would be an acceptable solution. My biggest issue with it in the title bar is that it is so far from the new pane I make. Secondly, I think it looks awful.

**Comment by yaira2** [comment]
> I did imagine we would add the options to the right click menu when right clicking on a pane, so that may solve it.

I'm on board with this
