### ISSUE TITLE
功能小建议

### ISSUE THREAD

**Issue by Fearlessv** [files-community/Files#1602]
1. 删除时，弹窗会有永久删除选项，建议添加提示，永久删除是指不进入回收站直接删掉，还是仅仅在Files UWP 程序中不显示这个文件，新人会不好判断。
2.选择文件时不能通过拖选的方式选择文件，建议添加
3.回收站建议添加按照删除时间排序的功能
其他：Files UWP 做的非常棒，我十分喜欢！ 感谢开发者大大的努力，希望Files UWP能越来越好！

**Comment by Jaiganeshkumaran** [comment]
2 - #94
3 - You can already sort by deletion date

**Comment by duke7553** [comment]
@Fearlessv Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now as @Jaiganeshkumaran has listed the relevant issues above.
