### ISSUE TITLE
Bug: memory leak problem

### ISSUE THREAD

**Issue by NSJim** [files-community/Files#16043]
### Description

As long as the software is opened, it does not mention the increase in memory usage, about 0.1M per second, and there is no limit, and sometimes it can occupy more than 3G memory, which is the software that occupies the most memory in the computer, no one. This is a problem that has to be solved, otherwise no one will continue to use it.

### Steps To Reproduce

1. Use this software to open the folder
2. Open Task Manager to view memory usage
3. Keep the software open and check the memory usage one day later
4. You can find that the memory usage grows without limit

### Requirements

Fixing memory leaks
Reduce memory footprint

### Files Version

3.6.0.0

### Windows Version

10.0.19045.4529

### Log File

[debug.log](https://github.com/user-attachments/files/16685307/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback, memory usage is a longstanding issue (#4180) that stems from the framework, but we'll keep working to improve this from our end. In the meantime, we recommend turning off the setting to keep Files in the background.

**Comment by NSJim** [comment]
> Thank you for your feedback, memory usage is a longstanding issue (#4180) that stems from the WinUI framework, but we'll keep working to improve this from our end. In the meantime, we recommend turning off the setting to keep Files in the background.

You say this is because of WinUI framework, but why don't other programs have memory leak problems, and can you find solutions on other programs?

**Comment by yaira2** [comment]
Other apps using WinUI face similar issues, and we’ve been collaborating with their developers to find solutions. We’ve also reported these problems on the relevant Microsoft GitHub repositories. However, memory leaks in Files might be more noticeable due to the large amount of data it handles in a single session compared to smaller apps.
Some of these leaks could be from our own code as well, and I want to reassure you that we’re actively working to improve this (#4180). As always, we welcome pull requests from the community to help with this effort. Thank you so much for your feedback!

**Comment by yaira2** [comment]
Other apps using WinUI face similar issues, and we’ve been collaborating with their developers to find solutions. We’ve also reported these problems on the relevant Microsoft GitHub repositories. However, memory leaks in Files might be more noticeable due to the large amount of data it handles in a single session compared to smaller apps. Some of these leaks could be from our own code as well, and I want to reassure you that we’re actively working to improve this (#4180). As always, we welcome pull requests from the community to help with this effort.
