### ISSUE TITLE
Reduce opacity of file icons / thumbnails when dragging

### ISSUE THREAD

**Issue by Rick-HM** [files-community/Files#1615]
In my opinion, when dragging a file, it should have less opacity, since it is currently a bit annoying drag and drop in the navigation bar or in the sidebar.

**In all layout modes**

**Before:**

![before](https://user-images.githubusercontent.com/61259627/88981908-fecc0e00-d294-11ea-837f-f14824462aa8.png)

**After:**

![after](https://user-images.githubusercontent.com/61259627/88981899-fa075a00-d294-11ea-80b1-218aa428c008.png)

**Comment by duke7553** [comment]
We could customize the icon with DragUIOverride by setting it to a more transparent version of the item's icon.

**Comment by duke7553** [comment]
@Rick-HM @yaichenbaum Coming back to this because I forgot to follow up back in Sep 2020. 

In this case, we probably want to match the default WinUI behavior for dragging storage items. Having to adjust the transparency at the time a drag gesture is invoked would produce a small delay which could make the operation more unreliable than it already is. We're looking to improve drag and drop as a whole in the future, but there are much larger tasks needed before we can make the behavior consistent with other desktop apps.

Closing this now.
