### ISSUE TITLE
Adding a auto-hide function

### ISSUE THREAD

**Issue by mariacristina40** [files-community/Files#16262]
### What feature or improvement do you think would benefit Files?

It would be useful to add a auto-hide function to avoid windows overlap. We should be able to attach the Files window to a side of the desktop, to hide it and then, with the mouse over a small pin, to show its window again until the mouse is over it. When the mouse pointer leaves the Files window, the Files window is hidden again to a side and the little pin is shown. Thanks.

### Files Version

3.7.7

### Windows Version

Windows 11

**Comment by yaira2** [comment]
Thank you for your suggestion! While the idea of an auto-hide function to avoid window overlap is interesting, we believe this feature might be more appropriate as part of Windows rather than Files itself. Our focus is on providing a stable and intuitive file management experience, and we aim to keep the interface straightforward and user-friendly. However, we appreciate your feedback and will keep it in mind for future considerations. Thanks for sharing your thoughts!
