### ISSUE TITLE
更改UAC后，还是无法实行拖放

### ISSUE THREAD

**Issue by auroralzone** [files-community/Files#16279]
### Description

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/d3173fc7-3539-4d05-ac5c-a1bfadba077f">
UAC里 4个级别都逐一设置并且重启，还是无法实行拖放。

系统：Windows 10
版本1：预览版
版本2：3.7.7.0（经典）

### Steps To Reproduce

-

### Requirements

- e.g. Fix crash that occurs when...

### Files Version

3.7.7.0

### Windows Version

10

### User ID

files-community

### Log File

-

**Comment by 0x5bfa** [comment]
Thanks for the feedback.

Drag and drop is disabled when the app is running as admin or UAC is fully disabled (in your image it's 1). The former is due to a feature of Windows (UIPI) and the latter is a Windows issue (in DataExchangeHost.exe). I have an idea to make the latter work in Files but we haven't planned yet.

IIRC @yaira2 was positive about this. It's good timing to consider again?
It's to use [a 3rd party metadata of Detours](https://github.com/lowleveldesign/detours-win32metadata) to work with CsWin32. The only concern we would have is probably package size increase. I'd doubt that but we should check it out.

**Comment by yaira2** [comment]
I'm on board if @ahmed605 is. That said, checking the package size is important.

**Comment by ahmed605** [comment]
> I'm on board if @ahmed605 is. That said, checking the package size is important.

the approach seems good but ping me when you have an impl so I can check if it's good to go

**Comment by auroralzone** [comment]
> After changing to level 2, did you restart Windows?更改为级别 2 后，您是否重新启动了 Windows？

Yes.
1. changing to level 1, restart Windows.  Fail.
2. changing to level 2, restart Windows.  Fail.
3. changing to level 3, restart Windows.  Fail.
4. changing to level 4, restart Windows.  Fail.

**Comment by 0x5bfa** [comment]
Setting higher than 3rd doesn't work for you doesn't make sense.
Is your account in Administrators group or normal one (Users group)?

**Comment by auroralzone** [comment]
> Setting higher than 3rd doesn't work for you doesn't make sense.设置高于 3rd 对你来说不起作用，没有意义。 Is your account in Administrators group or normal one (Users group)?您的帐户属于管理员组还是普通帐户（用户组）？

`Administrator`

**Comment by 0x5bfa** [comment]
I'm confirming if you're logging in through BUILTIN/Administrator if so you can't drag and drop at all iirc. Did you create your account in a normal way?

**Comment by auroralzone** [comment]
> I'm confirming if you're logging in through BUILTIN/Administrator (to create it you would have been required to touch around Computer Management or something ordinal users don't know I forgot) if so you can't drag and drop at all iirc. Did you create your account in a normal way?我正在确认您是否通过内置/管理员登录（要创建它，您需要触摸计算机管理或普通用户不知道我忘记的东西）如果是这样，您根本无法拖放iirc.您是否以正常方式创建帐户？

Yes, `BUILTIN/Administrator`

**Comment by 0x5bfa** [comment]
You can't use Files fully with that account. Use normal account who belongs to Administrators group.
