### ISSUE TITLE
Bug: Software crashes

### ISSUE THREAD

**Issue by Altral** [files-community/Files#16327]
### Description

Files is running under Windows 11. Programm crashes after a couple of minutes using it.

Have re-installed it several times, both versions. Don´t know what´s the problem is.

### Steps To Reproduce

Its occurs every time I open the program, no other programs running.

### Requirements

Its occurs every time I open the program, no other programs running.

### Files Version

3.7.10.0

### Windows Version

10.0.22631.4317

### User ID

7cfe51b6-baf4-4fbc-9cee-5b02426dcdc3

### Log File

[debug.log](https://github.com/user-attachments/files/17304444/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the report, What are you doing when File crashes?

**Comment by yaira2** [comment]
I don't see any reports for your user id in Sentry. Can you check Event Viewer?

**Comment by coderzawad** [comment]
I am sus about this log
```2024-10-09 09:20:58.9686|Warning|Invalid path: Q:\GoogleDrive\My Drive```
and 
```2024-10-09 09:21:08.7959|Warning|SIDELOAD: Update not found.```

The path for Google Drive ```(Q:\GoogleDrive\My Drive)``` appears to be invalid. This might be due to a misconfiguration, missing network drive, or incorrect mapping of the Google Drive folder.

and the second logs cause maybe 
The app regularly checks for updates to the package `FilesPreview`, but each time it concludes that no updates are found, despite performing the check successfully.

This suggests that the update mechanism is functioning (as it checks both the current and remote package versions), but either no updates are available, or it's failing to detect updates if they exist.

**Comment by Josh65-2201** [comment]
If a Google drive path isn't found it just skips and log a warning it won't be the cause of this crash. Nether would there being no updates as there aren't any newer versions at the time this issue was posted.

**Comment by Altral** [comment]
It just close the program and I have to re-start, but it’s crashing again an againVon meinem iPhone gesendetAm 09.10.2024 um 09:53 schrieb Josh65-2201 ***@***.***>:﻿
Thanks for the report, What are you doing when File crashes?

**Comment by 0x5bfa** [comment]
As Yair mentioned, please send crash logs from Event Viewer (Windows logs > Application) if any.

**Comment by yaira2** [comment]
> I am sus about this log `2024-10-09 09:20:58.9686|Warning|Invalid path: Q:\GoogleDrive\My Drive` 

This is not related, in fact we longer log this line in the latest version of Files.

> and `2024-10-09 09:21:08.7959|Warning|SIDELOAD: Update not found.`

This isn't an error, it just means the app is up to date.

**Comment by Josh65-2201** [comment]
@Altral Can you reproduce the crash then look in Event viewer > Windows logs > Application > Anything errors related to Files.exe
