### ISSUE TITLE
Feature: Right-click menu

### ISSUE THREAD

**Issue by INTEL-AMD-NVIDIA** [files-community/Files#16341]
### What feature or improvement do you think would benefit Files?

Now the files can use windows 11 Right-click menu，but it seems that the Windows 10 Right-click menu is better than Windows11‘s，Can the files app support Windows 10 Right-click menu？

by the way my application version is 3.7.11.0 from Windows UWP，Windows 11 version is 10.0.22631.2506

with Windows 10 right-click menu ,users can choose his/her own way to conroll the files 

### Requirements

- This proposal will accomplish X
- This proposal will accomplish Y
- This proposal will accomplish Z

### Files Version

3.7.11.0

### Windows Version

10.0.22631.2506

**Comment by Josh65-2201** [comment]
Thanks for the feedback, Files uses the same style as Windows 11 one but supports all items in the one menu. There is no plans on making it look like Windows 10. A more compact layout is planned in #9506. You can check there or click subscribe in the right sidebar for updates.

**Comment by yaira2** [comment]
> Now the files can use windows 11 Right-click menu，but it seems that the Windows 10 Right-click menu is better than Windows11‘s，Can the files app support Windows 10 Right-click menu？

Although it resembles the Windows 11 context menu, it's actually a custom menu that we built for Files. While technically possible to show the File Explorer context menu, it wouldn't be practical since it's meant for File Explorer and options like rename wouldn't work. Additionally, functionalities unique to Files, such as tags and creating folders with selected items, would be absent.

All that said, we're working to make the context menu more responsive, and we are closely monitoring feedback to help improve the menu.
