### ISSUE TITLE
Bug: Slow performance in everything, needs a complete rewrite

### ISSUE THREAD

**Issue by nitin2953** [files-community/Files#16393]
### Description

Navigating folders backward and forward always results in a delay of about 1 second.

I don't think a file manager app should have any unnecessary animations. The loading indicator and skeleton animation make it feel even slower; just use a file/folder icon as a placeholder instead.

The core focus of this app should be fast, seamless file navigation without any heavy UI or animations. I think this can only be achieved by completely rewriting the app without using any heavy dependencies. Also, separating the app and its settings panel could improve overall speed.

The current version of the app has great UI and features, but its slow performance has kept me from using it regularly.

System: Windows 11 Pro 23H2
Processor: Intel i5-8250U @ 1.60GHz  1.80 GHz
RAM: 12GB
Storage: 240GB SSD

### Steps To Reproduce

nothing

### Requirements

nothing

### Files Version

3.7.11.0

### Windows Version

10.0.22631.4317

### User ID

f7268d3a-e9ff-453f-ad3c-5d178a63eadd

### Log File

[debug.log](https://github.com/user-attachments/files/17540048/debug.log)

**Comment by Lamparter** [comment]
Complete rewrite? That's very difficult, especially considering that the app has been around since 2018 and still isn't complete. 

As for it being slow, it's generally because of the framework the app uses, the Windows App SDK, which is a relatively new and unoptimised technology that is still being developed and is rapidly becoming more stable and more efficient. The splashscreen and skeleton animations have very little effect on the app's speed.
I suppose it'll just be a long wait until the framework becomes quicker (which ironically is actually happening very quickly) for the app to have a higher performance.

**Comment by yaira2** [comment]
Thank you for your feedback. We appreciate the push to improve performance. We're working hard on this and are really pleased with the progress we've continued to make in this area. We also recognize that as Files improves, expectations for performance rise, and we're committed to earning the community's trust in this area.

As @Lamparter mentioned, much of the performance depends on the WinAppSdk framework. While it has been improving over time, it's not yet at the same level as some older technologies. This is partly because it's newer and optimizations take time, but also partly due to its heavior design elements.

We'll keep tracking and reporting our progress in #4180 and hope you stick around for the journey.
