### ISSUE TITLE
Bug: abnormal ram usage increase

### ISSUE THREAD

**Issue by clementdelestre** [files-community/Files#16390]
### Description

RAM usage increases abnormally when simply browsing folders. 
Also, after backtracking, the parent folder still reloads, so there shouldn't be any additional used ram.

Example:
ram usage at startup : 182mo.
ram usage after 2min of intensive browsing : 450mo.

The ram is cleared after a full close of Files.

### Steps To Reproduce

Navigate files. Open several folders one after the other.

### Requirements

- e.g. Fix crash that occurs when...
The ram usage should not increase as much

### Files Version

3.7.11.0

### Windows Version

11.0.26100.2161

### Log File

[debug.log](https://github.com/user-attachments/files/17535439/debug.log)

**Comment by yaira2** [comment]
Thank you for your feedback. While memory usage will eventually decrease after letting the app sit idle, we know this isn't ideal. Unfortunately, memory usage in WinUI apps takes a while to clear up. The good news is that this issue isn't specific to Files; it affects other WinUI apps like the Microsoft Store as well. Microsoft is aware of the problem, and although it's been a number of years since we reported it, we remain hopeful that Microsoft will address it as they continue to improve WinUI. We'll continue tracking this in #4180 and will make sure to post an update when improvements are available in this area.
