### ISSUE TITLE
Feature: Move properties window to the info pane

### ISSUE THREAD

**Issue by czargab18** [files-community/Files#16420]
### What feature or improvement do you think would benefit Files?

By clicking on the **``properties``** icon, or typing ``Alt + Enter``, could the pop-up window that appears be ``changed to a sidebar``?

I believe this would be more elegant.

![Image](https://github.com/user-attachments/assets/69f3b0aa-13bb-4611-8e51-bd344721a44a)

### Requirements

- change the location of the dropdown window to sidebar.
- Or create, in the settings menu, the user preference option for this behavior.

### Files Version

3.7.11.0

### Windows Version

23H2

**Comment by Lamparter** [comment]
You mean add the ability to display the Properties window in the preview pane?

**Comment by czargab18** [comment]
> You mean add the ability to display the Properties window in the preview pane?

yes!

**Comment by yaira2** [comment]
The properties pages have content that requires a larger window (for example, the hashes and security pages). Additionally, users frequently open multiple windows simultaneously, which wouldn't be posible using the info pane.

**Comment by czargab18** [comment]
> The properties pages have content that requires a larger window (for example, the hashes and security pages). Additionally, users frequently open multiple windows simultaneously, which wouldn't be possible using the info pane.

If the user is opening folders simultaneously, why does this sidebar open in all the others?
Is there any specific reason for this?

**Comment by yaira2** [comment]
The side pane provides a quick overview, allowing users to view basic metadata and preview files in the preview pane. For more advanced options such as hashes and security settings, the expected workflow is to open the properties window. Similarly, if users need to edit the file, they should open the file itself rather than using the preview pane.

While we're open to enhancing the details pane with more information, we don't intend for it to completely replace the functionality of the properties window. The properties window is designed for more detailed, advanced interactions that the info pane isn't meant to handle.

Do you have any specific scenarios that you were looking to be supported directly from the details pane?
