### ISSUE TITLE
Feature: Improve the conditions for dragging and dropping files

### ISSUE THREAD

**Issue by ShuangTianSheng** [files-community/Files#16450]
### What feature or improvement do you think would benefit Files?

I hope to improve the conditions for dragging and dropping files. Currently, I need to increase the UAC level to achieve this. However, in this case, when I need to make changes to the file, the system will pop up a prompt to obtain permission every time. I hope there is a way for me to turn off the UAC level while also being able to drag and drop files with the mouse

### Requirements

I hope there is a way for me to turn off the UAC level while also , thank you very much

### Files Version

3.7.11.0

### Windows Version

19045.4651

### Comments

![Image](https://github.com/user-attachments/assets/2609b70a-1c01-44f5-bc9f-3e292a6a324e)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

This issue, where drag and drop causes a crash when UAC is fully disabled, is due to Windows bug. We have an idea to workaround this bug but we haven't worked on it yet.

**Comment by yaira2** [comment]
This issue is unfortunately due to a limitation with the WinAppSdk framework. While we can't address it on our end, I recommend sharing your feedback with Microsoft. If and when they resolve it, we'll update the framework to incorporate the fix into Files. https://github.com/microsoft/microsoft-ui-xaml
