### ISSUE TITLE
Extracting zip file crashes Files UWP

### ISSUE THREAD

**Issue by jamiehoss** [files-community/Files#1661]
**Describe the bug**
I downloaded the latest Win10 2004 security baseline zip file from Microsoft, then viewed it in Files UWP and right clicked on it and selected Extract, I get the dialog about the folder to extract it to (I leave the current folder selected) and start the extraction, at that point Files UWP crashes and zip file isn't extracted.

**To Reproduce**
1. Download a zip file 
2. Right click the zip file and select extract
3. Choose to extract to the current folder location
4. Files UWP crashes 

**Expected behavior**
That the zip file contents would be extracted

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 20185.1000
 - App version: [v0.12.0.0]

**Additional context**
I've closed and reopened the app with the same results
[debug.txt](https://github.com/files-community/files-uwp/files/5032008/debug.txt)

**Comment by Jaiganeshkumaran** [comment]
@jamiehoss Does it work when extracting using File Explorer or any other tool?

**Comment by Dylan-Osborne** [comment]
I get the same issue, Files UWP always crashes after extracting a zip file.

I somehow don't think think that the issue lies with the actual extraction as the files are always extracted successfully. It almost appears as if the crash occurs when Files UWP is processing the new folder that was created by the extraction (so that it can be added to the UI)

@Jaiganeshkumaran I only get this crash when extracting using Files UWP

[debug.txt](https://github.com/files-community/files-uwp/files/5101448/debug.txt)

**Comment by yaichenbaum** [comment]
@jamiehoss This issue should be fixed in v0.20.
