### ISSUE TITLE
UI is too slow for comfort

### ISSUE THREAD

**Issue by SirClickALot** [files-community/Files#16631]
### Description

Files is definitely growing on me but I am put off by the slowness of the response of the UI compared to the core Windows File Explorer.

Is there anything I can adjust (hardware acceleration etc.) to try to speed things up?

### Steps To Reproduce

There are none.

### Files Version

3.8.0.0

### Windows Version

10.0.22635.4655

### User ID

7a655b4b-4d4d-4809-8bec-f9c3d989c76c

### Log File

[debug.log](https://github.com/user-attachments/files/18217449/debug.log)

**Comment by 0x5bfa** [comment]
Thank you for the feedback.

While our primary focus has been to boost both startup and execution experience, there's a certain limitation due to the UI framework we use, called WinUI3. As for the startup boosting, we're planning to introduce a new feature came from the application framework, called AoT compilation, which is expected to reduce startup time down to 50%. For the general information, please take a look at #4180.
