### ISSUE TITLE
Feature: Sync the show file extensions option with the system

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16650]
### What feature or improvement do you think would benefit Files?

Currently, the show file extensions option is not synced with the Windows Explorer setting. This should be synced with the system to enable seamless integration.

This setting can be found from within the registry at `Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced` with key name `HideFileExt`.

### Requirements

- Change show file extension setting based on File Explorer configuration

### Files Version

`3.8.5.0`

### Windows Version

`10.0.22631.4391`

### Comments

cc. @IviriusMain

**Comment by Lamparter** [comment]
There are various other settings that should also be synced with the system.

**Comment by Lamparter** [comment]
Denied by app lead maintainer (IMPLIED)

**Comment by yaira2** [comment]
As a third-party app, it's not good practice for us to modify system settings. Additionally, the default settings in Files don't always align with those in File Explorer. We've made an exception for the quick access service because it's common for users to want their list of favorites and recent files synced system-wide, in order to be consistent with the file pickers.
