### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by cristiangerardo** [files-community/Files#1769]
Very good UI, but the performance is very bad. When accessing any folder, the system takes a long time to read and display the results.
In addition, the properties of disks such as folders or files are very basic.

**Comment by yaichenbaum** [comment]
@cristiangerardo Can you provide information about the number of items in the location, the drive type, and how long it takes to load the items? It would also be helpful if you shared how the speeds compare to File Explorer.

**Comment by perplexityjeff** [comment]
I continue to monitor the project with great interest but this is a lot of the reason that I am not using it as my daily driver as well. For example I use Tablacus now and it speed is amazing but the UI is outdated. 

Specs:
I have a 256 Samsung 8XX Pro SSD with 16GB RAM and a Ryzen 5.

**Comment by jakoss** [comment]
I'm prety sure that native file explorer does some heavy indexing/caching internally, that's why it's so fast. I'm not sure how files are doing that now, but i think that caching paths in some super-fast embedded database (for example LMDB is extremly fast - https://github.com/kwaclaw/KdSoft.Lmdb). I'd love to take a shot at this, but a newborn baby limits my time a little bit. I'll keep that in mind and if nobody will take this - i might later on

**Comment by yaichenbaum** [comment]
@jakoss The latest update should improve the performance, but if you have idea's to improve it further, feel free to take a look when you get a chance 😃

**Comment by jakoss** [comment]
I did some measurement and experiments with memory cache and unfortunetely - i think the "load performance" issue is somewhere else (probably the rendering itself). All code that listed files performed under 800ms (average 350 ms for 20 measurements on my machine) which is in my opinion acceptable. I'm not sure how to measure perceivable performance here, but i'm pretty sure that ui (time that took from clicking the folder to displaying it on screen) is slower than all the code i was able to measure (methods in `ItemViewModel` that updates the `_filesAndFolders`).

The only weird thing in my measurements was line `var syncStatus = await CheckCloudDriveSyncStatusAsync(_rootFolder);` in method `ItemViewModel.EnumerateItemsFromStandardFolderAsync`. This method sometimes performed under 20 ms, but a few times it jumped even to 300 ms, and i could not correlate this to anything - the folders were all similar in size. I did all the testing on local folders, so i believe this can be avoided somehow.

Now, since i'm far from UWP expert (or any UI in particular) i probably cannot help you with UI optimizations, sorry

**Comment by jakoss** [comment]
Scratch my previous answer, there is a way to cache files list and i believe that i managed to do that quite efficiently. For now i'm caching only in RAM memory, but i can try and move it to some persistent storage if result will be promising.

There's still some work to be done, for example:
- Use some persistent store for cache (DBreeze in my opinion will be the best solution here)
- Cache preemptively - if user navigates to some directory we can check if parent directory and all children directories are caches as well. If not - we can read them in background and store in cache. This has the potential to smooth navigation out significantly

But the foundation seems to be quite solid. @yaichenbaum please take a look at PR draft: https://github.com/files-community/Files/pull/2655

**Comment by gave92** [comment]
Could we close this thanks to #2655?

**Comment by yaichenbaum** [comment]
@gave92 I would hold off on closing this until @jakoss creates a pull request to finish this feature.

**Comment by jakoss** [comment]
Yes. You could release this as is now, as optional and experimental feature. And I'll add preemptive caching asap

**Comment by jakoss** [comment]
@cristiangerardo Please test out the 1.0.0 release. In experimental settings there's flag for caching. This should give a decent performance gain. That's obviously not my last word. I'm planning to expand this to do preemptive caching and add more settings to finetune caching (memory and disc space usage)

**Comment by jl91569** [comment]
Caching helps slightly on loading a folder but scrolling through a cached folder after refreshing it is still extremely choppy while loading extended file properties (the app can become unresponsive for more than a minute in folders with many .exe files after right-clicking with Windows Defender enabled, though scrolling is choppy on any folder with a large number of items). This only happens on first scroll after opening a folder (even a cached one) though, as icons and type descriptions are only loaded from disk once every time a folder is opened.

I'm not sure how much it would help, but would it make sense to cache type descriptions since they are on a per-extension basis instead of a per-file basis? I don't believe caching every extension type permanently makes sense since file associations can change at any time, but caching the current folder's associations might be a good middle ground as Files doesn't automatically refresh when default associations are changed anyway.

Icons are a bit more difficult but most types seem to have static icons in list view as well; the exceptions on my machine are `.ani`, `.cur`, `.exe`, `.ico`, `.icl`, and `.msc` but I don't believe this is detectable through UWP as it's set in the registry's file associations list. 

I guess a potential solution to icons could be making a registry check on the first item (seeing as Files is already able to make registry calls) and checking if `DefaultIcon` for that extension handler is set to `%1` and caching that for the current folder, but I'm really just thinking out loud here and I'm not sure whether adding an additional layer would noticeably degrade performance for folders with fewer items (would it positively impact memory usage if there's a large number of static icons?).

![image](https://user-images.githubusercontent.com/10607947/104395650-47565a00-559d-11eb-9e87-bc921505d0f7.png)

For reference the folders I am using are in the hundreds of files (the .exe folder has approximately 300 files, though it hangs with ~20 .exe files and scrolling is choppy in the ~50 files range).

**Comment by perplexityjeff** [comment]
@jakoss I am checking out the performance gain with caching versus not caching and it is noticeable for sure and takes the loading of a folder faster. So from just a caching point of view I like where it is going. Thank you for all that work and I look forward to the improvements to it.

However the odd flickering loading and reloading when loading in a folder or the incomplete list that gets populated first and moments after updates with the correct list makes the whole experience feel a bit weird to me however that is present as well when you disable caching.

Also like @jl91569 stated is that the scrolling feels clunky especially when icons and the file descriptions get loading in while scrolling. 

I do like the new version better of course and I see improvements I just hope for even more on the performance side of things and make the whole experience smooth.

**Comment by jakoss** [comment]
Hmm, as to scrolling. We could consider caching icons, but i think the most important part is that it shouldn't be clunky anyway. It should load for example 10 icons concurrently, but it should never claim 100% cpu which can result in stuttering. So i believe simple queue (parallel limiter) for `LoadExtendedItemProperties` might do just fine for start. All icons will load slower, but without the bad "feeling" of scrolling

**Comment by jl91569** [comment]
I tried implementing a very simple cache for file types on my fork and scrolling performance is somewhat better at low velocities but is around the same or slightly worse at high velocities, but there is still significant stuttering (I'm a hobbyist so my code is very unoptimised, there's definitely a better way to implement it that I haven't thought of).

I'm not sure how to consistently test it though, and there's some odd behaviour around generating media thumbnails when multiple instances are open which might make my results not representative of the program's actual performance.

**Comment by jakoss** [comment]
Even the best caching won't save you if you're trying to load a 100 icons at the same time. I'll took at this and try to limit the parallel execution here

**Comment by yaichenbaum** [comment]
Further enhancements will continue to be made, but I think the changes with #2655 and #3045 should make Files much smoother to use.
