### ISSUE TITLE
the program just freezes and the only thing i can do is drag it around

### ISSUE THREAD

**Issue by TomerGamerTV** [files-community/Files#1879]
**Describe the bug**
the program just freezes and the only thing I can do is drag it around

**To Reproduce**
1. view some folders
2. click on properties
3. exit properties
4. window stuck

**Expected behavior**
to work normal I think

**Screenshots**
it's just stuck like normal but not working so there is no what to screenshot

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004]
 - App version: v0.14

**Additional context**
 restarted the program now it's working again normal

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5179123/debug_fulltrust.txt)

**Comment by duke7553** [comment]
@TomerGamerTV Does this occur when closing the Properties window in a particular way? Like by the close button, or the X caption button only?

**Comment by TomerGamerTV** [comment]
> @TomerGamerTV Does this occur when closing the Properties window in a particular way? Like by the close button, or the X caption button only?

The x button I think oh and plus I found some other real crashes

The program crashing then I'm trying to move big files or view them

**Comment by duke7553** [comment]
@TomerGamerTV The issue you mentioned with moving large files might have been fixed with the reliability improvements we're making to storage item operations including paste. I would suggest reproducing the issue in the latest preview, and if you encounter a crash, open a new issue with the debug log attached. Also please follow #632 for updates on that one.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2045.
