### ISSUE TITLE
Occasional crash when viewing properties of secondary storage device

### ISSUE THREAD

**Issue by arasthudev** [files-community/Files#1947]
**Crashes while opening properties tab**
The app crashes once opening of a properties tab occurs by right clicking.

**To Reproduce**
1. Go to 'Secondary Storage Device' (Not C:\ Directory)
2. Right Click on 'Folder'
3. Scroll down to 'Properties'
4. Sometimes see error, no idea what's causing it

**Expected behavior**
To show the properties tab without crashing.

**Screenshots**
Cannot add, how to add crashing screenshots? All I had was a option saying submit a bug report in the notification panel.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.508]
 - App version: [v0.14.0.0]

**Additional context**
Does this problem occur again after restarting the app? Yes

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug.txt](https://github.com/files-community/files-uwp/files/5250402/debug.txt)

**Comment by Thomas1664** [comment]
This happens when you remove a secondary storage item while the app is still open. After removing the drive, you can still view the files in it. If you rightclick on any item, the full trust process will crash and if you then try to open properties, the application will crash at `FolderProperties.cs`, line 86.
Instead of letting the user view items of a removed drive, we should display an error message or redirect to home.

**Comment by yaichenbaum** [comment]
@arasthudev Is this still an issue with v0.21.1?

**Comment by yaichenbaum** [comment]
Thanks again for your feedback.

_Since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
