### ISSUE TITLE
Ability to drag files between tabs in the same window

### ISSUE THREAD

**Issue by asuetin** [files-community/Files#1968]
**Is your feature request related to a problem? Please describe.**
Currently it's impossible to drag a file from one tab to another in the same window.

**Describe the solution you'd like**
Make inactive tabs into valid drop targets, and also activate the target tab after hovering over it for a certain period of time (similar to how you can hover a file over an opened application on the taskbar and the window will activate).

**Comment by yaichenbaum** [comment]
@duke7553 Can you confirm that this has been implemented for a couple of versions already?

**Comment by generalguy41** [comment]
@yair100 I've actually had issues with this as of late. It seems as though you can only do it if you drag the file in from the right side of the tab. 
![ezgif-3-43787b743b64](https://user-images.githubusercontent.com/8879244/94278732-306df800-ff19-11ea-8243-8638acf45b24.gif)

Version 0.14.0.0. Not sure if this is exactly what OP is talking about, but if so then maybe this should be a bug instead? Otherwise I can raise a new ticket.

**Comment by yaichenbaum** [comment]
@generalguy41 Please open a new issue and if it turns out they are the same, we can merge them then.

**Comment by generalguy41** [comment]
@yair100 will do (EDIT: #1969) 
@asuetin Can you confirm that this is the same issue you're having?

**Comment by asuetin** [comment]
@generalguy41 Yes, seems like the same issue. I did manage to make the Move prompt appear but as soon as I let go of the LMB, the app crashed, so I though it was an extension of the original bug. I can't reproduce the crash in 0.15.0 though, just the weird prompt behavior.
