### ISSUE TITLE
I want to suggest some things

### ISSUE THREAD

**Issue by jean3x7** [files-community/Files#2050]
Hello. i want to suggest some things:

1. Middle Click in folder to open in new tab.
2. Drag items to Recycle Bin
3. Show drives usages in navigation pane (below names, progress bar)
4. Click and Drag to select items
5. Checkbox to selected item
6. Option to open folder in Windows Explorer
7. Option to drag item with modifier key to create link, copy or cut (alt, ctrl)
8. Drag tab to out of current window to create new window
9. Option to eject external drivers
10. Items colors like Finder in macOS
11. Pin tabs
12. Show what program/process is locking file to be deleted
13. Option to show folder size like in the files
14. Option to change folder icon (custom icon)
15. Regex Search (when its become available)

Remember that it are only suggestions, thanks in advance.

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
