### ISSUE TITLE
A little idea

### ISSUE THREAD

**Issue by Xakkef** [files-community/Files#2068]
I'm not good at English, So with the help of Google Translate. :]

1. Use Win+E Quick open FilesUWP, Originally used to open the Explorer, Custom shortcut keys are also OK;

2. Add bookmark function, Very important function, You can refer to the bookmarks of Google Chrome.

Thanks for watching.

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
