### ISSUE TITLE
Proposal: Make translation resources as dedicated add-ons

### ISSUE THREAD

**Issue by hez2010** [files-community/Files#2124]
**Describe the solution you'd like**
In general, the frequency of translation updates is higher than application updates, and it'll be better if translations are updated independently depart from the application.

In order to achieve this, translations can be published as "add-ons" just like "Windows localization experience pack", and it will enable files-uwp to fix/update/add translations without needs of republishing the entire application to Microsoft Store. Also, it will make users able to pick their favorite languages instead of preinstalling all supported languages.

See: https://docs.microsoft.com/en-us/windows/uwp/publish/add-on-submissions

**Comment by yaichenbaum** [comment]
As of now, most of the people translating the app do the translations at the end of each development cycle when the strings are changing anyway. Because of this, I don't think making them an add-on will provide any benefits.

**Comment by duke7553** [comment]
@hez2010 I like the thinking behind this idea. Because these resources are updated frequently, it would make sense to have the ability to ship them on-demand and out of band. We have a rapid release cadence currently, but resource packages would definitely be something to consider once the app leaves beta.

For reference purposes, can you find the docs for the structure of resource packages with MSIX? I looked but had no luck exploring how we would get started with this idea in the future.

**Comment by Jaiganeshkumaran** [comment]
No need. Add ons should be provided for features and not for strings. Also, the store will only download the language the user really knows so this has no effects.

**Comment by yaichenbaum** [comment]
@hez2010 After looking into it, an add-on will not give any additional benefits since it will require us to submit an update to the store and go through the same certification process as a regular update. If you have any additional feedback, please let us know by opening a new issue.
