### ISSUE TITLE
Add options for different Date formats

### ISSUE THREAD

**Issue by Leblayd** [files-community/Files#2207]
**Describe the solution you'd like**
I would like to see dates formatted as "2020-11-02 09:30:23".
To achieve this, I think the most flexible (and not too difficult) solution would be to allow advanced users direct access to C#'s date formatting.
Meaning, I want to specify the format as "yyyy-MM-dd HH:mm:ss".

**Describe alternatives you've considered**
If this custom format doesn't align with either the vision or the design, I'd just like to see more generic options.

**Additional context**
![image](https://user-images.githubusercontent.com/33326417/97858879-184f7c80-1d00-11eb-9c55-01a74aac6dfa.png)
This box could be expanded with the option "Custom". When selecting it, a text input field would appear.
By default, this field would contain the format that is used by the "Application" setting (which seems to be "dddd, MMMM d, yyyy.").
When editing it, it would get validated on keypress. If the format is valid, it'd show an example date in that format. If incorrect, it could fall back to using the "Application" setting.

Additionally, [the Wiki page](https://github.com/files-community/Files/wiki/Date-formats) should be expanded with a detailed description that should match [the table near the top of this page](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings).

**Comment by TheOnlyTails** [comment]
Is this issue still active? I'd really like to see this feature in Files!

**Comment by Adam-Kay** [comment]
I would like the date format to simply folow the format that I have outlined in my system settings. My computer is set to English (US) but my date is set to YYYY-MM-DD, or ISO Standard. But in Files, the date format is MM/DD/YY with AM/PM for the 12 hour clock, which is very confusing for me not only because I live in Europe but also because everything else on my PC uses the correct date/time format as outlined in my system settings.

![P2APhzsmT9](https://user-images.githubusercontent.com/10010491/125314050-c13d8500-e32d-11eb-8fdd-85194e9a83b5.png)

![ApplicationFrameHost_Dki6swt2eE](https://user-images.githubusercontent.com/10010491/125314053-c3074880-e32d-11eb-9ef5-6d1c5a0f141c.png)

**Comment by yaichenbaum** [comment]
Closing for now as Files now has support for multiple date formats.
