### ISSUE TITLE
Files app opens MediaInfo for .mp3 files despite the fact that default app for this extension is Foobar2000

### ISSUE THREAD

**Issue by tehwolf1337** [files-community/Files#2299]
**Describe the bug**
Files app opens MediaInfo for .mp3 files when I double click it or press Enter despite the fact that default app for this extension is Foobar2000.

**To Reproduce**
1. Open Files app
2. Double click or press Enter on any selected .mp3 file

**Expected behavior**
Foobar2000 should be opened

**Screenshots**
![изображение](https://user-images.githubusercontent.com/73467140/98738611-a71f6180-23b0-11eb-8f63-d8870efd242f.png)
![изображение](https://user-images.githubusercontent.com/73467140/98738685-c4543000-23b0-11eb-86d5-367635d69eca.png)

**Desktop:**
 - OS Version: Windows 10 20H2 19042.610
 - App version: [v0.20.0]

**Additional context**
In the context menu list of both Windows Explorer and Files app for .mp3 files the first item is "Play in Foobar2000" and the second one is "MediaInfo"

**Comment by ElbowBaggins** [comment]
Hi, I also had this issue and was actually able to get `foobar2000` to behave as desired. The fault does not lie within `Files` _per se_. There seems to be a complicated interaction happening here mostly between `Windows`' file associations system, the UWP App subsystem, and `Explorer`. It just happens that `Files` is exposing what is either an outright bug in `Windows`, _or_ we've every one of us misinterpreted how this functionality is intended to behave. In any such case, I'm going to do my best to outline _**Don't Choose Your Own Adventure: Undocumented Registry Keys Edition**_. Apologies in advance.

### The Problem

`Files` is unable to `Open` files associated to `foobar2000`. `Open with...` _does_ allow me to successfully open the file with `foobar2000`, however, but repeat usages of this functionality result in the _Always open with_ checkbox not retaining the selection. Curiously, using `Open with...` from `Explorer` results in the checkbox _actually being checked_. So our selection actually _is_ being retained, somewhere! The regular `Open` (and double-click) work correctly in `Explorer` as well and _do_ respect the file associations we've selected. :rage4:

### So what gives?

Firstly, it _does_ appear that `Files` possesses some slightly wonky behavior with regard to launching other applications, be it from opening them directly or via an associated file. I suspect this is a UWP limitation, fair enough. I, too, had the _exact_ same behavior as noted by @tehwolf1337, down to the weirdly quiet log file. I did not get the opens-in-the-wrong-app behavior but I don't have any other associations that it could possibly try to use so this may be immaterial. I had `foobar2000` installed in `C:\Program Files` at the time.

Suspecting some kind of UWP funkiness, I removed the standalone version of `foobar2000` and installed the Microsoft Store version. Upon attempting to `Open` a once-again-associated-to-`foobar2000` file, part of my suspicion was confirmed.

```
2021-12-29 07:10:18.2067|INFO|Connection_RequestReceived|Argument: LaunchApp
2021-12-29 07:10:18.2497|INFO|StartSTATask|Access is denied
  System.ComponentModel.Win32Exception (0x80004005): Access is denied
    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
    at FilesFullTrust.MessageHandlers.ApplicationLaunchHandler.<>c__DisplayClass3_0.<HandleApplicationLaunch>b__0()
    at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2021-12-29 07:10:18.5550|INFO|Connection_RequestReceived|Argument: LaunchApp
2021-12-29 07:10:18.5985|INFO|StartSTATask|Access is denied
  System.ComponentModel.Win32Exception (0x80004005): Access is denied
    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
    at FilesFullTrust.MessageHandlers.ApplicationLaunchHandler.<>c__DisplayClass3_0.<HandleApplicationLaunch>b__0()
    at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2021-12-29 07:10:18.9448|INFO|Connection_RequestReceived|Argument: LaunchApp
2021-12-29 07:10:18.9869|INFO|StartSTATask|Access is denied
  System.ComponentModel.Win32Exception (0x80004005): Access is denied
    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
    at FilesFullTrust.MessageHandlers.ApplicationLaunchHandler.<>c__DisplayClass3_0.<HandleApplicationLaunch>b__0()
    at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
2021-12-29 07:10:19.3152|INFO|Connection_RequestReceived|Argument: LaunchApp
2021-12-29 07:10:19.3577|INFO|StartSTATask|Access is denied
  System.ComponentModel.Win32Exception (0x80004005): Access is denied
    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
    at FilesFullTrust.MessageHandlers.ApplicationLaunchHandler.<>c__DisplayClass3_0.<HandleApplicationLaunch>b__0()
    at FilesFullTrust.Win32API.<>c__DisplayClass0_0`1.<StartSTATask>b__0()
```

This is the result of me trying to open a few different files, back-to-back, associated to `foobar2000`. Upon tracking down the location of the executable, `Windows Terminal` was also unable to launch it (Access Denied) but double-clicking it from `Explorer` worked as expected, once you told it to let you into the folder.

### An Inconsistency!

`Files` is perfectly able to `Open` files associated to other UWP apps, such as `Windows Terminal` (which it can even launch on its own perfectly fine), `Photos` and even downloaded apps like `PDF Reader by Xodo`. So, plainly, something _must_ be different about associations to `foobar2000`. Indeed, they are.

`Files` has no difficulty opening files that UWP apps _declare_ a compatibility for in their manifest. That is, if you click on that particular app in the file associations panel in `Settings`, there is already an entry for the relevant file extension upon installing the app. `foobar2000` seems to be the exception to this rule, I was unable to `Open` `.mp3` files I had associated via this method. It is possible that this is due to my system state being tainted by remnants of the standalone `foobar2000`. I can't speak to the validity of that statement, however.

### DeFaUlT aPpS

Ultimately this seems to come down to the ludicrous behavior of the Settings -> Apps -> Default Apps 'control panel' (PrefPane?) as well as the `Open with...` dialog.

In the Windows 11 UI, if you install `foobar2000` from the Store, it will declare a small set of reasonable extensions it is already associated to (if those extensions are not already associated). This is sensible enough, but what if you install a `fb2k-component` that introduces support for a new extension? Does that add the extension to Windows 11's list?

No. It doesn't.

I suppose this makes some sort of sense. Components obviously cannot modify `foobar2000`'s manifest, and it seems there is no extension mechanism for this.

### Well... can't you just... associate it?

No! You can't!

Well, you _can_, but this association only works in `Explorer`!

You can, technically, register a filetype directly to the executable file found in `foobar2000`'s package folder (within the WindowsApps) folder. Due to the way this is permission'd, UWP apps can't respect this association because they cannot open the folder. It doesn't seem to matter if `Files` is run as Administrator.

The reason for this appears to be that Windows actually creates the association registration _differently_ depending on if the app is a regular Win32 app or a UWP app. Unfortunately, Windows is unable to tell if a .exe you pick belongs to a UWP application, despite the fact that people obviously do this. As such, it creates a regular Win32-type association, which will confound any UWP applications that try to respect it.

The 'proper' way to register a filetype with a UWP application is to type the extension into the control panel and then pick the app from the "Open with..." prompt that it gives you. However, the app we want to associate to (`foobar2000`) _does not declare the extension I want in its manifest_ (.vgz in this case). As a result, _it will **never** appear in the picklist_. This is a Catch-22, obviously.

**There is _no_ current way in Microsoft's UI to create a proper filetype association to a UWP app that does not declare that extension in its manifest.** (Well, there's _one_, which I'm going to cover, but it's clearly not intentional.)

There is apparently a way for apps to declare a `*` type but I understood this to be inconsistently supported and kind of a half-measure.

Not all is lost, though. Despite Microsoft's insistence that this is **impossible**, you can, in fact, set the association up correctly via the Registry!

Essentially, you want to look in `HKEY_CLASSES_ROOT` for an extension you _know_ is associated correctly to a UWP app, and one that is associated to a Win32 app. Under those extensions' keys, you want to look at nested subkeys `shell`, `open`, and `command`.

Notably, the Win32-style associations have a value with a name something like `ExecutablePath`, and that's pretty much it. It's just `%EXECUTABLE_PATH% %1` (i.e. `foobar2000.exe %1`). Interestingly, I noted that `%EXECUTABLE_PATH%` doesn't necessarily refer to a _real_ path. The bits before the actual executable name appear to (sometimes?) refer to registry keys that ultimately contain data that resolves the real path. It's possible I misinterpreted this but I seemed to be able to modify them to launch other executables. Take that part with a grain of salt.

The real interesting stuff exists in the UWP-style associations. These are very significantly more complex, referring to the full internal name of the package in multiple values as well as other metadata that _needs_ to be valid. The lynchpin in this whole thing seems to be the `DelegateExecutable` value, which is a string value containing the `CLSID` of the UWP app you want to launch.

### Okay, Okay, So how do I _use_ this?

Easy! Do what I said earlier and create the association _the wrong way_. Then, examine a functioning UWP association and determine what the values _should_ be for whatever app you want to associate. Finally, replace the contents of the `shell`, `open`, and `command` keys for your desired extension with _these_ values. After finding some additional reference to this extension (.vgz in my case) in the registry _I_ just removed them. I don't know how proper that bit is, but it might not even be relevant to you. So.

Anyway, after this, I was simply able to double click on a .vgz file and `Files` had no problem launching `foobar2000`! Curiously, it also started appearing in the `Open With...` list for every single extension. Associating additional extensions this way actually creates the correct structure. (This is the _one_ way through the UI I mentioned earlier.) So, clearly, Windows actually _can_ (and **will**) do it. You just have to break it first.

### omg, tl;dr!!
Windows creates file associations in two different ways. Some apps don't play nice with this. While this is seemingly inconsequential in a purely Win32 environment, the more strict permissions of UWP apps can cause said apps to break when trying to respect these file associations. You can work around this by installing a UWP version of that app, if available, because UWP file associations are defined differently.

However, if that app's manifest does not contain the extension you wish to associate, it is impossible to create this association in the UI. Simply navigating to the UWP app's executable and associating it that way does not work, a Win32 association is created instead. However, if such an improper association is created, it makes enough of the proper 'skeleton' that it can be amended into the correct format.

If one examines a proper UWP file association they can copy that structure (by hand, unfortunately) into the Win32-style association. After deleting the Win32-specific data the association effectively becomes a 'proper' UWP association which UWP apps can respect _and_ it seems to make the app suddenly associatable with whatever you want.

### Conclusion
It doesn't look like this really comes down to a fault in `Files`. It seems to want to follow the definition in the registry to the letter, and if this is anything but perfect _Windows_ seems to just kneecap you. I'm honestly not sure how you guys can mitigate this from your end. Perhaps you could try to resolve a corresponding UWP app if the above-described failure to launch occurs, but this seems like something you shouldn't _have_ to do.

If Microsoft just gave us a "Show all UWP apps" checkbox in the `Open With...` dialog, this would be solved. At least for the `foobar2000` case. Big oof.

This might also be the same as #5309.

**Comment by Josh-65** [comment]
Is this still an issue in 2.3.11.0 or above?
