### ISSUE TITLE
have tested 16+ file apps, this is missing so much it's unbelievable 

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [files-community/Files#2308]
have tested 16+ file apps, 
this is missing so much it's unbelievable 

gonna put of the basic things the file apps have and dont have on
https://docs.google.com/spreadsheets/d/1ngT8No6MBY46QtB9o-45SmqOgH1c3fmzShcVDEt1mvE/edit#gid=0

you can add what uwp file preview has or doesnt on there
but it's missing so many basics that i think gonna wait 2-5 years before adding anything about this

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
