### ISSUE TITLE
Network folders pinned to sidebar are removed after disconnection from network

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#2316]
**Describe the bug**
Network folders pinned to sidebar are removed after disconnection from network.

**To Reproduce**
1. Open the app.
2. Pin a network folder to the sidebar.
3. Close the app, disconnect from network and reopen the application again.
4. The pinned network folders are no longer pinned to the sidebar anymore.

**Expected behavior**
Expect the pinned folders to stay pinned at sidebar unless the pinned folder is removed manually.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.630]
 - App version: [v0.20.0.0]

**Comment by TheGamesmenDev** [comment]
Similar to [#6860 ](https://github.com/files-community/Files/issues/6860) which relates to removable drives.
Came here to add this same bug/feature request - but in relation to a network folder favourite disappearing when not connected to the associated VPN... since Windows doesn't resolve network names over VPN you either need to lookup/memorise the IP to reconnect to the network share, or revert to Windows file explorer.

**Comment by AaronKatzin** [comment]
I'm experiencing the same issue.
Favorite folders that require VPN connection are removed from favorites after disconnecting from VPN.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #8767
