### ISSUE TITLE
Implement Everything

### ISSUE THREAD

**Issue by Martin-Hausleitner** [files-community/Files#2324]
https://www.voidtools.com/

**Comment by yaichenbaum** [comment]
@Martin-Hausleitner Can you please fill out the issue template?

**Comment by duke7553** [comment]
@Martin-Hausleitner We haven't heard anything back from you for 2+ days, and we typically close issues without a filled-out template after three days of inactivity. Please fill out the issue template and include a copy of your log file. Otherwise, we'll assume you resolved this and close this feedback report.
