### ISSUE TITLE
Copy/Paste multiple files crashes the app.

### ISSUE THREAD

**Issue by lucandrei** [files-community/Files#2360]
**Describe the bug**
The app crashes when you copy multiple files and try to paste them into another path/folder.

**To Reproduce**
1. Copy over 100 jpgs (i had over 6gb of data)
2. Try to paste them into a different drive

I have the lastest vers of Windows 10

**Comment by yaichenbaum** [comment]
@lucandrei Can you fill out the issue template to help us investigate the issue?

**Comment by duke7553** [comment]
@lucandrei We haven't heard anything back from you for 2+ days, and we typically close issues without a fully filled-out template after three days of inactivity. Please fill out the issue template and include a copy of your log file. Otherwise, we'll assume you resolved this and close this feedback report.
