### ISSUE TITLE
The app seems too slow to load please make the loading performance better

### ISSUE THREAD

**Issue by fisforfaheem** [files-community/Files#2434]
I would mean a lot make it as fast at native explorer

**Comment by yaichenbaum** [comment]
@fisforfaheem Can you please fill out the issue template?

**Comment by duke7553** [comment]
Thanks again for your feedback. 

We remain committed to improving the performance of Files, but since we didn't hear from you on this topic for 3+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this.

**Comment by fisforfaheem** [comment]
ok, i have seen some speed improvements

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
