### ISSUE TITLE
Issue's with opening media in vlc via files preview 

### ISSUE THREAD

**Issue by RikKoedoot** [files-community/Files#2485]
**Describe the bug**
When opening media in vlc (windows store version) via files preview the media won't load in vlc, it does load in windows explorer

**To Reproduce**
See the video in the zip

**Expected behavior**
the video should open in vlc 

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: win 10 20h2 19042.630
 - App version: 0.23.1.0

**Log file**
included in the attached zip

[bug report.zip](https://github.com/files-community/Files/files/5612756/bug.report.zip)

**Comment by treneth333** [comment]
I've seen it have this problem before, sometimes reinstalling VLC will fix the problem.
But when some people continue to have difficulties, VLC is usually replaced by another MP4 player. Sometimes users will completely uninstall VLC so that there's no clash on what program is supposed to play the MP4 by default.

I'd start there personally, hope this helps 😁

**Comment by yaichenbaum** [comment]
@rickkode Is this still an issue in v0.23.1? I can't reproduce it on my end, so it may have gotten fixed.

**Comment by rickkode** [comment]
Yep, it still occurs for me, even after reinstalling vlc. Keep in mind it's the uwp version of vlc and not the x86 version.
