### ISSUE TITLE
Custom Folder shortcuts in Sidebar, file-preview instead of Icons

### ISSUE THREAD

**Issue by Cloudwires** [files-community/Files#2525]
1. Request: Possibility to place custom shortcuts in the sidebar (ex. custom project/music folders/ cloud storage links

2. Request: Instant File display: right now, content of folders loads with a delay, just like a browser would do. That's annoying, especially when browsing through large folders or navigating quickly between folders.

3. Request: File-Preview instead of File icons of several design/Document/image file-types such as Photoshop .psd, PDF, DNG Affinity Designer and Illustrator etc. - basically just like in mac os

4. Request: place "new folder" as Icon in navigation pane with the other icons (forward, backward), instead of hiding it behind the "new" menu - basically, just like in mac os

Cheers.

**Comment by yaichenbaum** [comment]
1. Merging with #1607.
2. This is due to the outdated DataGrid control, there is an issue on the WinUI repository regarding a new control that will solve this issue. In the meantime, we are considering other layout modes that won't have this issue.
3. Can you open a new issue for this?
4. We used to have it like this but the feedback we got that it was confusing, if you feel differently, please open a separate issue for that so we can gather feedback again.
