### ISSUE TITLE
Comfortable on a regular PC without a touch screen

### ISSUE THREAD

**Issue by dkostarnov** [files-community/Files#2593]
Make PLEASE the option to decrease the height of the file selection in ListView mode. At the moment it is not convenient to use Files with a mouse because of this. Also, it is not convenient due to the fact that you have not done empty space where there is no column. This is also very important. And lastly, when dragging a file, I drag a whole line. It's not comfortable. It would be very convenient if you did it like in a regular Explorer. That is, when dragging, display the file's thumbnail. I see that lately you have only been doing fixes and very rarely add something new. But these 3 reasons why Files are not comfortable on a regular PC without a touch screen are very important and I hope that in the near future you will fix it

**Comment by yaichenbaum** [comment]
@dkostarnov Thank you for your feedback, your idea about adding an option to decrease the height of items in the DataGrid is something we are tracking and planning to implement over here #1940. We are also looking for a solution to have empty space where there are no columns, #1040. I cannot reproduce the issue where thumbnails are not displaying when dragging items, but if it's still an issue in v0.21.1, please open a separate issue so we can track it.

> I see that lately you have only been doing fixes and very rarely add something new.

You may have noticed a slight decline in new features over the past couple of releases, this is because we are getting Files ready to leave preview, you can expect to see a couple new features before then but the main priority at the moment is improving stability.
