### ISSUE TITLE
Enable us to open everything with just one click

### ISSUE THREAD

**Issue by szaimen** [files-community/Files#261]
**Is your feature request related to a problem? Please describe.**
Especially for touchscreens it would be nice beeing able to open every file/folder with just one click.

**Describe the solution you'd like**
This and other UWP apps are ment to be also used by devices with touchscreen, so I think the option to open files and folders with just one click would be really nice.

**Describe alternatives you've considered**
Maybe for this also selecting through pulling would make sense?
![image](https://user-images.githubusercontent.com/42591237/67972677-70e0cb00-fc0f-11e9-888c-32eba8f06274.png)

**Additional context**
In file explorer the option to open everything with just one click can be found in file explorer settings:
![image](https://user-images.githubusercontent.com/42591237/67972780-a2599680-fc0f-11e9-864f-8d5b8bdbb534.png)

**Comment by yaichenbaum** [comment]
This is great feedback, I see three options we could have -
- An option to open files and folders with one click with mouse input and of course touch as well.
- An option to open with one click **only** on touch.
- The default which would be the current behavior that requires clicking twice.
Does this cover everything or is there anything else to keep in mind?

**Comment by szaimen** [comment]
@yaichenbaum I think your list is quite complete. I am just missing the option to select files and folders through pulling. This is important for touch input since you cannot use the shift button to select files/folders if the keyboard isn't available. And you probably shouldn't be forced to use the shift and/or ctrl key imho.
Maybe these ribbon options from file explorer could also be useful for that: 
![20191108_014035](https://user-images.githubusercontent.com/42591237/68439701-e7aa3500-01c8-11ea-87dd-34bc65b97c5c.png)

**Comment by yaichenbaum** [comment]
@szaimen That should be tracked in a new issue. I believe that #94 will work on touch when implemented.

**Comment by szaimen** [comment]
Thanks for pointing to #94, I must have overseen it.
For the additional ribbon options I opened:
https://github.com/duke7553/files-uwp/issues/274

**Comment by hez2010** [comment]
I think it needs a new approach to select files. (for example, long-press to enter select mode)
Otherwise there'll be conflict between opening files and selecting files.

**Comment by Jaiganeshkumaran** [comment]
@hez2010 In that case we can use hover to select.

**Comment by yaichenbaum** [comment]
If a user has this option turned on, they will need to use ctrl + click to select a file. Another option for the user will be to use the selection rectangle when it's implemented.

**Comment by Jaiganeshkumaran** [comment]
Why not hover? File Explorer uses hover for selecting if the user has the option to use single click turned on.

**Comment by jayasio** [comment]
Here's my opinion on the implementations for the actions, would this work?

| action | double click | single click | touch |
|--|--|--|--|
|open|double click|single click|touch|
|options|right click| right click|long press (better when displayed in space between navigation and search buttons instead of context menu)|
|single select (no need for this- no options are exposed while selecting in desktop use case; all options are in context menu)|single click|hover (or ctrl + single click)|long press (this way both selection and options are handled by single action)|
|multiple select|ctrl + single click / rectangle|ctrl + single click (as in win32 explorer) / rectangle|long press (then continue to select multiple by single touch)|

I remember from somewhere that the decision to remove the ribbon from the old design was because there was no need for it since everything was available through the context menu. The single-file select use case is redundant (except for times when the user needs to select multiple files ie. multiple select), I think.

**Comment by emvaized** [comment]
I think there must be checkbox in the top left corner of icons, that appear on hover and allow to select the file.
In standard File explorer there is such an option indeed:
![screenshot](https://user-images.githubusercontent.com/37851576/93419617-f87e0980-f8b5-11ea-91c7-edb57f73fe0d.png)

**Comment by emvaized** [comment]
I would love to see an option for single click to open on desktop. 
This is also good for people with physical injuries, for whom it is difficult to quickly double click.

**Comment by seltinusjulio** [comment]
> I think there must be checkbox in the top left corner of icons, that appear on hover and allow to select the file.
> In standard File explorer there is such an option indeed:
> ![screenshot](https://user-images.githubusercontent.com/37851576/93419617-f87e0980-f8b5-11ea-91c7-edb57f73fe0d.png)

It's good. But, I think we need a better design rather checkboxes.

**Comment by yaichenbaum** [comment]
@seltinusjulio You can already use ctrl + click to select more than one item.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2130.
