### ISSUE TITLE
Some Epic Suggestions for the Files App :O

### ISSUE THREAD

**Issue by DashCruft** [files-community/Files#2705]
I was wondering if you guys could make this awesome Files app a bit better with these suggestions :)

- Faster in processing
- If possible put an option for removing animations
- When selecting "Grid View" it changes the current grid of the folder your in. Not everywhere you go the default setting be like that.
- I've noticed that while previewing some files or pictures, it doesn't show up.
- Downloads folder organizes like the normal file explorer from the oldest to the recent (or an option for doing that in settings)
- Release the normal version(non-beta) with the normal icon Soon!!!!!

Hope these are helpful! Looking forward to see this rock and more people use it. Absolutely neat :)

**Comment by gave92** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one.

The following were recently implemented and will ship with the next public release: 🚀
- When selecting "Grid View" it changes the current grid of the folder your in. Not everywhere you go the default setting be like that. -> #530
- Downloads folder organizes like the normal file explorer from the oldest to the recent (or an option for doing that in settings) -> #530
