### ISSUE TITLE
Add a libraries section to the sidebar

### ISSUE THREAD

**Issue by infuriatedcodex** [files-community/Files#2709]
**Is your feature request related to a problem? Please describe.**
Pure feature request

**Describe the solution you'd like**
The Native File explorer has the ability for users to use Libraries for common folder types (Docs, Pic, Vids, Music).
This solution allows the logged on user to aggregate multiple folders into a single library which is great if you want to reduce pinning and creating shortcuts.

**Describe alternatives you've considered**
None suitable as yet.

**Additional context**
Currently the most used type for me are Pics folders. Having to create shortcuts in the current Pictures Library to places into OneDrive for example is not elegant and not a problem in the native explorer.

See native feature for context
[https://1drv.ms/u/s!Av1llRQPCCJGkBLSIbzcU95JCGGo?e=FdUyWv](url)

**Comment by duke7553** [comment]
@infuriatedcodex Just out of curiosity, are you wanting to create and list files from custom libraries, or just the 4 default libraries (Documents, Music, Pictures, Videos) from Windows Explorer?

Note to implementor:
The Windows Runtime API exposes [these](https://docs.microsoft.com/en-us/uwp/api/windows.storage.knownlibraryid?view=winrt-19041) default libraries which we should be able to display storage items from quickly because library contents are almost always indexed.

We could add a setting for these to be displayed in a node on the sidebar like explorer does.

**Comment by infuriatedcodex** [comment]
@duke7553 , hello mate ... yes exactly as you suspected, the 4 default Libs from Explorer for the reasons you point out to the project owner.

**Comment by TheAndyMac** [comment]
I would go further - I use Libraries extensively (with differences between machines used for different uses) and would need support for all my libraries on each machine. If the logic is done correctly to handle Libraries, it should then be able to recognise any Libraries setup by the user. Ideally, I would like to see them listed on the left-hand navigation tree in their own section, above the Drives section (much as Windows Explorer does). This feature, like in Windows Explorer itself, should be an option for users to be able to show or hide.

**Comment by InterruptDriven** [comment]
I will echo TheAndyMac's comments. Libraries are a often used facility when I am using Explorer. Having the ability to manage and use Libraries within Files would be "just the ticket" and I would jump to using Files immediately.

**Comment by yaichenbaum** [comment]
@InterruptDriven This issue should be resolved with #4134.
