### ISSUE TITLE
Feature request: Hide removable drives that are empty/non-populated/not mounted

### ISSUE THREAD

**Issue by BooBerry** [files-community/Files#2722]
**Is your feature request related to a problem? Please describe.**
I have a card reader connected via USB to my computer, which has multiple slots for SD, micro SD, CF, etc. memory cards. In Disk Management all these removable drive memory card slots have drive letters associated with them but when they are empty (non-populated) they do not appear in File Explorer's This PC section unless a memory card is plugged in. In Files both Home and the sidebar displays all empty/removable drives with no way to hide them.

**Describe the solution you'd like**
I'd like an option to automatically hide (non-populated) empty/removable drives that do have drive letters assigned to them in both Home and in the sidebar. This would allow Files to match File Explorer's behaviour in Windows 10.

**Describe alternatives you've considered**
I've tried to eject the drives in a vain effort to 'hide' them, which doesn't work of course.

**Additional context**
This should apply to all layouts and views.

**Comment by yaichenbaum** [comment]
Merging with #9170

**Comment by TCAtrevor** [comment]
I don't think that issue was the same as this one. This one was asking for an option that exactly mirrors an existing File Explorer option that is named "Hide empty drives". It is enabled by default but can be disabled, which I think would be the best case for Files as well. The issue you merged with was only asking for a specific behavior with the sidebar, but this feature would also apply to the Home screen. The feature does not hide empty optical or floppy disk drives; I believe it only applies to USB-like media. The use case for the feature is the situation OP described, where a card reader presents many empty devices to the system at all times while it is connected. I can elaborate further on File Explorer's implementation if needed, because I feel every previous request for this feature has just been misunderstood or people just did not understand what the original File Explorer option does.
![image](https://github.com/files-community/Files/assets/16995298/949aa6e1-3684-48e4-bd2d-c900db92271b)

**Comment by Josh65-2201** [comment]
They are the same request as the home page would have been included anyway and it was decided not to include this feature.
