### ISSUE TITLE
Setting Files as default file explorer

### ISSUE THREAD

**Issue by ziv-commentor** [files-community/Files#2853]
It's very frustrating to set Files as default file explorer using the registry. Please add an option in the setting to set it as default file explorer.

**Comment by yaichenbaum** [comment]
@ziv-commentor Unfortunately this is not possible because of the way Windows works. Explorer is the shell that powers the start menu, taskbar, control panel and much more. Replacing that with Files wouldn't work since Files is just a File Manager as opposed to a full shell. The most you can do is to follow the guide in how to redirect the command to launch File Explorer to launch Files instead.
