### ISSUE TITLE
Scroll speed is too slow

### ISSUE THREAD

**Issue by tony-ze-yi** [files-community/Files#3062]
**Is your feature request related to a problem? Please describe.**
The scroll speed for some reason is quite slow compared to other apps, eg. Settings

**Describe the solution you'd like**
A way to adjust the scroll speed.

**Describe alternatives you've considered**
I've considered changing the scroll speed in settings but it makes other scrolling tasks (eg. webpages) too fast.

**Additional context**
Windows 10 Pro Desktop

**Comment by gave92** [comment]
Thanks for this feedback, we're already working to improve this -> #3045

**Comment by yaichenbaum** [comment]
@tony-ze-yi The scroll speed is a limitation with the DataGrid control we are using, the good news is that Microsoft is working on a new DataGrid control that should resolve this issue.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
