### ISSUE TITLE
Moving folder with hidden files inside results in lost files

### ISSUE THREAD

**Issue by m4lebranche** [files-community/Files#3140]
**Describe the bug**
I moved (cut and paste) one of my folder with hidden files inside of it to my other hard drive. The folder is successfully moved, but to my surprise the hidden files inside of it are gone completely. Tried using recovery tools and stuff to restore the lost files to no avail. Undoing does not seem to bring the lost files back either (I  may have reopened the files, hence why the undo procedure no longer works)
 
**To Reproduce**
Have a folder with hidden files inside of it
1. Cut the said folder via ctrl+x or context menu
2. Paste it in some other directory
Hidden files inside of the folder are now gone

**Expected behavior**
Hidden files should be moved accordingly with folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2
 - App version: v1.1

**Additional context**
After I encountered this weird behavior, I tested and successfully replicated it multiple times. This may be critical since it can cause a data loss.

**Log file**

**Comment by gave92** [comment]
This should be fixed with #3030

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available and reopen if this behavior continues to cause data loss after updating.
