### ISSUE TITLE
Add option to choose home directory

### ISSUE THREAD

**Issue by dennisroche** [files-community/Files#3207]
**Is your feature request related to a problem? Please describe.**
I frequently open the user home directory, e.g. `C:\Users\{Name}` or `~`.

**Describe the solution you'd like**
Change `Home` to go to user home directory instead of the dashboard...  or provide an option in settings to disable the dashboard.

**Describe alternatives you've considered**
Bookmarks as described in https://github.com/files-community/Files/issues/3150 would also allow for this access pattern. 

**Additional context**
The contents of the current dashboard isn't very useful as I can access the `Folders` and `Drives` from the sidebar. `Recent items` could also move into the sidebar as suggested in https://github.com/files-community/Files/issues/2718

**Comment by winston-de** [comment]
What about having a Json file of "shortcuts" that the user can set for use in the path bar? Something like this:
```json
[
  {
    "Name": "Home",
    "Path": "%userprofile%"
  },
  {
    "Name": "importantfolder",
    "Path": "D:/folder/folder/important/"
  },
]
```

Also, I know this isn't the solution your looking for, but for the time being you can type `%userprofile%` in the path bar to get to your user folder.

**Comment by gave92** [comment]
Is it not enough to pin the user folder to the sidebar?

**Comment by marcellarius** [comment]
I was disappointed to see this wasn't an option.

As a primarily Linux and macOS user, the clumsy way Windows handles the home directory, and its inconsistent navigation (go up taking you to 'This PC' or 'Desktop' rather than real FS location) were some of the reasons I want to use a different file manager.

Pinning to the sidebar would be acceptable if: 

 a) we could reorder the items, and
 b) we could set aliases

But honestly I'd love a setting that let us have the "Home" link just go to %userprofile% instead; and maybe introduce something like "This PC" instead for the existing view.

**Comment by yaichenbaum** [comment]
We don't have plans to let users choose the home directory as we treat the home page as a directory of it's own, however, #6478 will allow you to remove the home page from the sidebar.
