### ISSUE TITLE
add actions somewhere depending upon contents of folder

### ISSUE THREAD

**Issue by mrcoder991** [files-community/Files#3265]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when lets say on recycle bin i recycle bin there should be an option for emptying it

**Describe the solution you'd like**
like recycle bin there should be optimization of folder according to the contents like if that folder contains videos then there should be option at top or in context menu or at bottom for play, play all, play with and such stuff just like it  
![image](https://user-images.githubusercontent.com/66244185/105634760-bb3e0f80-5e85-11eb-9c42-029e2dadf905.png)
and this 
![image](https://user-images.githubusercontent.com/66244185/105634795-dc066500-5e85-11eb-9f2e-ad0a27a85e61.png)
and this 
![image](https://user-images.githubusercontent.com/66244185/105634838-ffc9ab00-5e85-11eb-8710-81ad83ac4b2c.png)
you can also add some extra features like previewing temporary music or video or a document in thumbnail or in case of music like android listning it before actully opening a app for that

**Comment by tgrelka** [comment]
My original comment from #3883:

Seeing how the action bar below the address bar has a lot of free space, I think a redesign of the buttons and the overflow menu leads to usability improvements.

I tend to use New and New Pane quite often, not always reaching for the shortcuts though, especially since both are three-stroke-shortcuts. I’d suggest placing these buttons next to the Search and Toggle Preview Pane buttons.
I’d also like to see the open in Terminal button there, I haven’t found a shortcut for that one yet.

I believe this can be improved even further: The New Tab and New Window buttons can stay in that overflow menu, for all I care. But given how the New Tab button is already placed at a different spot, one where it makes sense from a usability point of view - in the tab bar, maybe consider adding the/a Copy Location button to the addres bar, to the side of it or only show it when the bar is selected, like the clear button. Something like this is common practice in many web apps, even GitHub itself has this, if you click the green ↓Code button in any repository, any of the links will have a Copy To Clipboard action right next to them.

Overall, the overflow menu seems a bit all over the place right now, especially since the dual-bar design (address bar and action bar) leaves a ton of free room for two more buttons without adding much clutter.

I might suggest a smart overflow menu which places more and more of the options in the action bar as the window grows bigger / hides them as the window shrinks. That way, clutter will be low when the window is small, but usability will be improved as the window gets bigger.

The Toggle Preview Pane may make more sense down in the Display Options menu at the bottom of the window, and personally I’d have the search button at the very right, with the expanding search bar pushing the other items to the side or overlaying them.

**Comment by yaichenbaum** [comment]
Merging with #2922.
