### ISSUE TITLE
La sincronización con onedrive no se muestra correctamente.

### ISSUE THREAD

**Issue by dconstanti** [files-community/Files#3289]
Los ficheros no muestran el estado correcto con onedrive. Tengo ficheros que salen como "en la nube" cuando los tengo sincronizados en local.

**Comment by yaichenbaum** [comment]
@dconstanti We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.

**Comment by ghost** [comment]
Hi! I opened a new issue. I don’t know how to reopen an issue.  Thnx in advance. Daniel Constantí Sánchez De: Yair yair100: miércoles, 27 de enero de 2021 5:45Para: files-community/FilesCC: dconstanti; MentionAsunto: Re: [files-community/Files] La sincronización con onedrive no se muestra correctamente. (#3289) @dconstanti We need a little more information from you in order to investigate this issue, please reopen this issue once you have filled out the issue template.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
