### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by Tech-How** [files-community/Files#3308]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I think it would be a nice polish to the fluent design system if the app had smooth scrolling, just like Microsoft Word has.

**Describe alternatives you've considered**
None.

**Additional context**
Version 1.1.0.0
Video: https://user-images.githubusercontent.com/76794507/105916687-51e20c00-5fff-11eb-87e3-84f22481ebd2.mp4

**Comment by yaichenbaum** [comment]
@Tech-How Thank you for opening this feature request, I would like to point out that the grid view layouts already have smooth scrolling. The details layout doesn't have smooth scrolling because of some limitations with the DataGrid control used in Files, the good news is that WinUI is going to be building a new DataGrid control. I am linking the proposal here so you can add your request for smooth scrolling, and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
