### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by iKatsuo** [files-community/Files#3352]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem.

**Describe the solution you'd like**
A shortcut for opening the app would be great, I normally used Win + E when I was using the predetermined file explorer but now that I'm using Files, I'm missing a shortcut to open the program.

**Describe alternatives you've considered**
I don't know if there's an alternative to the feature I just proposed.

**Additional context**
There's no additional context needed.

**Comment by glitchcodes** [comment]
Follow this documentation:
https://files-community.github.io/docs/#/articles/replace-file-explorer

This replaces Win+E to open Files instead of File Explorer and most other things that uses File Explorer.
Although, this isn't perfect. Opening downloaded files from your browser still opens file explorer.

**Comment by gave92** [comment]
You can set WinE to open files!

https://files-community.github.io/docs/#/articles/configure-win-e
