### ISSUE TITLE
please add these features to the app.

### ISSUE THREAD

**Issue by kleuton05** [files-community/Files#3534]
1. toolbar, with copy, paste, cut shortcuts ...
2. sliding adjustments of the viewing modes.
3. add a contor around the file icons.
![untitled png 3ed18a7bae81b1bcbb2d082228294c09](https://user-images.githubusercontent.com/51864325/107655399-4f6bed00-6c62-11eb-930c-063449d72dbf.png)

**Comment by yaichenbaum** [comment]
@kleuton05 Thank you for opening this issue. We usually expect users to fill out the issue template when reporting a bug or submitting a feature request, it would also help if can you split each feature request into its own issue so they can be worked on indecently.

**Comment by R3voA3** [comment]
1. Please don't. We already have this clutter in the Explorer. Copy and Paste are accessible via context menu and keyboard shortcuts. However, it would make sense if user is using a touch screen or is using the tablet mode.

2. Yes, good idea

3. Contour looks nice and adds some depth. It also indicates where the user can click to for example open the content menu for the folder instead of a file. However, I think it should be optional.
