### ISSUE TITLE
Home drives are not refreshed after disk size changes

### ISSUE THREAD

**Issue by osieltorres** [files-community/Files#3593]
**Describe the bug**
The "Home" drives shortcuts are not being refreshed after disk size changes

**To Reproduce**
1. Go to Files app.
2. Click on any disk and remove/add files to it.
3. Go back to "Home" pane.
4. The disk size is not refreshed after the changes.

**Expected behavior**
The disks size to be automatically refreshed after each operation inside them.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.804]
 - App version: [v1.2.3.0]

**Additional context**
After few minutes without refreshing the disk size, the app goes blue blocked and crashed.

**Log file**
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5989823/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/5989825/debug.txt)

**Comment by gave92** [comment]
Merging with #2242

**Comment by gave92** [comment]
@jakoss could you take a look at the last stacktrace in the posted log file?

**Comment by jakoss** [comment]
Seems like there's an issue loading string from property `Section` in `FileProperty`. It's not used anywhere, but it shouldn't be serialized anyway, since it's a calculated property:
![image](https://user-images.githubusercontent.com/3933348/108110439-8a6f8580-7093-11eb-988d-cb9d42ab0e0c.png)

I think that adding `[JsonIgnore]` to this property (and the `Name` property to be safe) should solve that issue. But i'm not sure about the cause of that. Seems like `GetLocalized()` returns some weird string that cannot be serialized.

That said - it shouldn't be cause of the original issue, since it's in try/catch block. Failure in saving to persistent cache shouldn't have any effect on the rest of the app
