### ISSUE TITLE
Can change the order of the items in lateral panel

### ISSUE THREAD

**Issue by dieggono** [files-community/Files#3654]
**Is your feature request related to a problem? Please describe.**
I can't reorder the items I add in the lateral panel

**Describe the solution you'd like**
I want to drag and drop Items in lateral panel.

**Describe alternatives you've considered**
Quit and readd all Items in the order I want

**Additional context**
I thing is a good idea that you answer all the people commenting the app in microsoft store, maybe disappointing people can reconsider get the app for a second chance in future versions of the app if they know that some problems will be resolved in future versions

**Comment by gave92** [comment]
This feature was implemented but is currently deactivated due to an issue with the WinUI library, I am linking it here so you can upvote the issue and hopefully increase the priority for Microsoft microsoft/microsoft-ui-xaml#3290.

Instead of readding the items you can edit this file:
"%LocalAppData%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalCache\PinnedItems.json"
