### ISSUE TITLE
App should automatically upload crash logs

### ISSUE THREAD

**Issue by sguergachi** [files-community/Files#3762]
**Describe the bug**
The app crashes for many diffrent reasons that would require a lot of time to report, for this reason most crashes are not reported. An automated crash log upload should be created to make it so hard crashes are reported without requiring users to do so.
**To Reproduce**
1. Open a USB device in a tab
2. Close File
3. Unplug USB device
4. Open File
5. App crashes and crash log isnt reported

**Expected behavior**
Crash log should be automatically uploaded for devs to manage and fix high frequency crashes
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version:
![image](https://user-images.githubusercontent.com/615386/109399307-1b562480-7910-11eb-998c-6998786d54e7.png)

 - App version: 1.3

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please upload the log file here so that we can understand your issue better. You can access it from Settings->About->Open log location. You can also find this file by going to `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6055326/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6055327/debug.txt)

`, you should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Comment by gave92** [comment]
Thanks for this suggestion. Crashes are already automatically reported using AppCenter. But a crash log without additional info (e.g. without steps to reproduce the bug) are often not that useful, that's why we appreciate it when people take time to create issues on github.

>Open a USB device in a tab
Close File
Unplug USB device
Open File
App crashes

Is this an issue you've being experiencing? Does it happen always or is it random? Does it make a difference if you disable the "continue where you left off" option in Files settings?

**Comment by sguergachi** [comment]
It happened once. I didnt have continue where you left off enabled. Not sure how to reproduce which is why I asked about the logs.

**Comment by yaichenbaum** [comment]
@sguergachi Please let us know it happens again.
