### ISSUE TITLE
Feature Request: Custom Themes

### ISSUE THREAD

**Issue by MudkipBanana** [files-community/Files#3809]
**Is your feature request related to a problem? Please describe.**
When using custom themes for windows, or custom themes in general, you are unable to manually change the color values of the Files app.

**Describe the solution you'd like**
I would like a hidden/experimental settings panel from which you could change the hex values of the app.

**Describe alternatives you've considered**
Another solution would be a config file from which you could change the hex values of the app.

**Additional context**
Edit: I know this is similar to #3176, but I believe this to not be a duplicate because in #3176, the author wants support for custom explorer themes, whereas I want a way to manually change the color codes via a gui or a config file.

**Comment by yaichenbaum** [comment]
@MudkipBanana This is something we have been exploring, this is a good chance for us to gather feedback on what users are looking for with custom themes. Here is some feedback we are looking for.
- Are you looking for the option to edit the brushes used inside Files?
- Are you looking for the option to edit font colors as well?
- Are you looking for a couple of themes to be built into Files?
- How will custom themes add value to your usage of Files?

**Comment by winston-de** [comment]
@yair100 
The main thing I would like with theming is the ability to customize the look of Files overall (margins, sizing, padding, etc.), not just the colors.

For example, I really dont like thin grid splitters, because I have big fingers so they're really hard to use on a touch screen. Since this is not an issue for most users, it doesn't really make sense to widen it in the Files codebase. It would be nice to have an easy way to customize the grid splitter template.

I think a solid way to do this would be to allow loading xaml resource dictionaries.
This gives a simple way to change the color scheme of Files, and also allows for more advanced configuration like re-templating controls.

This approach would, for example, allow me to increase the size of the grid splitters.

There are also theming utilities like [Fluent Xaml Theme Editor](https://github.com/microsoft/fluent-xaml-theme-editor) that could be used to design themes and generate the resources. Or, Files could have a built-in one.

I have a working prototype of this, if you're interested. 
You can add a theme dictionary to ```%userprofile%\AppData\Local\Packages\FilesDev_et10x9a9vyk8t\LocalState\themes```
https://github.com/winston-de/Files/tree/Theming

---
- How will custom themes add value to your usage of Files?

This would make it much easier to tailor Files to my own needs and address some personal pain points.

- Are you looking for the option to edit the brushes used inside Files?

Yes

- Are you looking for the option to edit font colors as well?

Yes

- Are you looking for a couple of themes to be built into Files?

I think a sample/template built in would be nice for reference.
Also, perhaps compact mode could be done by having a compact and standard theme installed by default.

**Comment by yaichenbaum** [comment]
@MudkipBanana @winston-de This issue has been approved for further development, at the moment, the plan is to detect custom resource files and load them in Files.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3890.

**Comment by weeebdev** [comment]
> This issue should be resolved with #3890.

When it will be released? Already created a theme, but I think the production version doesn't have this feature yet.

**Comment by yaichenbaum** [comment]
@weeebdev We don't have a release date yet.
