### ISSUE TITLE
Bug with right mouse click

### ISSUE THREAD

**Issue by vinimaurina** [files-community/Files#3886]
**Describe the bug**

I recently download the Files app, im love with this app, but the only bug i am suffering is, when i click on one archive by the right mouse bottom, the app just crash and i have to restart

**To Reproduce**
1. Go to one file 
2. Click with the right mouse bottom
3. See error

**Expected behavior**

The app crash and i have to restart the app

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 18363.1379]
 - App version: [v1.3.0.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

Yes, everytime this happen

**Log file**

[debug_fulltrust.txt](https://github.com/files-community/Files/files/6101767/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6101768/debug.txt)

Sorry by any english mistake, im still learning  :)

**Comment by gave92** [comment]
Thanks for this report!
- When the app crashes, do you get a notification saying "something went wrong" or does the app just close?
- Could you post a screenshot of the context menu the appears in Windows Explorer?
- Does the app crash also when right-clicking on a folder instead of a file?
- Does the app crash immediately after right clicking or does the app hang open for a few seconds before closing?

**Comment by arvindhmani** [comment]
I had the same issue when I right-clicked the Code.exe application:
![image](https://user-images.githubusercontent.com/15002753/110534687-5ebd4980-80ed-11eb-8f97-0062027931fc.png)

I did not experience this when I right-clicked an executable (although this behavior, too, was inconsistent):
![image](https://user-images.githubusercontent.com/15002753/110535423-41d54600-80ee-11eb-91cd-bf1312249238.png)

In the second case, there were some occasions when it crashed, and I noticed that the icons of these applications did not load. They had the default icon of a file (blank sheet of paper folded on the top right corner).

**Comment by corte** [comment]
Same here, right clicking anywhere makes the app stop responding and then closes the app.
On my case I was never able to even see the context menu. It crashes before showing it up.

If I disable an option in the settings that is something similar to "Move overflowing objects to a sub menu" it starts working. (I don't know the exactly text because my app is in Swedish which I also don't understand if my Computer settings are set to English).

**Comment by Ecpii** [comment]
I've had the same problem, and trying @corte's solution helped for a few right clicks, but it went back to the behavior of freezing on right click. The bug seems to happen for both folders and files indiscriminately. It seems that changing any of the options dealing with the context menu lets it work a few times (although inconsistently), but after a while of switching folders and clicking it returns back to the behavior of freezing the app and not displaying.

Oddly enough, the side panel context menu works 100% of the time, even if the folders may not be right clickable from their parent directory.

**Comment by Timur78** [comment]
This problem makes it very difficult to work(more than others)! Do you understand why this error appears? As soon as an update will be available to fix this bug.

**Comment by payambordbar** [comment]
@yair100 no, it fixed for me.

**Comment by yair100** [comment]
> @yair100 no, it fixed for me.

Thanks for the update!
