### ISSUE TITLE
Very slow performance on local network

### ISSUE THREAD

**Issue by Wanooo0** [files-community/Files#3903]
**Describe the bug**
Files app is very slow on local network.

**To Reproduce**
Brows some directories on local network

**Desktop (please complete the following information):**

OS Version: [Windows 10 20H2 19042.804]
App version: [v1.3.0.0]
Synology DS718+ | DSM 6.2.3-25426 Update 2

**Expected behavior**
A sliding little blue bar appears during loading of the directory content

**Video**
https://user-images.githubusercontent.com/77484326/110476983-ef425c80-80e2-11eb-831a-a03164f32041.mp4

**Comment by yaichenbaum** [comment]
@Wanooo0 Do directories load faster the second time you navigate to them?

**Comment by kwendel** [comment]
I have a similar setup (same Windows and Files version, different Synology NAS) and I'm experiencing the same issues.

To add to this issue:
- directories do not load faster the second time. I do have the option "Cache files and Folders..." enabled.
- directories with many child directories are not loaded in one go. This makes it feels slow compared to standard File Explorer.

**Comment by Wanooo0** [comment]
@yair100 @kwendel Hi guys.. same issues here, directories do not load faster the second time :(

**Comment by Avastgard** [comment]
I am facing the same issue as OP. Local folders take quite some time to open and once they are open, it takes more time to load the icons. Since most of my work is done accessing a server via VPN, it is impossible to use this app for actual work, as it takes even longer to load folders via VPN. Folders with many files take up to several **minutes** to load completely. Loading a second time or going back to the previous folder does not make it faster. I do have cache files and folders enabled.

Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   2.00 GHz
8GB RAM
Windows 10 64bits version: 20H2 19042.985 - Windows Feature Experience Pack 120.2212.2020.0
App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
@gave92 was this resolved in `main`?

**Comment by gave92** [comment]
I don't think so, stuff on network drives is still enumerated using the StorageFolder method (due to the fact that in Release mode only the fast method returns "Access denied")

**Comment by Avastgard** [comment]
Is this something you guys plan to fix on next version? I'm eager to use Files as my default file manager.

**Comment by megamorf** [comment]
I ran into this issue as well. Accessing a big file share is awfully slow. 
~680GB of data (86641 files, 12036 folders) with 870 folders being in the root of the share.

Neither the first nor a subsequent opening of the share compared to the regular explorer.exe performance. It took ages until Files had populated its pane with the root folder elements. After roughly 1min all folders starting with "A" were displayed.

Let me know how I can help you test possible improvements.

**Comment by yaichenbaum** [comment]
Merging with #4578
