### ISSUE TITLE
Allow customising context menus

### ISSUE THREAD

**Issue by mbeps** [files-community/Files#3966]
### Is your feature request related to a problem?

Being able to rearrange or completely remove certain entries in the context menus. This is useful as some apps add unnecessary entries to the context menus which clutter the menu. 

### Describe the solution you'd like

Include a new tab in the settings called _Context Menu_. Include a graphical solution for folders and different file types where the user can drag options or remove them. The removed items are stored in another place which can then be dragged and dropped if needed in the future. 
![image](https://user-images.githubusercontent.com/58662575/110772217-48310280-8253-11eb-8817-1961eaaa26b9.png)

### Requirements

-

### Files version

2.3.12.0

### Windows version

10.0.19043.2006

**Comment by gave92** [comment]
@mbeps I know the following does not fully cover your suggestion but you can customize the menu context items in Files by using any software that customizes the windows explorer context menu (a google search will suggest a bunch of those)

**Comment by mbeps** [comment]
@gave92 I don't really know of any good software. I use multiple utilities and registry tweaks.

**Comment by gave92** [comment]
>  I use multiple utilities and registry tweaks.
Yeah changes done by any of those should be affecting Files context menu as well as Explorer's

**Comment by josh-65** [comment]
I would like this feature too. It's kind of need at this point with all the options currently.

**Comment by mdtauk** [comment]
I would really like to be able to arrange, add and remove context menu entries.

You could include the standard options, and leave those fixed in position and order, but allow arranging of items in the rest of the menu.

As a thought experiment, I look at the File Explorer context menus, and see so much cruft.  Where a modern app like Files should give a cleaner and better thought out experience.

![image](https://user-images.githubusercontent.com/7389110/121271728-3398f080-c8bc-11eb-8842-7919288f5279.png)

**Comment by Tropix126** [comment]
It would also be nice to control whether the context menu was a CommandBarFlyout or not, and also animation timing/speed.

**Comment by winston-de** [comment]
> It would also be nice to control whether the context menu was a CommandBarFlyout or not, and also animation timing/speed.

Worth noting for this, if a ``CommandBarFlyout`` has no primary items, only secondary items, the CommandBar part will be hidden making it look and act like a normal menu flyout.

**Comment by mdtauk** [comment]
> It would also be nice to control whether the context menu was a CommandBarFlyout or not, and also animation timing/speed.
>
I would say this is going a bit too far in customisation.  The control respects the user's chosen settings for Animation.  Also normal users don't know the names of these kinds of controls, or the implication of changing it.

**Comment by yaichenbaum** [comment]
Regarding the speed issues, @winston-de found a way to reduce the amount of time it takes to show the context flyout.

**Comment by winston-de** [comment]
> Regarding the speed issues, @winston-de found a way to reduce the amount of time it takes to show the context flyout.

Yes, we can show the menu immediately with the built-in items, then lazy load the shell items.

**Comment by winston-de** [comment]
I think the biggest hurdle with implementing this is shell items. In order to add settings for shell items, we have to have the id for the shell item. But in order to get the id, the menu must be invoked for an item, which would make it hard to show in any kind of settings menu.

A possible solution to this would be to add a menu item to "edit menu items". When invoked, a content dialog would be shown that shows all the items, with context menu options to pin/unpin items, move them to the overflow menu, or hide them. Since the shell items would already have been retrieved, getting the id of the invoked item, storing it, and hiding it in the future would be relatively simple.

**Comment by dftf-stu** [comment]
Yes, being able to customise this would be great!

As an example, this is what I see when I have clicked on a random folder containing music files:
![FilesApp_OverflowSubMenu](https://user-images.githubusercontent.com/83965343/170691486-4c729883-b086-4f73-952f-ea22529808c0.png)

I'm not interested in having "Add to Windows Media Player", "Play with Windows Media Player" or "Cast to Device" at the bottom.

I'd prefer to just have "7-Zip", "WinRAR" and "Scan with Microsoft Defender" always at the bottom, as I'd use these far-more often for most folders.

Thanks

**Comment by yaira2** [comment]
We don't plan to support rearranging shell extensions because like it or not, users will complain if the changes aren't reverted when Files is uninstalled. However, we recently added support to control if shell extensions are displayed in the main menu or not.

We're also adding support for hiding some of the built in options like "edit tags", we'll be extending this list over time, but I think we can close this issue now.
