### ISSUE TITLE
Detail layout mode bug

### ISSUE THREAD

**Issue by SiRo24** [files-community/Files#4105]
**Describe the bug**

**To reproduce**
1. Go to '....'

**Expected behavior**

**Log file**
Please upload the log file here so that we can understand your issue better. 
* You can access it from Settings->About->Open log location. 
or 
* `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 
 
You should see a file in this directory called debug.txt or/and debug_fulltrust.txt.

**Screenshots**

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

When a Folder's Layout mode is set to Detail, the scrolling is lagging after about every Second, which makes it quite choppy. 
The hover effects on the whole program are lagging in the same way, when the layout mode is switched to detail.

Files version: 1.4.1.0
Windows version: Windows 10 Home Insider Preview 21332.1000

**Comment by yaichenbaum** [comment]
@SiRo24 Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
