### ISSUE TITLE
Grid view: The textbox background in rename mode is transparent

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#4229]
In grid view, when you want to rename an item, the textbox background is transparent, it's visually annoying.

![Captura de pantalla 2021-03-22 205302](https://user-images.githubusercontent.com/61259627/112073547-1ffaab00-8b53-11eb-9755-6acaa216a452.png)

**Comment by yaichenbaum** [comment]
This is likely an issue with WinUI, can you open an issue on their repo?

**Comment by XPoppyX** [comment]
@yaichenbaum This was the response I received: _"this looks by design. Can you put the textbox in a flyout?"_

**Comment by yaichenbaum** [comment]
@XPoppyX Can you link the issue?

**Comment by XPoppyX** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/4626

**Comment by yaichenbaum** [comment]
@cinqmilleans Do you want to try to solve this?

**Comment by cinqmilleans** [comment]
@yaichenbaum I'll investigate.

**Comment by cinqmilleans** [comment]
@yaichenbaum @XPoppyX
1) I have a fix for this issue, but
2) I got a null error when trying to rename in grid view. I must activate 2 lines in comments. I don't know why this code is commented out.
3) Visually, it's better, but there is still a downward shift in the icon, not very harmonious. It would be necessary to use a modal, as to create a new folder. It is also more convenient with long names and easier to read because it is all on one line.
4) I'm waiting before committing, because of this comment problem.

Current code (GridViewBrowser.xaml.cs, line 200):
Popup popup = gridViewItem.FindDescendant ("EditPopup") as Popup;
TextBlock textBlock = gridViewItem.FindDescendant ("ItemName") as TextBlock;
// Popup popup = (gridViewItem.ContentTemplateRoot as Grid) .FindName ("EditPopup") as Popup;
// TextBlock textBlock = (gridViewItem.ContentTemplateRoot as Grid) .FindName ("ItemName") as TextBlock;

What works for me:
// Popup popup = gridViewItem.FindDescendant ("EditPopup") as Popup;
// TextBlock textBlock = gridViewItem.FindDescendant ("ItemName") as TextBlock;
Popup popup = (gridViewItem.ContentTemplateRoot as Grid) .FindName ("EditPopup") as Popup;
TextBlock textBlock = (gridViewItem.ContentTemplateRoot as Grid) .FindName ("ItemName") as TextBlock;

**Comment by yaichenbaum** [comment]
Can't you just change the background color of the TextBox?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #4674.
