### ISSUE TITLE
Network location on side bar isn't visible unless drive is mapped

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4247]
**Explain the bug**
I can't access/see devices on the network anymore as the network side bar option is gone.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6191509/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6191510/debug_fulltrust.txt)

**System Information**
 - OS Version: Windows 10 20H2 19042.870
 - App version: v1.5.0.0

**Comment by gave92** [comment]
It's not gone. Someone thought it was a good idea to hide it if no network locations are present -.-
To get it in 1.5 you can add a (fake) network location from file explorer.

**Comment by josh-65** [comment]
I think it should still show the network index stuff like file explorer does

**Comment by gave92** [comment]
Exactly

**Comment by FlowingSteve** [comment]
Did a winget ( love it ) - ran FILES - saw the network icon ( i had a mapped z drive already) then tweaked a bunch of setting, restarted and they were gone - can no longer see all the networked devices, mapped drive are fine , so is onedrive and sharepoint drives - gonna uninstall and reinstall - just an FYI since i am running a Windows Dev version

OsVersion                                               : 10.0.21354
OsBuildNumber                                           : 21354
WindowsBuildLabEx:  21354.1.amd64fre.co_release.210402-1630

**Comment by josh-65** [comment]
@FlowingSteve create a new issue for this as it not a relate or same issue

**Comment by josh-65** [comment]
Any update on this?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5082.
