### ISSUE TITLE
Folder table header has inconsistent coloring upon switching themes.

### ISSUE THREAD

**Issue by Tropix126** [files-community/Files#4370]
**Explain the bug**
When switching from dark to light mode and vice versa, the "Details View" table header changes color to either pure white or pure black, which then goes away upon hovering the mouse over it. This also appears to have an effect on the sorting arrows (for sorting by ascending/descending) present in the header, which persists until the app is relaunched.

**To reproduce**
1. Switch to "Details View" and open a folder.
2. Go into settings and change the app theme.

**Expected behavior**
The header should use the correct coloring upon the theme being switched.

**Logfile**
Not relevant.

**Screenshots**

https://user-images.githubusercontent.com/42101043/112924129-34035700-90d5-11eb-93e0-382384ff4a0b.mp4

**System Information**
 - OS Version: Windows 10 Dev (21332.1000)
 - App version: 1.5.0.0

**Additional comment**
None.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
