### ISSUE TITLE
Drag & drop Bug

### ISSUE THREAD

**Issue by inspiredscout** [files-community/Files#4571]
When using the Drug And Play function, it is not possible to transfer files to third-party applications such as browser or Discord. That is, it does not work like this to send files to other people through instant messengers

**Comment by CreepyCat225** [comment]
I'd like to add that it doesn't work with Adobe applications such as Photoshop consistently, works sometimes for me but not consistent enough.

**Comment by tlherysr** [comment]
I am having the same problem with browsers and any kind of my daily third party apps. I wish I know cs and fix this myself but it will take so much time :) I hope it will be fixed in a short time. This app is the most innovator app 👍🏻

**Comment by sujeendran** [comment]
I would like to add another problem with drag and drop is that when you start dragging a folder and hover over itself, it enters that folder and starts complaining its a subfolder of itself when dropped. The error is okay, but the expected behavior should be not to even try or completely restrict entering the same folder. 
It can also be nice if a user preference setting is available to toggle hover enter behavior.

**Comment by yaichenbaum** [comment]
@inspiredscout is this still an issue in v2.0.34?

**Comment by Talisman39ar** [comment]
@yair100 It still happens for me in 2.0.34 - for example trying to drag from Files into Sharepoint or Google Photos, the attempt is just ignored (using latest version of non-dev/canary Edge). Have to switch to File Explorer to get it to work.

**Comment by yaichenbaum** [comment]
Merging with #6941
