### ISSUE TITLE
Taskbar icon is misaligned

### ISSUE THREAD

**Issue by brendannoble** [files-community/Files#4729]
**Explain the bug**
The icon in the taskbar is misaligned with other icons, the bottom is a few pixels above the rest making it look off center.

**To reproduce**
1. Open Files
2. Check the icon against others in your taskbar

**Expected behavior**
The bottom of the icon should be aligned with the other icons in the taskbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/2664312/115940159-b9bcbd00-a45d-11eb-9f77-91ba2515740e.png)
![Untitled-1](https://user-images.githubusercontent.com/2664312/115940224-f2f52d00-a45d-11eb-900a-baf4ffb0942b.jpg)

**System Information**
 - OS Version: 
 
Windows 10 Pro
Version	20H2
Installed on	‎6/‎11/‎2020
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

 - App version: 1.5.0.0

**Comment by yaichenbaum** [comment]
It looks pretty aligned in the screenshot you shared, but perhaps the folder holder is causing it to look a little off.

**Comment by Rasmagoric** [comment]
It's just one pixel off to the top.  Here's how it looks corrected: 
![1px](https://user-images.githubusercontent.com/24687648/115996791-ab46e080-a5d8-11eb-93f0-0d523375d8e6.jpg)

**Comment by brendannoble** [comment]
That correction looks much better!

**Comment by skaldebane** [comment]
@yair100 Looking at the original assets, the icon is pretty misaligned. Look how much space is at the bottom compared to the top of the icon:

![image](https://user-images.githubusercontent.com/35589610/119536343-e297e100-bd80-11eb-9f8a-962814238907.png)

This image is what the browser shows as a preview of [this icon from the Assets folder here.](https://raw.githubusercontent.com/files-community/Files/main/Files.Package/Assets/Square44x44Logo.altform-lightunplated_targetsize-48.png) The transparent places are white in this preview.

EDIT: There's also an empty pixel on the left that isn't there on the right.
EDIT 2: I guess I'm a little too serious about the icon 😅 but I use this primarily instead of the original file explorer and it's unmistakably bugging me every time I look down

**Comment by yaichenbaum** [comment]
@Skaldebane This can be fixed by editing each icon that has the issue.

**Comment by Skaldebane** [comment]
I can do it - but I'd like to understand what do their names mean...
For example, in the icon above, it says Square44x44Logo...targetsize-48 and its resolution is 48x48. Does this mean I have to put a 44x44 in the center of a 48x48 canvas? And what about the others?

**Comment by yaichenbaum** [comment]
@Skaldebane Basically, this is something I am working on and I'll share the results when they are ready.

**Comment by yaichenbaum** [comment]
@brendannoble This issue should be resolved in `main`.
