### ISSUE TITLE
Add Ctrl+Shift+T hotkey to reopen last closed tab

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#4796]
**Is your feature request related to a problem?**
Oh no, I just closed my [very important content] tab, and I want to quickly reopen it.

**Describe the solution**
If there was a hotkey for this, I could just reopen the tab I just closed,

**Describe alternatives you've considered**
I could try to reopen the tab by navigating to the corresponding folder, but what if it's very deep in the structure?

**Additional comment**
How many tabs do we want to keep in the history? Should I be able to reopen a tab that was closed, five million tabs ago?

Also @yaichenbaum :)

**Comment by cinqmilleans** [comment]
@chingucoding @yair100 
This shortcut already works but is not visible.
I propose to add this choice in the contextual menu of the tabs and indicate the missing shortcuts there.
I can do it.

**Comment by marcelwgn** [comment]
That sounds reasonable to me since the feature already exists but is just not mentioned. @cinqmilleans Would you also like to update the documentation around this [here](https://github.com/files-community/files-community.github.io/blob/main/docs/articles/keyboard-shortcuts.md) (assuming @yair100 is fine with the proposed changes)?

**Comment by cinqmilleans** [comment]
ok for me.

**Comment by yaichenbaum** [comment]
@chingucoding This issue should be resolved with #4839.
