### ISSUE TITLE
Feature: Display "shield overall" indicating elevation is required

### ISSUE THREAD

**Issue by ADeltaX** [files-community/Files#4845]
Windows Explorer displays an overlayed tiny shield icon for executables that requires an elevation.
![image](https://user-images.githubusercontent.com/11020093/117223464-0618dd00-ae0e-11eb-9a21-af363a5d72be.png)

**Describe the solution**
The following function will let you know if an elevation is required for a given executable file path.

```cs
[DllImport("shell32.dll", EntryPoint = "#865", CharSet = CharSet.Unicode, SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)] private static extern bool IsElevationRequired([MarshalAs(UnmanagedType.LPWStr)] string pszPath);
```

Usage:
```cs
var isElevationRequired = IsElevationRequired(@"C:\Windows\regedit.exe");
```

@yaichenbaum

**Comment by ELowry** [comment]
Also, design-wise, it could be more interesting to have the shield be at the start of the file name instead of in the icon.

The main reason I suggest this is that in some cases, icons can be designed with slight variations (for slightly different file types for example), which can be covered up by this sort of design. On the other hand, the file name can be easily shifted left to make space for an icon without any loss of information.

**Comment by QuaintMako** [comment]
Should the shield be displayed in the properties icon as well?

![image](https://user-images.githubusercontent.com/110472580/229448929-61b46bac-f2fa-4c3d-a704-5deb132e0718.png)

**Comment by QuaintMako** [comment]
Do we want the colored shield like here :

![image](https://user-images.githubusercontent.com/110472580/229507810-59832928-7a8b-4a4c-a3a0-fc658d50886c.png)

Or do we want the glyph style shield like so :

![image](https://user-images.githubusercontent.com/110472580/229508742-7bf9063e-8773-4a54-9929-398da1bcf40a.png)

**Comment by yaira2** [comment]
I like the colored one

**Comment by QuaintMako** [comment]
> I like the colored one

I'll look into how to get it to work then! Thanks.

**Comment by yaira2** [comment]
@ADeltaX this feature has been implemented and will be included in one of the next feature releases.
