### ISSUE TITLE
Pin to start in overflow submenu when settings off

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4850]
**Explain the bug**
Pin to start menu is in a sub menu even when "move overflow items to sub menu" is off.

**Expected behaviour**
Should be out with the rest of them.

**Screenshots**
![image](https://user-images.githubusercontent.com/26977075/117373102-8ac53300-aec2-11eb-9276-a8e54c5991c8.png)

**System Information**
 - OS Version: Windows 10 20H2 19042.928
 - App version: v1.5,26

**Comment by cinqmilleans** [comment]
This bug is related to the ShowOnShift property
1) ShowOnShift is only used for PinItemToStart and UnpinItemFromStart.
2) The expected behavior of ShowOnShift is probably to show the command only if shift is pressed.
3) The real behavior of ShowOnShift is to show the command in More when Shift is not pressed.
4) Why only display commands with Shift? It's not intuitive and the user never will.
5) This bug is fixed by removing ShowOnShift initialization for these 2 commands. The behavior of ShowOnShift should be fixed, but it would no longer be used and would not have any impact.

**Comment by yaichenbaum** [comment]
@josh-65 This issue should be resolved with #4877.
