### ISSUE TITLE
Full acrylic theme

### ISSUE THREAD

**Issue by JotaRata** [files-community/Files#4944]
It is possible to have a theme in the future that achieves this effect from VS Code?

![imagen](https://user-images.githubusercontent.com/36273501/118578914-080e6480-b75b-11eb-8200-b74e604ed51a.png)

**Comment by Rasmagoric** [comment]
+1 I also have my vs code setup that way.
It would be cool as an option "full acrylic" but way less transparent than that screenshot.

**Comment by josh-65** [comment]
You could properly make one in https://github.com/files-community/Custom-themes

**Comment by winston-de** [comment]
As @josh-65 said, this is (mostly) possible to do with a custom theme. However, there are a few surfaces that are not possible to override with an acrylic brush.

![image](https://user-images.githubusercontent.com/59544401/118700582-afc17c00-b7c7-11eb-80e2-2fe97cc06247.png)

I'll add this theme to the custom themes repo, and also look into updating the remaining resources that currently can't be overridden with acrylic brushes so that they can be.

**Comment by Rasmagoric** [comment]
@winston-de wow, that acrylic themes looks great. Here's how it looks side by side with the acrylic visual studio:
![acrylic](https://user-images.githubusercontent.com/24687648/118732503-5e9aa200-b832-11eb-8368-fb046a534ae6.png)

**Comment by mdtauk** [comment]
> @winston-de wow, that acrylic themes looks great. Here's how it looks side by side with the acrylic visual studio:
> ![acrylic](https://user-images.githubusercontent.com/24687648/118732503-5e9aa200-b832-11eb-8368-fb046a534ae6.png)

Slight issue with the status bar, but an optional border along the top of it, would fix the grid being cut off - maybe the border only shows with the Acrylic theme chosen?

**Comment by yaichenbaum** [comment]
This issue should be resolved with https://github.com/files-community/Custom-themes/pull/14.

**Comment by Peter20130402** [comment]
how to download
