### ISSUE TITLE
Crashed when opening a specific folder in OneDrive by double-click

### ISSUE THREAD

**Issue by ZjzMisaka** [files-community/Files#5335]
**Explain the bug**
Crashed when opening a specific folder in OneDrive by double-click.

**To reproduce**
1. Open OneDrive folder.
2. Open a child folder by double-click which contains a lot of .mp4 videos.
3. Use [Ctrl + Mouse scroll up] to reload and arrange the video files and their previews.
4. Close the window and do 1-2 again.
5. The program crashed.

***But***
When I open the same folder by 
1. right-click the folder
2. click "open on new tab"
The folder will opened normally without any bug. 

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
[debug.txt](https://github.com/files-community/Files/files/6724057/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6724058/debug_fulltrust.txt)

**System Information**
 - OS Version: 
Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz   3.10 GHz
16.0 GB (15.8 GB 使用可能)
64 ビット オペレーティング システム、x64 ベース プロセッサ

 - App version: [e.g. v1.5.0.0] 

**Additional comment**
Does this problem happen again after restarting the app? Yes.

**Comment by gave92** [comment]
This issue should be fixed in latest code.

To verify I'm posting below 2 workarounds that were found for similar issues.

Workaround 1:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode

-------------------------------------

Workaround 2:

1. Disable these two settings (turn off caching) under Experimental

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)
