### ISSUE TITLE
I was trying to open a folder and suddenly files crushed

### ISSUE THREAD

**Issue by LeoCabelloP** [files-community/Files#5338]
**Explain the bug**
Write a clear description of what the bug is.

**To reproduce**
1. Go to '....'
4. See the error

**Expected behavior**
Write a clear description of what you expected.

**Logfile**
Upload the log file here for us to understand your issue better. 
- You can access it from Settings->About->Open log location. 
or 
- Copy the debug.log and debug_fulltrust.log from the following directory, and upload the files here.
`%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState` 

**Screenshots**
Add screenshots to help explain your problem if needed.

**System Information**
 - OS Version: [e.g. Windows 10 20H2 19042.804] (Press WIN + PAUSE/BREAK, use the copy button at the bottom)
 - App version: [e.g. v1.0] (In the app, go to Settings -> About, the version is shown at the top)

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app?

**Comment by gave92** [comment]
Hello, please add Files version to the description and upload the debug files but this issue should be fixed in latest code.

You can try 2 workarounds that were found for similar issues.

Workaround 1:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode

-------------------------------------

Workaround 2:

1. Disable these two settings (turn off caching) under Experimental

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)
