### ISSUE TITLE
The desktop folder cannot be opened by Files

### ISSUE THREAD

**Issue by Varorbc** [files-community/Files#5345]
**Expected behavior**
`Files ` instead of `Explorer` to open folders 

**System Information**
 - OS Version:Windows 10 20H2 19042.804
 - App version: v1.5

**Comment by gave92** [comment]
Hello thanks for this report. Could you add more details?

**Comment by Varorbc** [comment]
What more information do I need to provide?

**Comment by gave92** [comment]
Are you asking how to "replace" windows explorer with Files so clicking on a folder on the desktop opens Files instead of explorer?

**Comment by Varorbc** [comment]
Thank you very much, but why open my computer is still the windows explorer

**Comment by gave92** [comment]
Unfortunately it's not possible to open Files when clicking on my computer (and possibly recycle bin).

**Comment by Varorbc** [comment]
Is there a support plan?In addition, [replace-file-explorer](https://files-community.github.io/docs/#/articles/replace-file-explorer) can be used as a configuration option

**Comment by gave92** [comment]
If you really wish to do that, the reg files included below should do the trick but there may be undesired consequences (e.g you won't be able to access the control panel anymore).

All the usual warnings about registry editing apply, most notably:
- We take 0 (zero) responsibility for anything bad that may happen
- Take a backup of the registry before running this scripts and place it *on the desktop*

To do:
1. Extract the two files from this archive [SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip) and place them *on the desktop*
2. Run `SetFilesAsDefault_Bad.reg`

> In addition, replace-file-explorer can be used as a configuration option

Since a registry modification is needed, we're not currently planning to add this as a configuration option
