### ISSUE TITLE
Newtonsoft.Json.Serialization crash when entering folder

### ISSUE THREAD

**Issue by jkendall327** [files-community/Files#5346]
**Explain the bug**
Unhandled hard crash when entering new directories. Did not happen consistently, but occurred three times within ten minutes. The folders in question were 'large' -- either containing several hundred image files or nested subfolders. My layout mode is on 'Grid View (Large)'.

**To reproduce**
Open a large folder soon after app start with layout mode set to Grid View (Large).

**Log**
[debug.log](https://github.com/files-community/Files/files/6741552/debug.log)
I have redacted folder names from the log file for the sake of privacy.

**Expected behavior**
No crashes or a more graceful crash.

**System Information**
Edition	Windows 10 Home
Version	21H1
Installed on	‎13/‎02/‎2021
OS build	19043.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

Version 1.5.0.0

**Additional comment**
Problem did not reoccur when restarting app. Maybe because the directories were cached?

**Comment by gave92** [comment]
Hello, this issue should be fixed in latest version which is currently in beta.

You can try 2 workarounds that were found for similar issues.

Workaround 1:

1. Turn Off "Enable individual preferences for individual directories" in Settings > Files and Folders
2. Set Tiles or GridView layout mode

-------------------------------------

Workaround 2:

1. Disable these two settings (turn off caching) under Experimental

![image](https://user-images.githubusercontent.com/9673091/110851026-ce2f6680-82b0-11eb-8974-599e144ff399.png)

**Comment by jkendall327** [comment]
Thanks very much for the advice, I'll try it out.
