### ISSUE TITLE
Resizing of Colums not in a 1:1 ratio with mouse cursor

### ISSUE THREAD

**Issue by crashmit** [files-community/Files#5371]
**Explain the bug**
When I resize a column, the edge, I'm grabbing is not locked to my mouse-cursor but rather moves with 50% the speed or distance.
See the attached video:

https://user-images.githubusercontent.com/58466626/124397491-5e863100-dd10-11eb-860e-a8159efca7a7.mp4

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6760495/debug.log)

**System Information**
 - OS Version: Windows 10 21H1 19043.804
 - App version: 1.5.46

**Additional comment**
The column, I resize there doesn't need to be as wide to just display a ✔. This is how I discovered the bug.

**Comment by yaichenbaum** [comment]
@winston-de @gave92 do you think there is a way we can optimize the code for this?

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
