### ISSUE TITLE
New app icon does not scale beautifully at 125%

### ISSUE THREAD

**Issue by BreeceW** [files-community/Files#5488]
**Explain the bug**
When display scale is set to 125%, the new app icon has an unpleasant white stroke at the bottom.

**To reproduce**
1. In Settings, set display scale to 125%
2. Look at taskbar. Files icon is ugly
3. Look at Start menu app list. Files icon is ugly

**Expected behavior**
The icon should look good at all scales

**Screenshots**
![Files app icon on taskbar with ugly white streak](https://user-images.githubusercontent.com/18747724/126732499-9c95d98a-2487-4737-98c9-999ab8019d49.png)
![Files app icon on all apps list in Start with ugly white streak](https://user-images.githubusercontent.com/18747724/126732450-4f03b363-0ab2-4c77-9953-eac3e8c771da.png)

**System Information**
 - OS Version: Windows 11 22000.100
 - App version: 1.9.0.0

**Additional comment**
I believe the culprits are Square44x44Logo.targetsize-30.png, Square44x44Logo.targetsize-30_altform-lightunplated.png, and Square44x44Logo.targetsize-30_altform-unplated

**Comment by yaichenbaum** [comment]
This appears to only be an issue in dark mode.
Fyi @mdtauk @itsmichaelwest

**Comment by esibruti** [comment]
@yair100 I think we can close this

**Comment by yaichenbaum** [comment]
This is still an issue in `main`..

**Comment by mdtauk** [comment]
Does the 125 scale asset look ok when just viewing the files?

**Comment by yaichenbaum** [comment]
Yeah, as @BreeceW mentioned, it looks like it's the 30px assets that aren't scaling properly.

**Comment by mdtauk** [comment]
> Yeah, as @BreeceW mentioned, it looks like it's the 30px assets that aren't scaling properly.

I fiddled with it in Figma, got it exporting right now, not sure what the problem was, but it should be sorted now.
![Square44x44Logo targetsize-30_altform-lightunplated_theme-light](https://user-images.githubusercontent.com/7389110/130463782-7af48fcc-7ed3-4c21-a38e-033e87d1f907.png)
![Square44x44Logo targetsize-30_altform-unplated_theme-dark](https://user-images.githubusercontent.com/7389110/130463784-937b4fcb-55c9-4abd-850e-5c72d927fb84.png)
![Square44x44Logo targetsize-30_theme-dark](https://user-images.githubusercontent.com/7389110/130463785-8c409763-e02a-4e25-a3bf-bb37d0756a7c.png)
![Square44x44Logo targetsize-30_theme-light](https://user-images.githubusercontent.com/7389110/130463788-d3955122-fcc0-4532-b94d-93240f887fa2.png)

**Comment by yaichenbaum** [comment]
@BreeceW this issue should be resolved with #5907.
