### ISSUE TITLE
Ability to Use the Old File Manager Properties Window

### ISSUE THREAD

**Issue by KaiserCalm** [files-community/Files#5847]
### Solution/Idea

It would be nice if it was possible to access both the new and old (Windows File Manager) properties windows or to choose in the settings which one is preferred.

### Alternatives

Using Windows File Manager for the Properties Window.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Have the ability to open Windows File Manager's Properties window | Must |
| Make it possible to use both Property windows from the Context Menu | Should |

### Files Version

v1.5

### Windows Version

Windows 11 21H2 22000.132

**Comment by yaichenbaum** [comment]
@KaiserCalm thank you for opening this feature request. While we'd love to hear your use case, our focus is on building out Files to be a modern replacement for File Explorer rather than falling back to the old UI we are trying to replace. If we're missing options you're looking for, please let us know and we'll add them to the backlog of things to do 🙂

**Comment by KaiserCalm** [comment]
Thank you for the response. 🙂
