### ISSUE TITLE
Improve Selected Files on Hover

### ISSUE THREAD

**Issue by stanleyowen** [files-community/Files#5858]
### What's the Problem?

I noticed there are major changes made in the latest build preview version, one of them is the selected file will now have the blue color. However, it turns into gray color when the selected file(s) are hovered.

### Solution/Idea

Instead of using gray color when the selected file(s) are hovered, it will be great to set it to the dark or light blue on hover.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Set the selected files to a darker or lighter blue on hover | Must |

### Files Version

1.9.25.0

### Windows Version

Windows 10 21H1 19043.1165

**Comment by BanCrash** [comment]
Do you mean this, right?

![image](https://user-images.githubusercontent.com/11770760/129875123-816cf127-6499-4c84-a6ad-670971193d3a.png)

I let as the default color since for me has sense to not color so much the hovering item since you already should know where you have the pointer. But maybe could be useful for someone to change this color too.

**Comment by stanleyowen** [comment]
Yap it's probably what I mean. Although I realize where is my cursor, it will be quite weird (for me) to have very different color when the selected files is hovered. However, maybe maintaining the color of selected files on hover will be also a great option such as how the File Explorer implement it.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5876.
