### ISSUE TITLE
In Column View there's no clear difference between the open folders and the currently selected item/items

### ISSUE THREAD

**Issue by Takanu** [files-community/Files#5880]
### What's the Problem?

While in other views there only has to be a selection highlight applied to the items you're editing or viewing in one directory, in Column View you have two selection types that currently have no distinction in the user interface:  1) The folders that have been opened to make up the chain of hierarchical folders being displayed.  2) The items the user is actively selecting to view or perform an operation on.   In both these instances the same background highlight and accent colour bar along the left side are used.

### Further description of the problem

![image](https://user-images.githubusercontent.com/9108903/130316635-741493bf-f272-461f-97b3-b3bd74f68b83.png)

**This image just describes the problem as the "Problem" input box on Github is too small to include this.**  

- There's no clear separation between my current item selection and the folders that are open and contributing to the Column View display.
- This means that actual state of selected objects is indiscernible at a glance.
- This also means that you can select other files further down the hierarchy and it will create the effect where the folder opened is no longer the one being selected even though it is contributing to the Column View, as is the case with the first column in this example - "Files Playground" is the open folder but "Rescued Downloads" is the currently selected item. 

---
### Solutions

There **_must_** be two different types of highlights for Column View - one to indicate an open folder, and one to indicate a selected item.

Given that the default highlight design in Files is the one currently used throughout the app for different views, **this highlight design should remain for currently selected files** and **a new highlight design should be created for a currently open folder.**

I'm not experienced in Windows UI design so my thoughts on what this secondary design could be is not going to be precise but initial thoughts include:

- Using the background highlight but dropping the "bar accent" (the strip of colour on the left side of a selection), to indicate that the Folder is contributing to the view but is not actively selected.

- Using an arrow or arrow-like icon that is anchored to the left or right side of the open Folder item.  Anchoring it to the left side could cause problems if an open folder can also be an actively selected item, it depends on what behaviours Column View should or should not have.

- If an open Folder can also be selected and operated on at the same time, the two highlight designs must have the ability to be overlapped and still communicate the same information.

### Alternatives

There are likely many design solutions to how a second highlight could be created, but there are no alternatives I can think of that would not necessitate two different highlight designs:

- For Column View to communicate the hierarchy being displayed, it has to show every folder that is open and contributing to the view.
- For files or folders to be operated on they must be selected.

Both things must be displayed amongst each other, this conflict is unavoidable and requires a design solution.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to clearly see the difference between the Folders that are open and the Files and Folders that are actively selected. | Must |

### Files Version

Version: 1.9.25.0 

### Windows Version

Windows 11 Pro 21H2 22000.160

**Comment by yaichenbaum** [comment]
Fyi @mdtauk

**Comment by Talisman39ar** [comment]
I realize this is a fairly old thread but figured I'd add on here...

Additional confusion can come because two individual items can look like they bare both selected, even when one of them no longer is:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/61295915/147625673-f162a844-69d9-494a-8808-0fa498e3f2b8.png">

In this scenario, I'd clicked on an item in the right-most column, and then clicked on the PDF in the middle column and used QuickLook on it...however the item in the right-most column still looks like it is also selected and has focus. I would expect that once I've clicked away to another item (assuming I'm not doing multi-select) that the previous item loses its highlight bar. Furthermore, the status bar reports 1 item selected, but to the user it can look like 3 things are in this screenshot.

So I'd agree there needs to be a differentiation between selected and focused (Mac OS does this by simply graying out the background for an item that has lost focus, while the one that has focus gets the highlight color as background)

**Comment by leic4u** [comment]
@Talisman39ar Why the status of your folders looks correct? My folders status is always local while there are only cloud files in the folder.
![image](https://user-images.githubusercontent.com/32786903/177562380-b2ca65ab-40a0-400b-9459-168056677d50.png)

**Comment by yaira2** [comment]
Merging with #9594
