### ISSUE TITLE
Bug: Pressing AltGr+A in a text field interrupts text entry.

### ISSUE THREAD

**Issue by gsvalbe** [files-community/Files#6150]
### Description

Pressing AltGr + A keys in a text field should not execute commands and interrupt text entry. AltGr key is used together with letter keys to input language specific characters (for example: AltGr+A=Ā in Latvian).
When renaming a file, pressing AltGr + A selects all files and sometimes closes the rename box. This can get very frustrating.
The "Select all" command, in my opinion, should only be executing when pressing Ctrl + A.

### Steps To Reproduce

1. Click to rename a file.
2. Press both - AltGr and A keys in the rename text box.

### Expected behavior

Pressing AltGr+A should only input the letter and nothing else.

### Files Version

2.0.12.0

### Windows Version

Windows 11 Pro 21H2 22000.184

**Comment by gsvalbe** [comment]
Yes. AltGr+A (same as Ctrl+Alt+A) still selects items not types the character. Not a critical bug, just a bit annoying.
For testing, pressing AltGr+A with English keyboard should type 'á' not select all items.

**Comment by ferrariofilippo** [comment]
This is a MUX bug. I've already <a href="https://github.com/microsoft/microsoft-ui-xaml/issues/8063">reported it</a>.
Running some tests, I found that our code does not handle `AltGr + A`. In fact, this is done by `ListView` and cannot be disabled. I think I can try to implement a temporary, inelegant solution that we can remove once the bug is fixed.

**Comment by yaira2** [comment]
Microsoft fixed this issue in WinAppSdk 1.5 and it'll be included in the next version of Files.
