### ISSUE TITLE
Performance issues, splash screen, animations, icon loading performance

### ISSUE THREAD

**Issue by yevon** [files-community/Files#6177]
### Description

Files is super nice but it is low performant compared to standard windows file explorer by some reasons, even in pc's with ssd or nvme drives:

1 - I always see briefly the splash screen (At least on windows 11), it should be optional, or being able to disable it on the settings, or only appear if the initial load takes more than 1 or 2 seconds.

2- The same with animations, it delays the initial load by those slide-in file list animations. We should be able to disable those animations without needing to disable all system animations.

3 - The file-icon loading is noticeable, and in standard windows explorer is instant. There should be or improve an icon memory cache for instant icon loading. The same when you are scrolling large folders, you can notice how the icons load. progressively. 

4 -  When you close the explorer the app could be kept in memory for faster start up and memory icon caching,.

### Expected behavior

Better or same performance compared to standard windows file explorer.

### Files Version

2.0.12.0

### Windows Version

Windows 11 dev

**Comment by hez2010** [comment]
Thanks for your advice. We do still have some performance issues need to be resolved and we are always continuing tuning Files performance. 

1. Turning off splash screen doesn't help in this case. We load all profiles, devices and settings during the splash screen, even if we disable the splash screen, the startup time won't be improved and instead there will be no window appearing at all during the period of original splash screen. 
2. Turning off animations doesn't help in this case. Animations in UWP are relatively independent with UI responsiveness, even if we turn off the animations, it will only change the animations to UI freezing. 
3. This is because we are using RPC for icon loading while explorer doesn't, this would result in 100x-1000x slower invoking time. UWP doesn't have enough privilege to load icons as explorer so we have to send those requests to the FullTrustProcess and retrieve responses remotely. Currently we cannot figure out a way to do this in-process.  
4. This seems doable. We can keep a background process of Files and make it automatically start after system boot for faster startup.

**Comment by yevon** [comment]
Nice to know thanks for the fast response!

1. Ok, related to 4, maybe this could be done during system startup and be kept in memory.
2. By disabling all windows system animations I noticed Files responding just a bit faster, maybe just a feeling.
3. uwp limitations :(
4. Nice addition, automatically starting it on boot would be nice, as the profile loading and device loading could be done then and in background instead of during app start?

**Comment by yaichenbaum** [comment]
@yevon thank you for opening this request, merging with #4180 so we can track it in one place.

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.
