### ISSUE TITLE
Colum sizes don't save position when re entering the folder

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#6199]
### Description

I can change column sizes in a folder but if I go back then to it again or close the program it resets to the wide as possible sizes.

### Expected behavior

It should save the custom sizes and not reset

### Files Version

2.0.13.0

### Windows Version

10.019043.1237

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7202548/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7202549/debug_fulltrust.log)

**Comment by wnstngs** [comment]
Some additional informational on 2.0.13.0:
Columns sizes are saved after closing if firstly open any folder with unchanged column size instead of a changed folder. If open folder with changed columns sizes after opening another folder columns sizes restore to changed values even if firstly sizes were reset to default.
Columns sizes are saved if navigate through different folders without app closing.

P.S. Don't we need to change columns sizes for all folders not for only one? Maybe we can implement it with an appropriate option in the preferences?

**Comment by josh-65** [comment]
Merging with #6448
