### ISSUE TITLE
Feature: Allow pining recycle bin to start in right click option

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#6230]
### What's the Problem?

Other folder allow pining there folders to start but not the recycle bin

### Solution/Idea

Allow the option like other folders

### Steps to reproduce
1. Open the Recycle bin
2. Right click on blank space or sidebar
3. See no option for Start menu only Favourites

### Files Version

2.0.13.0

### Windows Version

10.0.19043.1237

**Comment by Hark64** [comment]
Hello, I would like to work on this issue but I am unable to reproduce the issue described as when I installed Files I was able to pin and unpin the recycle bin. Has this issue already been addressed?

**Comment by Hark64** [comment]
Is pinning to the start menu the same thing as pinning to favorites because I can pin and unpin the recycle bin to favorities.

![image](https://user-images.githubusercontent.com/91097852/210447897-91efe760-f9c1-472d-a1c6-d0a422f8d251.png)
![image](https://user-images.githubusercontent.com/91097852/210448008-55daa779-b7a4-4e24-a65f-3e87331e1ca5.png)

**Comment by Josh-65** [comment]
No. Pining to favourites is the in app saves. Start menu is Windows start menu

**Comment by EaranardMso** [comment]
I'm unable to reproduce this issue. I'm guessing it's already been fixed, but not closed.

![Image](https://user-images.githubusercontent.com/99692910/216421554-bf06db3a-9437-4851-8945-a21d11b30c6c.png)
