### ISSUE TITLE
Make the tabs clickable on top when window is maximized

### ISSUE THREAD

**Issue by iloveitalready** [files-community/Files#6397]
### What's the Problem?

When I want to select a tab by clicking on it I have to aim for it more precisely, because there is some padding on top which means I can't just drag the cursor to the top of the screen but I have to move it a little bit under it. This is very frustrating since my muscle memory expects the tab to be clickable at the top, like it is in many other programs that have tabs,

### Solution/Idea

Make the tabs clickable on top

### Alternatives

Make the tabs clickable on top as an option

### Files Version

Version: 2.0.13.0 

### Windows Version

OS Version: 10.0.19043.1266

**Comment by viruseg** [comment]
Tabs take up too much space. You need to remove the indents at the top and bottom. A good example of an implementation of tabs for explorer is the Groupy application.
![image](https://user-images.githubusercontent.com/919215/137597472-9440a0f6-2843-47f6-9a15-6dfa3e9783a0.png)

**Comment by MalteTasler** [comment]
Maybe, Files could do it as many other modern apllications nowadays such as Microsoft Edge, that make the titlebar smaller when the window is maximized. In maximized mode, the padding above the tabs of the Files window should be removed so that the user can accomplish what this request is aiming for. When the window is not maximized the layout should be as it is now as there is no need for the cursor to be dragged to the verry top of the screen in most cases. 

In MS Edge, padding above the tabs is also only present when the browser is not maximized.

**Comment by octopushugger** [comment]
This issue can be simply solved by changing the margin property of "HorizontalTabView" from "0,10,0,0" to "0,0,0,0" when the window is maximized. I've never programmed with UWP before so I'm having a hard time figuring out where in the code a window state event should go for this.

**Comment by yaichenbaum** [comment]
> This is very frustrating since my muscle memory expects the tab to be clickable at the top

I'm not sure this is a good idea, after all, the majority of applications do not have tabs and users muscle memory expects to be able to drag the window by moving the cursor to the top of the screen. Additionally, unlike browsers where the window is usually maximized, the window for Files is usually smaller.

**Comment by octopushugger** [comment]
@yair100 

Of course I agree this feature should only apply when the window is maximized. I think the benefit here of faster lower effort tab selection outweighs the small potential of people accidentally dragging a tab instead of the whole window from a maximized state. And it's not like this disables any features either, you can still drag the window from the empty space to the right of the tabs which I am already accustomed to doing from my use of web browsers.

**Comment by yaichenbaum** [comment]
> And it's not like this disables any features either, you can still drag the window from the empty space to the right of the tabs which I am already accustomed to doing from my use of web browsers.

That's correct, but as mentioned, that's not something the average user knows about.

**Comment by viruseg** [comment]
Add an option to the settings menu. With which everyone chooses what they are comfortable with.

**Comment by yaichenbaum** [comment]
Options are good but in cases like this, we'd like to define a proper behavior. That's why we're keeping this issue open for a while before making a decision.

**Comment by yaira2** [comment]
Thank you for sharing your feedback, it appears that there are limitations in the WinAppSdk platform that would prevent us from implementing this option. In addition, we've decided that it's preferable to keep the current behavior so that it functions as a proper drag region.
