### ISSUE TITLE
The devices menu is not as wide as the folders menu on the homepage. [INSIDER 2.0.16]

### ISSUE THREAD

**Issue by nightwing2994** [files-community/Files#6398]
### Description

![image](https://user-images.githubusercontent.com/77131766/136581746-24ac2e91-0808-4e69-84b6-1dae2c6cdeeb.png)

As you can see, the folders menu is wider than the devices menu. It's kinda inconsistent imo.

### Steps To Reproduce

1. Install Build 2.0.16.
2. Open Files.
3. You can see it on the homepage itself.

### Expected behavior

In my opinion, the sizes of menus should be consistent.

### Files Version

v2.0.16

### Windows Version

Windows 11 21H2 Build 22000.194 (Stable Release)

### Relevant Assets

![image](https://user-images.githubusercontent.com/77131766/136582058-fad0bfe5-b69c-4510-967b-b6e8db0af733.png)

**Comment by StefanJanssen95** [comment]
What would be the expected behaviour? With the current size of the drives they dont fit next to eachother. Wrapping the folders seems weird to me as well. I can see the three dots in the title being moved to the far right so it shows that it's using that space.

Or it's possible to shrink the size of each drive to make it fit and give them a min and max width, though I'm not sure if that will solve the issue.

**Comment by cinqmilleans** [comment]
@nightwing2994 @StefanJanssen95 @ballonura @dileepthoutam @yair100 One solution is to stop stretching the Folder widget. This stretch looks ugly on a very wide screen. Here is an preview.

![WidgetAfter](https://user-images.githubusercontent.com/46631671/169054841-b7664b5b-232e-42d2-bbcd-d0b76ca3bb95.png)

**Comment by cinqmilleans** [comment]
@yair100 What does he do exactly? I have already completed this modification.

**Comment by yaichenbaum** [comment]
It's not complete it but you can see the work in progress in #9108

**Comment by yaira2** [comment]
This is by design
