### ISSUE TITLE
Feature: Add option to completely hide the sidebar

### ISSUE THREAD

**Issue by Onidotmoe** [files-community/Files#6408]
### Requirements
Add option to settings to completely hide the sidebar

### Files Version

Version: 2.0.13.0 OS Version: 10.0.19043.1237

### Windows Version

Windows 10 21H1 19043.1237

**Comment by gave92** [comment]
You can collapse the sidebar so it takes very little screen space, could you elaborate on why you'd like the ability to hide it?

**Comment by VampireMonkey** [comment]
> You can collapse the sidebar so it takes very little screen space, could you elaborate on why you'd like the ability to hide it?

It's obnoxious and takes up space when you don't use it. And collapsing it still makes it consume around 50 pixels horizontally.

**Comment by yaichenbaum** [comment]
Based on a quick poll, 99% of users use the sidebar. It'll be interesting to continue gathering feedback on this.

**Comment by yaichenbaum** [comment]
Thank you for your feedback, I understand the reason to hide the sidebar completely but it appears that almost every user uses the sidebar and it doesn't make sense for us to implement this option.

**Comment by beedell-roke** [comment]
@yair100, should this, consequently, be closed as not planned, rather than completed?

**Comment by Josh-65** [comment]
We don't use githubs close states thing as theres no reason too.

**Comment by infoparticle** [comment]
Although this issue is closed, wanted to share my thoughts. @yair100 if we go by user polls most majority may be using sidebar. However if we can get minimalistic aesthetics by removing unwanted clutter when needed, it would greatly help and attract users who are currently not in the user polls! ! 

Clutter-free UI really adds value (think google home page vs yahoo home page, apple products UI vs others). Clutter-free UI will be useful esp. when working with dual pane in small screens where every pixel of screen real estate matters. Same is true for all UI components (toolbars, menbars, statusbar etc.). If you look at the emacs community, most of them turn off menu-bar, tool-bar etc. to achieve this minimal and functional look.

**Comment by yaira2** [comment]
> this will attract users who are currently not in the user polls

That's always the tradeoff when asking existing users for feedback, but on the other hand, feedback from someone who hasn't tried to get used to the existing UX isn't going to be something we can act on. That being said, nearly 99% of users responded that they use the sidebar which leads us to believe it's an integral part of the app.

**Comment by infoparticle** [comment]
Sure let people who love sidebars keep using it, let the default be with side-bars + other bells and whistles. It will be nice to hide them when needed. Anyways thanks for all the wonderful efforts you guys put in!

**Comment by dchatel** [comment]
> Although this issue is closed, wanted to share my thoughts. @yaira2 if we go by user polls most majority may be using sidebar. However if we can get minimalistic aesthetics by removing unwanted clutter when needed, it would greatly help and attract users who are currently not in the user polls! !
> 
Just want to add my two cents on this. I'm not a user of Files. I've tried it multiple times, and everytime, I uninstalled it.
It's a beautiful app, but one of the reasons it never ticks for me is the impossibility of hiding the sidebar.
And the fact I've tried it multiple times also tells another story : if it wasn't for this sidebar, I would probably be using it.
