### ISSUE TITLE
Docs AHK Win+E Doesn't Work

### ISSUE THREAD

**Issue by mertbakir** [files-community/Files#6413]
### Description

[The script](https://files.community/docs/configuring/configure-win-e) in the docs to replace Win+E using AHK didn't work out for me. I'm no expert of AHK but I why we don't simply:

```
#E::
   Run, files
   Return
```

This just works.

### Expected behavior

I expect the script in the docs to work.

AHK Version: 1.1.33

![image](https://user-images.githubusercontent.com/43188411/136676836-8455f9d0-e155-4a77-a9e5-478b7a422d13.png)

### Files Version

2.0.13

### Windows Version

Windows 11 22000.194

**Comment by gave92** [comment]
I expect that works too, the script is fancy as when you win+e and Files is already open a new tab is opened instead of a new window.

The script on the website is wrong, try if it works if you change the second line to:
`FilesLocation := USERPROFILE . "\\AppData\\Local\\Microsoft\\WindowsApps\\files.exe"`

**Comment by mertbakir** [comment]
> I expect that works too, the script is fancy so that when you win+e and Files is already open a new tab is opened instead of a new window.
> 
> The script on the website is wrong, try if it works if you change the second line to: `FilesLocation := USERPROFILE . "\AppData\Local\Microsoft\WindowsApps\files.exe"`

I see, it works and opens a new tab. The docs needs to be updated then.
