### ISSUE TITLE
After pasting on a directory, the directory don't refreshes

### ISSUE THREAD

**Issue by lucaberti** [files-community/Files#6564]
### Description

After a CTR-C - CTR-V nothing happens. THe impression is that the command doesnt work, in realitly the copy is ok, but the result doens't show up since the folder is not refreshed. The only solution to see the copied files is to manually refresh the folder with F5

### Expected behavior

When something relevant changes in a folder, it should be automatically shown/updated

### Files Version

2.0.13.0

### Windows Version

Windows 11 21H2 22000.282

**Comment by gave92** [comment]
Does this happen in network shares/folders or local folders too?

**Comment by metalfabs** [comment]
I have the same issue on a Windows 10 machine with both local and network folders.

Renaming files/folders, deleting, or creating new items all have the same issue.

Refreshing with F5 or Ctrl+R will update the folder.

It seems the issue is that Files will not refresh a folder automatically after a change is made.

**Comment by gave92** [comment]
Bumping to #7304
