### ISSUE TITLE
Slow Folder Enumeration/Listing with a few hundred subfolders

### ISSUE THREAD

**Issue by cardin** [files-community/Files#6568]
## Environment
Version: 2.0.13.0
OS Version: 10.0.21390.2025

## Expected
Files' enumeration speed should be comparable to Windows Explorer's

Windows Explorer is able to display a folder (which contains 645 subfolders) within 1 second.

## Observed
Files takes ~5 seconds to enumerate that folder.

Pressing the refresh button will again, take ~5 seconds to enumerate.

**Comment by cardin** [comment]
Not sure if related, or a different bug, but:

I have a WSL2 instance, which contains 47,000 subfolders. That actually never finished loading in Files (after enumerating for a couple seconds, it stops at 22,000 listed subfolders), with the loading indicator perpetually spinning.

Windows Explorer took 1 second to enumerate all 47,000 folders.

**Comment by minihazel** [comment]
I have this same issue in every single folder I open.

I read that the reason File Explorer does it so quickly is because it caches your folders and files, hence why it's nearly instant. Files fetches all files and folders in real-time everytime you use it.

I'd like if Files also cached the way File Explorer does. The slow enumeration is a huge dealbreaker for me using an otherwise brilliant app for browsing.

**Comment by cardin** [comment]
> Enumeration in the latest preview build is much closer to File Explorer.

Just to get a sensing, would this be a major or minor version update? I'd just checked that Version: 2.0.34.0 OS Version: 10.0.19044.1348 still has the issue.

**Comment by yaichenbaum** [comment]
@cardin the changes were included in v2.0.34. How many items are in the directory you tested with?

**Comment by cardin** [comment]
@yair100 48 thousand folders on WSL. After enumerating 32 folders, it got stuck for a fair bit of time.

Windows Explorer could display all folders in seconds.
