### ISSUE TITLE
Open Storage Sense does not show at system disk

### ISSUE THREAD

**Issue by InfiniteSynthesis** [files-community/Files#6664]
### Description

The Open Storage Sense button in my Files now appears at disk D. However, my system is installed at disk C, and the storage setting indeed shows the storage condition of dick C.

![drives](https://user-images.githubusercontent.com/20440018/139559280-a228ec9b-5963-49b0-a7e5-eaf876e0b40f.PNG)

Maybe this is because that the order of my disks are mounted in an weird way, check below for my disk management.

![volumn](https://user-images.githubusercontent.com/20440018/139559297-28db286f-88c2-4d93-9ba0-5289db32ee1c.PNG)
.

### Expected behavior

The Open Storage Sense appears at system disk.

### Files Version

2.0.13.0 

### Windows Version

10.0.19043.1320

**Comment by gave92** [comment]
Thanks for the report. "Open storage sense" button is shown for drives where the available space is low (D drive) and the settings app does not support opening Storage sense page for a specific drive. The closest we can get is the "Drive selection" page.

**Comment by gave92** [comment]
@yair100 since it's not possible (in any sane way) to open the settings app to the StorageSense page for a specific drive, would it make sense to open the [Overview](https://user-images.githubusercontent.com/9673091/139582020-cfffce12-e0d3-43a2-9d36-c092664b958b.png) page when clicking on C: drive and the [Drive selection](https://user-images.githubusercontent.com/9673091/139582034-d651f887-2893-402a-83eb-66d906bdeab0.png) page when clicking on other drives?
If not perhaps it's better to put the button to open storage sense in the drives widget "..." menu so users don't expect the settings app to be opened on a specific drive page.

**Comment by yaichenbaum** [comment]
> would it make sense to open the Overview page when clicking on C: drive and the Drive selection page when clicking on other drives?

Probably 👍

**Comment by yaichenbaum** [comment]
This issue should be resolved with #6668
