### ISSUE TITLE
Resizing detail view information very slow

### ISSUE THREAD

**Issue by justinbernard-dev** [files-community/Files#6784]
### Description

When resizing the information a detailed list view offers the movement isn't as fast as the mouse. 
![List elemtents](https://user-images.githubusercontent.com/83189122/140660487-6307b226-efcf-4a01-87a2-d0d65f9ae2bb.jpg)

### Steps To Reproduce

1. Got to Layout
2. Change it to "details"
3. Resize the sections

### Expected behavior

It should move as fast as the mouse without such delay just as the Microsoft Explorer.

### Files Version

Versão: 2.0.34.0

### Windows Version

Windows 11 21H2 22000.258

**Comment by Hellobrine** [comment]
I noticed that, but simply found it useful as resizing goes smooth this way lol

**Comment by justinbernard-dev** [comment]
If it's intended, it obviously isn't a bug so I'm gonna close it. But I have to say that with my low DPI and Mouse speed it really isn't that comfortable to resize the menu like this.

**Comment by generalguy41** [comment]
Personally I agree with the issue here and think it should be fixed

**Comment by justinbernard-dev** [comment]
Reopening

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, it's something we would like to resolve but we are held back because the DataGrid control is outdated. WinUI is planning to create a new DataGrid control, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500
