### ISSUE TITLE
Feature: Focus existing tab instead of creating duplicate when opening from external process

### ISSUE THREAD

**Issue by boysent** [files-community/Files#6925]
### Description

Opening a folder from an external link (e.g. download from a browser) will open a second tab of the same folder instead of re-using the first instance of the tab.  This occurs with the download folder at a minimum

### Steps To Reproduce

1. Download file from Chrome.
2. Click to open downloads folder from Chrome
3. New Downloads folder tab is opened in Files.
4. Repeating steps 1-3, creates a new Downloads tab instead of re-using and activating the existing Downloads tab already in Files.

### Expected behavior

Expected Downloads folder tab to be used instead of a second tab for the same folder being opened.

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.22000.318

**Comment by josh-65** [comment]
It's the same behavior for any folder being opened externally. I don't think it make sense to change it just for the download since that makes a consistent issue. you can simply just close the other tab and/or don't open it in the first place. I'm sure there's also complications adding this in code since files wont know why the other tabs are open from the user.

**Comment by boysent** [comment]
Thanks for the quick response. I didn't mean to imply that the download
folder is unique. I was just citing that as an easy to check example. Tim

**Comment by MalteTasler** [comment]
I like the idea, since tabs in Files should in general behave different from browser tabs. Browser tabs are about web sessions, hence multiple tabs can be different in content even though the same URL is opened. In Files on the other hand, there is no reason to open a new tab with the same path as an existing tab.

BTW, please add the "feature request" tag. :)

**Comment by clackwell** [comment]
There are extensions for web browser that also try to address this as a "site/URL already open, switch to that tab instead of opening a new tab" style. Just saying that the problem itself is somewhat universal.

**Comment by clackwell** [comment]
> I like the idea, since tabs in Files should in general behave different from browser tabs. Browser tabs are about web sessions, hence multiple tabs can be different in content even though the same URL is opened. In Files on the other hand, there is no reason to open a new tab with the same path as an existing tab. :)

If you call it "state" instead of "content", the perspective may change:

State may include an open rename dialog/UI, selection/checkboxes, sorting, grouping, etc. It may be considered advanced to have two tabs of, say, the Download folder with different selections, sorting, group, etc. but...I am a friend of keeping things open, rather than limiting them (to exactly the use cases that I intend to cover). But I know that limiting things like this, and later opening the scope can also have its merits, and may prevent having to backtrack on some behavior or possibilities that may no longer work due to other changes. Both approaches may cause pain for some users. :)

**Comment by clackwell** [comment]
Also, as far as I know, the extensions for web browsers offer configurability and perhaps custom rules for the decision when to reuse a tab, and when not to. (On the other hand this likely does not make them easy to use for such more advanced cases.)

**Comment by yaira2** [comment]
This is approved an ready to build

**Comment by yaira2** [comment]
This behavior will be included in the next release.
