### ISSUE TITLE
Inform user when files cannot be moved or excluded.

### ISSUE THREAD

**Issue by cleuton4k** [files-community/Files#6981]
### What's the Problem?

when cutting/pasting files that are open in other programs, the app says that the files were moved, but not.

### Solution/Idea

tell me which files cannot be moved/excluded and in which program the file is open.

### Alternatives

tell me which files cannot be moved/excluded and in which program the file is open.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Files Version

2.0.34

### Windows Version

windows 10 home 64 bits 21h1

### Additional comment

https://user-images.githubusercontent.com/90144967/142458498-b8076192-c6cf-46fd-b070-a1931354d4b9.mp4

![01](https://user-images.githubusercontent.com/90144967/142461963-0443bdfb-b4f0-428e-8e54-b1c52019ffd9.jpg)

**Comment by cleuton4k** [comment]
??

**Comment by octopushugger** [comment]
This is more of a bug than a feature request imo.

I encountered a similar issue when trying to move protected operating system files. Instead of informing me there isn't permission to move the file it just did nothing. 

Ideally a future update would request admin perms or at least inform the user the operation couldn't be completed.

**Comment by gave92** [comment]
Merging with #1681 and #8572
