### ISSUE TITLE
Bug in opne terminal

### ISSUE THREAD

**Issue by Somyst** [files-community/Files#6997]
### Description

Open terminal crash my pc

### Steps To Reproduce

Click in open terminal and CRASH

### Expected behavior

No crash

### Files Version

2.0

### Windows Version

21h1

**Comment by yaichenbaum** [comment]
@Somyst is this an issue in v2.0.34?

**Comment by gave92** [comment]
I think it is, these (quite common) appcenter reports seem to be caused by `App.TerminalController.Model` being null: [1528823123u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1528823123u/overview?q=preferencesviewmodel&searchType=all), [813232478u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/813232478u/overview), [4277801717u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/4277801717u/overview)

**Comment by gave92** [comment]
@Somyst could you 🙏:
- upload the app's log files. You can find them from Files Settings > About > Open log location (debug.log + debug_fulltrust.log)
- post the contents of the "terminals.json" file (you'll find it in the above folder, inside the "settings" folder
- check whether you're able to open the "Preferences" page of Files Settings

**Comment by Somyst** [comment]
No need, I've fixed it, whenever I tried to open a folder in cmd it would close, but it's ok

**Comment by gave92** [comment]
How did you fix it? If it still crashes when using "Open in terminal", the logs files + "terminal.json" could help us resolve the issue for you and all users.
