### ISSUE TITLE
Feature: Add path column for search results/tags

### ISSUE THREAD

**Issue by Hefaistos68** [files-community/Files#7070]
### Description

When searching I would expect some way to identify the files found. There is no indication whatsoever (not even in the tooltip) where the item is from (folder), the only option is using "Open Parent" (or "Copy location") from the context menu of a file, which will throw away the search results because it opens in the same pane. Returning to the search results will repeat the search though.
![image](https://user-images.githubusercontent.com/8855055/143431086-414bb693-7f17-4c7e-975e-df58ce18e8d7.png)

### Expected behavior

1. Add a column with the file path in search results

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19042.1348

**Comment by ObiW4nKenobi** [comment]
Ditto for "tagged" views since the purpose of tags is view multiple files that shared a common trait/keyword as one cohesive list. However, the files themselves could be scattered across the storage device. So, the search results view and tagged views should both show the "Path" property as part of the "details" layout. And for full flexibility let the user decide in the end whether he wants it "checked" or "unchecked" just like File Explorer allows now.
