### ISSUE TITLE
Paste files from VMWare doens't work

### ISSUE THREAD

**Issue by LucFeron** [files-community/Files#7084]
### Description

When I copy a file from a VMWare virtual machine and paste it in Files nothing happens. Pasting in the Windows Explorer pastes the file correctly

### Steps To Reproduce

1. Open Files
2. Open VMWare 
3. Start a virtual machine 
4. Copy a file from the virtual machine
5. Goto to Files
6. Press paste
7. Nothing happens

### Expected behavior

The file from the VM should be pasted

### Files Version

Version: 2.0.34.0 

### Windows Version

OS Version: 10.0.19044.1348

**Comment by JohnMansell** [comment]
Copy **TO** virtual machine is also broken. Copies parent folder, but does not copy recursively.

1. Open Files
2. Open VMWare - Virtual Machine
3. Copy directory from files -> Virtual machine
     - Copy with either ctrl-c + ctrl-v or drag-and-drop
4. Parent folder is copied -- child directories are not copied

**Expected Behavior** 
Directory and all sub-folders should be copied

**Versions**
Files --2.1.2.0
VMware Workstation -- 16.2.2 build-19200509
Host Windows -- Windows 10 Enterprise -- 21H1
VM Windows -- Windows 10 Home -- 21H1

**Comment by Josh-65** [comment]
Merging with #6827
