### ISSUE TITLE
Default file explorer feature is not working properly.

### ISSUE THREAD

**Issue by Sabarigirishan** [files-community/Files#7218]
### Description

This feature is not working when I open any drivers(C, D, E, etc) or recycle bin using run command(win+R) in win11.
But normal folder are opening in the files software.r

### Steps To Reproduce

1. Type Win+R.
2. Type folder destination(c:\)
3. Hit enter.
![image](https://user-images.githubusercontent.com/66403234/144738763-15592ad7-5ec9-4a6f-8d4d-b362e460d741.png)

### Expected behavior

Expected behaviour was files softwared to be open showing given folder destination.
![image](https://user-images.githubusercontent.com/66403234/144738818-5068f8c0-e3ef-4999-b9b1-302215fe8ca6.png)

### Files Version

Version: 2.0.34.0 OS Version: 10.0.22000.348

### Windows Version

windows 11 22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7655468/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7655469/debug_fulltrust.log)

**Comment by gave92** [comment]
This is currently by design. To open Files when clicking on This PC or recyclebin, the reg files included below should do the trick but there may be undesired side effects.

To do:
1. Extract the two files from this archive [SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip) and place them *on the desktop*
2. Run `SetFilesAsDefault_Bad.reg`

To reverse run the other reg file (UnsetFilesAsDefault).

**Comment by gave92** [comment]
No known side-effects, but it hasn't got much testing. In any case you should always be able to revert to Explorer by running "UnsetFilesAsDefault.reg".

**Comment by Sabarigirishan** [comment]
Thanks, i will check this out.

**Comment by gave92** [comment]
Nice, we'd be really happy to get feedback if you notice any issue.
