### ISSUE TITLE
Standard explorer when I click on the trash

### ISSUE THREAD

**Issue by topiga** [files-community/Files#7295]
### Description

Files is not opened when I click on the trash icon, on the desktop. It opens instead the standard Windows file explorer

### Steps To Reproduce

1. Activate the experimental feature "Set Files as default file explorer"
2. Open the trash from the desktop

### Expected behavior

It is supposed to open Files, not the standard Windows file explorer

### Files Version

Version : 2.0.34.0 OS Version: 10.0.22000.318

### Windows Version

Windows 11 21H2 22000.318

### Relevant Assets/Logs

My [debug.log](https://github.com/files-community/Files/files/7719995/debug.log) and [debug_fulltrust.log](https://github.com/files-community/Files/files/7719997/debug_fulltrust.log)

**Comment by gave92** [comment]
This is currently by design. To open Files when clicking on This PC or recyclebin, the reg files included below should do the trick but there may be undesired side effects.

To do:
1. Extract the two files from this archive [SetUnsetFilesAsDefault_Bad.zip](https://github.com/files-community/Files/files/5825020/SetUnsetFilesAsDefault_Bad.zip) and place them *on the desktop*
2. Run `SetFilesAsDefault_Bad.reg`

To reverse run the other reg file (UnsetFilesAsDefault).

**Comment by gave92** [comment]
Merging with #6462
