### ISSUE TITLE
Target destination for a shortcut wont accept arguments.

### ISSUE THREAD

**Issue by aayushyap89** [files-community/Files#7307]
### Description

In regular file explorer when you open properties for a shortcut you can for what I was doing add --incognito to make brave browser in private mode instead of a regular window. Though when I opened the properties window for files and opened shortcut the destination box seemed to be the closest to file explorer target window and when I added --incognito to the end nothing happened and it didnt even change it in regular file explorer so I dont know if destination has the arguments feature. Also there is an arguments box and I did try --incognito in the arguments box and it didnt work either.

### Steps To Reproduce

1. find a shortcut, I used brave browser shortcut
2. open its properties
3. open the shortcut section
4. type your argument, I used --incognito to open brave in private mode on default
5. it wont work

### Expected behavior

To make brave open in private mode

### Files Version

2.0.42.0

### Windows Version

Windows 11 21H1 22000.348

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7730032/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7730033/debug_fulltrust.log)
Both log files

**Comment by gave92** [comment]
Where is the shortcut located? Is it in a folder the requires administrator access? It looks like Files is failing to save the arguments due to "access denied".
`
2021-12-16 11:44:41.2726|WARN|ParseFileOperationAsync|Access is denied. (0x80070005 (E_ACCESSDENIED))
	System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at Vanara.Windows.Shell.ShellLink.SaveAs(String linkFile)
`

**Comment by yaira2** [comment]
@aayushyap89 sorry for the long delay, is this still an issue in the latest version of Files?
