### ISSUE TITLE
Highlight newly created files and folders by default

### ISSUE THREAD

**Issue by DAmNRelentless** [files-community/Files#7310]
### What's the Problem?

I usually create new files with CTRL + SHIFT + N. Mostly that's folders or unnamed files.
Currently, after you create a new element, the current index of my sidebar is highlight.

### Solution/Idea

It would be much more beneficial to highlight the element which was just created.
That way you could instantly open the file/folder instantly by pressing `Enter`. Or in case you accidentally named it wrong, you could simply press F2 to rename it.

This is  a small QoL change but has a lot of benefit if you want to avoid using your mouse as much as possible.

### Alternatives

The alternative is selection the file with the mouse or navigating to it with the keyboard in a very clunky way.

### Priorities

Could

### Files Version

2.0.34.0

### Windows Version

10.0.22000.348

**Comment by jiejasonliu** [comment]
Hi there! 👋 I'd like to work on this issue. I did some looking around and my initial strategy was to retrieve the path from the item per `IStorageItem.Path` and clicking it. Unfortunately, it appears I have to defer the click since the UI isn't updated synchronously with the file creation and thus can't be clicked.

I had a peek in `ItemViewModel` and the `DirectoryInfoUpdated` event appears to be my best option so far. However, I lose track of which file was created (could hackily recover with date modified perhaps?) but more importantly, I have no distinction of **how** the directory was updated.

Any suggestions on how I could proceed without making significant infrastructural changes? 
I'm thinking that I'm overlooking something. Thanks!!😄

**Comment by yaichenbaum** [comment]
> Hi there! 👋 I'd like to work on this issue. I did some looking around and my initial strategy was to retrieve the path from the item per `IStorageItem.Path` and setting the selection to its matching item in `FilesAndFolders`. Unfortunately, it appears I have to defer the click since the UI isn't updated synchronously with the file creation and thus can't be clicked.
> 
> I had a peek in `ItemViewModel` and the `DirectoryInfoUpdated` event appears to be my best option so far. However, I lose track of which file was created (could hackily recover with date modified perhaps?) but more importantly, I have no distinction of **how** the directory was updated.
> 
> Any suggestions on how I could proceed without making significant infrastructural changes? I'm thinking that I'm overlooking something. Thanks!!😄

Is it posbile to track changes to the listview and focus the newly added item?

**Comment by jiejasonliu** [comment]
> Is it possible to track changes to the listview and set the focus to the newly added item?

I don't believe so as of now. The list view is updated per `ItemViewModel.FilesAndFolders` through a bulk operation which suppresses `CollectionChanged.` As far as I see, there's no way to recover the `Add` event since all the UI gets is a `Reset` and refreshes the entire UI with whatever is in `FilesAndFolders` after the bulk operation finishes.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #7657
