### ISSUE TITLE
Add an option to open the folder in file explorer

### ISSUE THREAD

**Issue by TechyAditya** [files-community/Files#7324]
### What's the Problem?

Sometimes, I really want to use original file manager for some reason. If I turn on that experimental setting files as default file explorer, then I got no way to use original file manager (other than opening control panel and navigating back to home). 

### Solution/Idea

In menu, add a context menu to open in file explorer (only if that default file manager option is enabled)

### Alternatives

Right click also helps

**Comment by yaichenbaum** [comment]
@TechyAditya what are the reasons for opening File Explorer? We would like to resolve properly those instead of adding a menu item to fall back to explorer.

**Comment by josh-65** [comment]
I believe this could be useful for when files isn't doing what's expected to get it done quicker. Most common is properly a failed operation for something files doesn't account for or ones that are lengthy in files but not in explorer. Like deleting many files that could be in use since there isn't an apply all feature. I've had to or preferred do this sometimes.

**Comment by yaichenbaum** [comment]
@josh-65 can you open or comment on an existing issue regarding the apply all options? I think it's better to focus on fixing those cases instead of working on this option.

**Comment by josh-65** [comment]
I did make one quite a while ago #5030
