### ISSUE TITLE
Save folder index size

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7327]
### What's the Problem?

When ever I refresh or go back and forth a directory with folder sizes enable they get re index every time (no idea if this causes unnesary drive usage). Side note it doesn't seem to use the properties way so when opening the properties of that folder it also re index's the size.

### Solution/Idea

Cache the folder size (for properties and item column) and refresh with content changes.

### Alternatives

None

**Comment by yaichenbaum** [comment]
cc @cinqmilleans

**Comment by cinqmilleans** [comment]
I already tried. It is easy to cache the size of each calculated folder. The calculation is recursive therefore the subfolders are already cached when we open them. For this functionality, it is necessary to delete the cache of a folder when it is updated, even when it is not displayed. Technically this is possible, but it seems to me that it is not yet used by Files. I don't know the impact on performance. I'll investigate.

**Comment by yaichenbaum** [comment]
> I already tried. It is easy to cache the size of each calculated folder. The calculation is recursive therefore the subfolders are already cached when we open them. For this functionality, it is necessary to delete the cache of a folder when it is updated, even when it is not displayed. Technically this is possible, but it seems to me that it is not yet used by Files. I don't know the impact on performance. I'll investigate.

Seems like it can be a bit heavy but I think it should be fine if we indicate that in the setting description.

**Comment by cinqmilleans** [comment]
Let's test.

**Comment by cinqmilleans** [comment]
@yair100 Here is an idea for improvement that can be implemented quickly and easily, while waiting for a more complete solution.

- When we want to display the size of a folder, we check if the size is cached. If so, we display it, otherwise we display a message (Calculation in progress ...).
- Then, we calculate asynchronously and recursively the current size of the file, because it could have changed.
- During recursive computation, the size of the sub-folders is cached, being limited to 2 levels so as not to overload the memory.
- When the calculation is finished, we update the cache and the display.
- If the cache is too large, the oldest datas are deleted.

This will faster display the values already calculated (the same folder or subfolders), and update the value if it has changed.

**Comment by yair100** [comment]
> @yair100 Here is an idea for improvement that can be implemented quickly and easily, while waiting for a more complete solution.
> 
> * When we want to display the size of a folder, we check if the size is cached. If so, we display it, otherwise we display a message (Calculation in progress ...).
> * Then, we calculate asynchronously and recursively the current size of the file, because it could have changed.
> * During recursive computation, the size of the sub-folders is cached, being limited to 2 levels so as not to overload the memory.
> * When the calculation is finished, we update the cache and the display.
> * If the cache is too large, the oldest datas are deleted.
> 
> This will faster display the values already calculated (the same folder or subfolders), and update the value if it has changed.

Is the cache you're talking about going to be stored across app sessions or only for the current instance?

**Comment by cinqmilleans** [comment]
@yair100 To improve the idea above, we can update the cache directly when adding/removing files with Files by impacting the size of the parents in the cache. This will make it possible to have the right size immediately after an operation in Files, when we return to the parent.

**Comment by cinqmilleans** [comment]
@yair100 I think limiting the cache to the current instance is sufficient. Storing the info in a db will pose too much of a performance and update problem, for very little benefit. You can always add it later if needed.

**Comment by yair100** [comment]
> @yair100 I think limiting the cache to the current instance is sufficient. Storing the info in a db will pose too much of a performance and update problem, for very little benefit. You can always add it later if needed.

I think it's worth keeping it across sessions because otherwise, it won't make much of a difference.

**Comment by cinqmilleans** [comment]
@yair100 The problem with a persistent cache is that drives can change paths. In uwp, it is not possible to have the volume guid. I will do a version without persistence, but with an update during the session. The sizes of subfolders are already calculated during the parent folder. We will add persistence later if possible.

**Comment by yaichenbaum** [comment]
@cinqmilleans is this something we can use the full trust process for?

**Comment by cinqmilleans** [comment]
@yair100 I tried but failed. All my attempts only got nulls. I may have missed something. If someone can get a unique id for a volume, we might have something really cool.
I started working on the file size cache again, because the searchpanel needs integration #7892. I already have a cache system and it's very nice. I need to improve it to optimize memory usage before publishing it.

**Comment by duke7553** [comment]
Appears to have been fixed with #7960

**Comment by yaichenbaum** [comment]
> Appears to have been fixed with #7960

@duke7553 the cache in #7960 is only a temp cache.

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by yaichenbaum** [comment]
@Josh-65 does it stay chached for the current session?

**Comment by yaichenbaum** [comment]
It wouldn't hurt to save the cache across sessions.

**Comment by Josh-65** [comment]
This is fixed in 2.3.11.0
