### ISSUE TITLE
Revert from files back to Explorer.exe as default file browser

### ISSUE THREAD

**Issue by richeaston** [files-community/Files#7599]
### What's the Problem?

Files has broken the file association and just doesn't work, this should be in Alpha at the most and not a full release there are just too many bugs to make it usable.

Please release a method to reset the file association back to explorer.exe as it's a full rebuild otherwise which is really annoying.

Please make the uninstaller reset the file associations back to explorer.exe!!!

### Solution/Idea

Please read above ^^

### Alternatives

make this an Alpha release!

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### Windows Version

Windows 10 21H2

**Comment by josh-65** [comment]
This work fine in 2.1.0.0. you can use the unsetasdefault.reg file in this.
https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip

**Comment by richeaston** [comment]
I managed to revert it back myself by diving into the registry classes

**Comment by dlongm01** [comment]
HI - Could you let me know what to do to reset registry? I have had real trouble wiht this. Runing two machines on W11. Tried File sin both (perhaps foolish to do that) but when I reset the 'replace file explorer' setting I lost File Explorer completely. Has taken hours and still not right. Found reg setting for W10 but these seem incomplete.

E.g. Fie explorer now opens on one PC but can't get multiple windows; on the other machine I can open File Explorer but only if I keep Files installed (uninstall it and File Explorer disappears!). Weird - errors seem different for the same OS?

Badly need help here!

I know there is a warning on the website about this, and fair enough ... but hey! This is actually pretty fatal. At least some advice about how to reset if it goes wrong would be helpful rather than a handwash warning. After all, Files must change the registry in one direction so providing info about how to reverse that if you get stuffed would be nice (with all the usual risk warnings).

Thanks for any advice. (PS in case you ask - no, machines are new so haven't set up Restore points. My bad! Lesson learned!)

**Comment by Josh65-2201** [comment]
Make sure Files is updated then turn off the toggle in Files settings > Advanced > Set as default 

If that doesn't work run this file. [UnsetFilesAsDefault.zip](https://github.com/files-community/Files/files/13334069/UnsetFilesAsDefault.zip)

If they both don't work then there is something wrong with your Windows install and you would probably have to reinstall Windows

**Comment by dlongm01** [comment]
Thanks for the update Josh65. Will try that in mo' after a system scan
finishes ....

Very frustrating issue.

As you say - if your file doesn't work a windows re-install is next ...

ho-hum - bang goes my daily target!

David Longman

**Comment by dlongm01** [comment]
OK - brilliant! Thanks. Scannnow finished and declated some repairs but made no obvious difference.

However, your reg file cured the problem at a stroke. (Well, not all  - some file associations had been knocked out along with startup apps ... but those I can fix!)

All power to you!

Thank you. 

An afterthought to developer community - Josh's regedit reset file might be listed on website under a troubleshooting section? I don't think I am the only one who has hit this snag.
