### ISSUE TITLE
File/folder in the recycle bin can be added to other folders in it

### ISSUE THREAD

**Issue by Josh-65** [files-community/Files#7640]
### Description

I can take a file or folder from the recycle bin and then added it to a folder in there. It doesn't permanently delete them it just adds them like a normal folder would.

### Expected behavior

Moving file/folder into others in the recycle bin should be disabled. External files/folders added should go directly into the root of the recycle bin when dragged and dropped.

### Files Version

2.1.0.0

### Windows Version

10.19043.1466

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/7870740/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/7870741/debug_fulltrust.log)

**Comment by linnjason678** [comment]
Why do you interfear with someone learning proper 
Handling of coder s purps,
Placing problems on others.
Interupting a person an persons 
Life. Your taking soneones files 
That have been deleted and 
Trying to have those issues 
Placed on deleter because its away to make themselves a better person ? Some times 
You look at something does not mean you wAnt it downloaded. So delete is nessary to get that issue out of your phone .
You are wrong for placing issues delete back on them .!

**Comment by Josh-65** [comment]
what on earth are you on about linnjason678

**Comment by yaichenbaum** [comment]
This issue should be resolved with #9323
