### ISSUE TITLE
Hitting the right arrow key when a new column is opening switches focus to tab control

### ISSUE THREAD

**Issue by Cazvind** [files-community/Files#7726]
### Description

I like to use my arrow keys to navigate my computer, I've tried moving with the right arrow but found that the behaviour is very different from macOS' Dock. 

What I'm missing is that each time you hit right arrow the first item inside the folder is selected. In this case, after selecting Desktop, it would select "01 - Kick" next time I press right arrow "- Battery" etc.

Another thing I've noticed is that If you hit the right arrow until you reach the end and then hit it one more time, it kind of loses focus and you can't hit left arrow to go back to the previous folder.

Also when you hit key left arrow, it would be great if the content from the folder inside the folder dissappeared. right now it stays even thought I'm not highlighting the inside folder.

Thanks

![Step 1](https://user-images.githubusercontent.com/97838698/149680584-3ad4701f-7968-4f43-a313-3a855cf3f035.png)
![Step 2](https://user-images.githubusercontent.com/97838698/149680587-e64e0044-9202-44ec-8e5f-bfd2559ca327.png)
![Step 3](https://user-images.githubusercontent.com/97838698/149680649-cc45380b-b1d7-4c36-88b8-82016ce30271.png)

### Steps To Reproduce

Explained before

### Expected behavior

Explained before

### Files Version

2.1.0.0

### Windows Version

Windows 11 Pro 21H2 22000.434

### Relevant Assets/Logs

Explained before

**Comment by yaichenbaum** [comment]
Please fill out the version information

**Comment by Cazvind** [comment]
Done, sorry

**Comment by yaichenbaum** [comment]
@Cazvind can you see if these issues are resolved in v2.1.5?

**Comment by lian-lima** [comment]
> @Cazvind can you see if these issues are resolved in v2.1.5?

I'm facing the same issue in version 2.1.5. In my case, the problem happens when navigating quickly using the arrows to access a folder. The focus changes to the tab bar when opening a folder with a large number of files or folders.

![State-2](https://user-images.githubusercontent.com/98998479/152467882-8e88639b-4e84-4d92-900c-716c7becbb99.png)

**Comment by lian-lima** [comment]
I'm facing the same issue in version 2.1.5. In my case, the problem happens when navigating quickly using the arrows to access a folder. The focus changes to the tab bar when opening a folder with a large number of files or folders.

![focus-changing](https://user-images.githubusercontent.com/98998479/152468106-a12deefe-1167-4bd1-aa3e-c63a486fb5f0.png)

**Comment by yaichenbaum** [comment]
> I'm facing the same issue in version 2.1.5. In my case, the problem happens when navigating quickly using the arrows to access a folder. The focus changes to the tab bar when opening a folder with a large number of files or folders.
> 
> ![focus-changing](https://user-images.githubusercontent.com/98998479/152468106-a12deefe-1167-4bd1-aa3e-c63a486fb5f0.png)

I was able to reproduce this.

**Comment by Harll3kin** [comment]
Still the same problem in 4.1

**Comment by Josh65-2201** [comment]
Thanks, not sure why this was closed.

**Comment by yair100** [comment]
Merging with #13813.
