### ISSUE TITLE
EXPLORER.EXE NOT FOUND

### ISSUE THREAD

**Issue by d4kir92** [files-community/Files#7736]
### Description

how do i repair the normal explorer.exe??

### Steps To Reproduce

how do i repair the normal explorer.exe??

### Expected behavior

how do i repair the normal explorer.exe??

### Files Version

how do i repair the normal explorer.exe??

### Windows Version

how do i repair the normal explorer.exe??

### Relevant Assets/Logs

how do i repair the normal explorer.exe??

**Comment by gave92** [comment]
To restore explorer run this script (make sure to save it as a ".reg" file):
https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
Please let us know if it solves the issue.

**Comment by JoshuaDup** [comment]
@gave92 This script does not work properly. When you run it and attempt to open a file it says file explorer is still unable to be found. You're able to open new files within new windows, btu are unable to open files in the same window. I had to use a backup of my registry in order to solve this problem. Please fix this for future users.
