### ISSUE TITLE
Bug: Cannot create second pane when column layout is being used

### ISSUE THREAD

**Issue by CrypticVader** [files-community/Files#8074]
### Description

When a tab is opened in column layout, clicking on "New pane" does nothing.
On the other hand, dual pane can be used after entering column layout after a new pane is created.

### Steps To Reproduce

1. Open any directory in column layout.
2. Select **new pane** from the ellipsis menu.

### Expected behavior

A new pane is created.

### Files Version

v2.1.5.0

### Windows Version

Windows 11 21H2 22000.469

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/7972325/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/7972326/debug.log)

**Comment by gave92** [comment]
Does the keyboard shortcut work? Ctrl+Shift+"+"

**Comment by CrypticVader** [comment]
> Does the keyboard shortcut work? Ctrl+Shift+"+"

No, it doesn't work, even if the tab isn't in column layout.

**Comment by gave92** [comment]
Uops, that's because the shortcut is _Alt_ + Shift + "+" 😅

**Comment by CrypticVader** [comment]
lol
Nope, it doesn't do anything either, column or not.
My keyboard doesn't have a dedicated '+' key. I used the '+/=' key btw.

**Comment by gave92** [comment]
> My keyboard doesn't have a dedicated '+' key
That's probably it, thanks for testing

**Comment by yaichenbaum** [comment]
@CrypticVader is this still an issue in the preview version? https://files.community/download/preview

**Comment by CrypticVader** [comment]
Yes, it still doesn't work.
I'm on v2.2.5.0 store insider version.

**Comment by puppetsw** [comment]
I'm not able to replicate this issue on 2.2.52.0.

**Comment by gave92** [comment]
It works with thehe keyboard shortcut, doesn't work with the toolbar menu.

**Comment by puppetsw** [comment]
The PaneHolder property is null whenever the display is set to ColumnShellPage. The Alt+Shift++ keyboard shortcut works because the KeyboardAccelerator_Invoked is correctly being called from the PaneHolderPage. But if you try to close (from the menu) the pane after opening with the shortcut, it won't let you because the property is still null in the ColumnShellPage. But changing back to ModernShellPage (details) sets the property value and you can close it again. 

Just need to figure out how the binding is being set for the ModernShellPage and fix it for the ColumnShellPage. Setting break-points on the property sends me to the bindings for the PaneHolderPage. So I'll start there.

**Comment by yaichenbaum** [comment]
Thanks for the update, I've been meaning to look at this as well but most of my Files time has been working on design lately.

**Comment by ferrariofilippo** [comment]
I think this is the root of the problem:
![2](https://user-images.githubusercontent.com/102259289/212658910-0b062d20-ffc1-4122-a995-3118625e8f98.png)

**Comment by yaira2** [comment]
@CrypticVader this issue will be resolved in the upcoming v2.5.20 release.

**Comment by CrypticVader** [comment]
Great work👏
