### ISSUE TITLE
Automate Closing Stale Issues

### ISSUE THREAD

**Issue by sumeshir26** [files-community/Files#8093]
### What's the Problem?

Recently, I noticed that the issue tracker is getting cluttered with issues which are not approved. 

### Solution/Idea

https://github.com/marketplace/actions/close-stale-issues could be used to automate closing of stale issues (My suggestion is in 90 days) if the issue does not have the `triage approved` label.

### Alternatives

_None_

### Priorities

_NA_

### Files Version

2.1.5

### Windows Version

Windows 11 Version 22000.434

### Comments

https://github.com/marketplace/actions/close-stale-issues

**Comment by yaichenbaum** [comment]
@sumeshir26 thank you for your feedback, it's true that there are a lot of open issues that we haven't gotten to, but we don't want to close them as stale since we haven't had a chance to look them over yet. We welcome community participation to help point out duplicates or fixes for issues. If you believe an issue was resolved, mention me on the issue and I'll try to check it out.
