### ISSUE TITLE
Files crash but i don't know why.

### ISSUE THREAD

**Issue by Hardel-DW** [files-community/Files#8461]
### Description

I just opened the G: drive which corresponds to Google drive.
and the application closed.

In a similar way, the application stopped when opening a folder.

I think this is due to the option to display the folder weight.

### Steps To Reproduce

1. The display of folder sizes.
2. Open Google Drive Disks

### Expected behavior

That the application does not crash.

### Files Version

Version : 2.1.13.0 OS Version: 10.0.22000.527

### Windows Version

Microsoft Windows 11 Family 10.0.22000 Build 22000

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8112580/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8112581/debug_fulltrust.log)

**Comment by themoonmeetsthesun** [comment]
Have you tried reinstalling it? I don't know how to read logs and I am a normal user like you. Also that I did encounter something similar even though I use windows 10. After reinstalling it got fixed. I can't reproduce this issue because I uninstalled google drive long back when it was messing with my icons in the search menu.

**Comment by Josh-65** [comment]
Merging with #8413

**Comment by Josh-65** [comment]
you can turn off show folder sizes and it should work again
