### ISSUE TITLE
Crash when pasting

### ISSUE THREAD

**Issue by SdiaSuez** [files-community/Files#8557]
### Description

Consistent crashing using cut/paste command. Crash happens after initiating "paste" via the app "button" option. 

### Steps To Reproduce

Cut file from folder
Open final destination folder
Click "paste" button within app

### Expected behavior

immediate application crash

### Files Version

Version: 2.1.15.0 OS 

### Windows Version

Version: 10.0.19044.1566

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8172617/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/8172618/debug_fulltrust.log)

**Comment by yaichenbaum** [comment]
Is this still an issue in the latest preview build? https://files.community/download/preview

**Comment by MintHawk** [comment]
No, Yair, everything seems to be working fine.Cut/copy/paste works fine.Is there anything else you want me to check? Sent from Mail for Windows From: Yair AichenbaumSent: Τρίτη, 4 Οκτωβρίου 2022 1:21 πμTo: files-community/FilesCc: MintHawk; CommentSubject: Re: [files-community/Files] Crash when pasting (Issue #8557) Is this still an issue in the latest preview build? https://files.community/download/preview—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
