### ISSUE TITLE
Bug: Navigating to folders via keyboard focuses on the name header in the details layout

### ISSUE THREAD

**Issue by oomek** [files-community/Files#9042]
### Description

Keyboard navigation still has this bug when the focus rectangle jumps permanently onto Name tab when pressing enter or temporarily when pressing backspace.

### Steps To Reproduce

1. Use keyboard to open a folder in the details layout
2. See that the name header is focused

### Expected behavior
- Focus should be on the first item in the file list

### Windows Version

Windows 11 22H2 22610.1

**Comment by Josh65-2201** [comment]
Asking @yair100 for approval.

**Comment by QuaintMako** [comment]
I'm taking a look at this issue.

**Comment by Josh-65** [comment]
Is this an issue in the preview version? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
Yes

**Comment by sthivaios** [comment]
I just checked the PRE version, and it does in fact do that.

When hitting enter to enter the folder, the name tab will be highlighted.

https://user-images.githubusercontent.com/109022579/195329948-3dd1062e-6abc-4296-8435-f218ac37c04e.mp4

Btw, if my comments sometimes sound weird, it is because I am from Greece, and just 11 y.o. so, you know, I am just in class D' yet.
