### ISSUE TITLE
Poor performance, slow opening and loading folders, slow to refresh

### ISSUE THREAD

**Issue by quantumwebco** [files-community/Files#9280]
### Description

The app takes a long time to open folders. When double clicking a folder it takes between 1 and 3 seconds to open the folder, then when navigating back up it takes a second to navigate and then the view refreshes another second later which causes the screen to jump

### Steps To Reproduce

Double click a folder, wait for it to load, navigate back

### Expected behavior

As in the native file explorer things open immediately or at least quicker than 2 seconds

### Files Version

Version: 2.1.15.0

### Windows Version

Windows 11 Pro 21H2 10.0.22000.708

### Relevant Assets/Logs

Too long

**Comment by Josh-65** [comment]
Merging with #4180. You can try the preview version https://files.community/download/preview as there has been updates on performace

**Comment by quantumwebco** [comment]
This issue is worse not better in 2.3 @Josh-65

**Comment by yaira2** [comment]
We're excited to share that startup performance will be significantly improved in the upcoming release of version 3. You can download the preview version from our website https://files.community/download.

**Comment by yair100** [comment]
@justrustyspoons we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by justrustyspoons** [comment]
Still takes between 1 and 3 seconds to load a folder. Even ones without much in them. It is noticeably much slower than the native Windows file manager and I switched to File Pilot a few months ago and Files app feels even worse now, because File Pilot is blazing fast lol. One of the most annoying things on Files is that when you double clock to load a folder there is a delay before it even starts doing anything, it doesn't show a loading indicator it just does nothing for about 500ms then loads the folder empty which takes another 500ms to show the content. There doesn't seem to be any caching

@yair100 I literally don't use Files at all any more because the performance is so so bad

**Comment by yair100** [comment]
@justrustyspoons which preview build did you test? Also, is it a regular folder or a network share?
Can you please upload a short screen recording?
