### ISSUE TITLE
Make manually resized column widths stick in Details view

### ISSUE THREAD

**Issue by RKinMTL** [files-community/Files#9558]
### What's the Problem?

When user manually slides to resize column widths in Details view, these widths revert to default after leaving and returning to the directory; and do not stick when browsing to other directories.  

### Solution/Idea

Make manually set column widths stick in Details view, and/or provide a user setting to make these apply to other folders like in the native File Explorer.

### Alternatives

Could also be useful to have the "resize columns to fit contents" option as dynamically "on" so that it applies as users browse between directories.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yaichenbaum** [comment]
Column sizes should already be saved in v2.3. You can make the same setting apply to all folders by turning off the option to use individual preferences for different directories (settings > files and folders)

**Comment by RKinMTL** [comment]
I can confirm this is not the case (running Version: 2.3.3.0, OS Version: 10.0.22000.795). Manually resizing column widths in Details view does not stick. When I navigate to another folder, the column widths revert to default; and when I return to a folder where I've previously set column widths, these are reset to default widths. That setting to use individual preferences for different directories is off.

**Comment by Josh-65** [comment]
It hasnt fully been fixed. When the individual directory option is turned off it doesn't save but does when it on for me.

**Comment by ZaLiTHkA** [comment]
I got a new work laptop just recently, which (unfortunately) came with Windows 11.. found this app after searching for alternatives to Microsoft's built-in "File Explorer", but now I'm running into this very same issue.

---

> note: the following paragraphs are purely my own personal opinions.

I don't think the way "File Explorer" handles this scenario is the best anyway, to me it's always seemed very unintuitive.. by the time you've navigated to the "Apply to Folders" button, the mental connection between the folder you just customised and the action you're about to carry out is severely diminished.

I feel that customising "Detail" view columns should be linked to the view type by default, not to the folder currently being viewed. in other words: increasing the width of the "Name" column should use _that_ column width for all views that display it, _unless_ another customisation overrides that rule.

I also feel that the existing "Enabled individual preferences for individual directories" option is a little unclear, especially after reading through the comments and questions on the other issues logged for this point (I found 9, there may be more).

---

> please do keep in mind, this suggestion is made without knowing how these settings are currently stored... I'm not much of a C# guy, so I haven't gone digging through the code yet.

in the interest of making this app _better_ than the default system app it replaces, I'd like to propose a slightly different approach..

* "Detail" view column customisations should be tied to the _view_ type first.
* individual folders should be able to override this user-set "default".

with only these two base constraints, I believe this could be implemented with the following steps:

* remove the current "Enabled individual preferences for individual directories" option entirely.
* add an option to the folder info modal (with file/folder size, attributes, etc) called "Remember custom view settings".
  * _when enabled_, this would allow the current folder to have it's own column sizes.
  * _when disabled_, this folder will fall back to the previous valid config level (as user customisations if set, otherwise use internal defaults).

I believe this should go a long way to improving the UX side of Files, which already feels light years ahead of the "new and improved Explorer" that came with Windows 11.

**Comment by yaichenbaum** [comment]
Users will be able to set the current directory preferences as the default, they'll also be able to override it in individual directories.

**Comment by ZaLiTHkA** [comment]
thanks @yair100, that sounds like what I was hoping for. 👍🏼 

..so, as an aside, which Windows 11 "improvement" are you planning to fix next? 🤣

**Comment by yaichenbaum** [comment]
Merging with #9867
