### ISSUE TITLE
Bug: Toggling "Show Alternate Data Streams" crashes app

### ISSUE THREAD

**Issue by khanhtoan529** [files-community/Files#9816]
### Description

When toggle "Show Alternate Data stream" in Setting > Perference > Hidden files and folders

**Requirements**
- Fix crash that occurs

### Files Version

2.3.11.0

### Windows Version

Windows 11 22H2 22621.457

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/9429289/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/9429291/debug.log)

**Comment by yaichenbaum** [comment]
Detailing what the option does in the app is out of the question due to the complexity, it doesn't hurt to turn it on but it's not something the regular user would be interested in. This has a pretty good introduction https://www.malwarebytes.com/blog/news/2015/07/introduction-to-alternate-data-streams

**Comment by gave92** [comment]
Does it only crash in columns view mode?

**Comment by khanhtoan529** [comment]
> Does it only crash in columns view mode?

It crashed even in normal mode

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by khanhtoan529** [comment]
yeah, it's fixed now
