### ISSUE TITLE
Bug: Share dialog doesn't use the app theme

### ISSUE THREAD

**Issue by yaira2** [files-community/Files#9922]
**Steps to reproduce**
1. Change Files theme so that it doesn't match the system theme
2. Select a file and click the share option in the toolbar
3. See that the share dialog has the wrong theme

**Steps to fix**
- Pass in the app theme when opening the share dialog

**Comment by ferrariofilippo** [comment]
@yair100 we can't fix this issue because we're limited by the APIs.
With UWP there's a method that accepts the theme as a parameter, but there's not such a method for `WinUI3`.

Here is documentation:
- <a href="https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datatransfermanager.showshareui?view=winrt-22621#windows-applicationmodel-datatransfer-datatransfermanager-showshareui(windows-applicationmodel-datatransfer-shareuioptions)">UWP `ShowShareUI(options)`</a>
- <a href="https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/display-ui-objects#for-classes-that-implement-idatatransfermanagerinterop">WinUI3 workaround</a> (needed to use APIs)
- <a href="https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idatatransfermanagerinterop-showshareuiforwindow">Workaround method</a> (Note that there is no overload to pass the theme)

**Comment by yaichenbaum** [comment]
Is there a feature request on the WinAppSdk repo?

**Comment by ferrariofilippo** [comment]
I'll check

**Comment by ferrariofilippo** [comment]
There was no feature request related to WinUI3, so I created one
